/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../../../../index.js";

/**
 * @example
 *     {
 *         domain: "domain",
 *         body: {
 *             query_id: "query_id",
 *             conversation_id: "conversation_id",
 *             domain: "domain",
 *             text: "text",
 *             role: "role",
 *             source: "source",
 *             created_at: "2024-01-15T09:30:00Z"
 *         }
 *     }
 */
export interface CreateQueryRequest {
    domain: string;
    body: FernAI.Query;
}
