FROM cgr.dev/chainguard/wolfi-base:latest AS base
RUN apk add --no-cache nodejs-22 npm ca-certificates openssl

# TODO: This is currently unused.
# We prisma migrate in the service's Docker container which is not recommended.
# But it is easier than spinning up an EC2 instance just to run prisma migrate, right now.

RUN openssl version -v
RUN uname -a

# Create app directory
WORKDIR /app

# Copy schema and migration folder
COPY ./package.json ./package.json
COPY ./servers/fdr/prisma ./prisma

# Install prisma for the migration
RUN npm install -g prisma@5.13.0

# Don't run production as root
RUN addgroup -S -g 1001 app_user
RUN adduser -S -D -H -u 1001 -G app_user app_user
USER app_user

CMD ["prisma", "migrate", "deploy"]
