// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         url: FdrLambda.Url("url")
 *     }
 */
export interface EnsureDocsInS3Request {
    url: FdrLambda.Url;
    /**
     * When provided, uses basepath-aware S3 key format and queries
     * the database with (domain, basepath) instead of domain-only.
     */
    basepath?: string;
}
