// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         domain: "domain",
 *         fields: ["BASE_URL", "BASE_URL"]
 *     }
 */
export interface GetDocsFieldsRequest {
    domain: string;
    fields: FdrLambda.docs.v2.read.DocsDefinitionField[];
}
