// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         url: FdrLambda.Url("url")
 *     }
 */
export interface GetMetadataForUrlRequest {
    url: FdrLambda.Url;
    /**
     * When provided, returns metadata for the specific (domain, basepath) pair.
     * Used for basepath-aware docs sites.
     */
    basepath?: string;
}
