/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ApiDefinition {
    id: FdrLambda.ApiDefinitionId;
    endpoints: Record<FdrLambda.EndpointId, FdrLambda.api.latest.EndpointDefinition>;
    websockets: Record<FdrLambda.WebSocketId, FdrLambda.api.latest.WebSocketChannel>;
    webhooks: Record<FdrLambda.WebhookId, FdrLambda.api.latest.WebhookDefinition>;
    types: Record<FdrLambda.TypeId, FdrLambda.api.latest.TypeDefinition>;
    subpackages: Record<FdrLambda.api.latest.SubpackageId, FdrLambda.api.latest.SubpackageMetadata>;
    auths: Record<FdrLambda.AuthSchemeId, FdrLambda.api.latest.AuthScheme>;
    globalHeaders?: FdrLambda.api.latest.ObjectProperty[];
    snippetsConfiguration?: FdrLambda.api.v1.register.SnippetsConfig;
}
