/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface DeleteDocsSiteRequest {
    url: FdrLambda.Url;
}
