// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../../../../core/index.js";
import type * as FdrLambda from "../../../../../../../index.js";

export type Error =
    | FdrLambda.api.v1.read.getApiDefinitionFull.Error.UnauthorizedError
    | FdrLambda.api.v1.read.getApiDefinitionFull.Error.ApiDoesNotExistError
    | FdrLambda.api.v1.read.getApiDefinitionFull.Error._Unknown;

export namespace Error {
    export interface UnauthorizedError {
        error: "UnauthorizedError";
        content: string;
    }

    export interface ApiDoesNotExistError {
        error: "ApiDoesNotExistError";
    }

    export interface _Unknown {
        error: void;
        content: core.Fetcher.Error;
    }

    export interface _Visitor<_Result> {
        unauthorizedError: (value: string) => _Result;
        apiDoesNotExistError: () => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    unauthorizedError: (value: string): FdrLambda.api.v1.read.getApiDefinitionFull.Error.UnauthorizedError => {
        return {
            content: value,
            error: "UnauthorizedError",
        };
    },

    apiDoesNotExistError: (): FdrLambda.api.v1.read.getApiDefinitionFull.Error.ApiDoesNotExistError => {
        return {
            error: "ApiDoesNotExistError",
        };
    },

    _unknown: (fetcherError: core.Fetcher.Error): FdrLambda.api.v1.read.getApiDefinitionFull.Error._Unknown => {
        return {
            error: undefined,
            content: fetcherError,
        };
    },

    _visit: <_Result>(
        value: FdrLambda.api.v1.read.getApiDefinitionFull.Error,
        visitor: FdrLambda.api.v1.read.getApiDefinitionFull.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.error) {
            case "UnauthorizedError":
                return visitor.unauthorizedError(value.content);
            case "ApiDoesNotExistError":
                return visitor.apiDoesNotExistError();
            default:
                return visitor._other(value.content);
        }
    },
} as const;
