/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";
import * as core from "../../../../../../../../core/index.js";

export type Error =
    | FdrLambda.api.v1.read.getEndpointById.Error.UnauthorizedError
    | FdrLambda.api.v1.read.getEndpointById.Error.ApiDoesNotExistError
    | FdrLambda.api.v1.read.getEndpointById.Error.EndpointDoesNotExistError
    | FdrLambda.api.v1.read.getEndpointById.Error._Unknown;

export namespace Error {
    export interface UnauthorizedError {
        error: "UnauthorizedError";
        content: string;
    }

    export interface ApiDoesNotExistError {
        error: "ApiDoesNotExistError";
    }

    export interface EndpointDoesNotExistError {
        error: "EndpointDoesNotExistError";
    }

    export interface _Unknown {
        error: void;
        content: core.Fetcher.Error;
    }

    export interface _Visitor<_Result> {
        unauthorizedError: (value: string) => _Result;
        apiDoesNotExistError: () => _Result;
        endpointDoesNotExistError: () => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    unauthorizedError: (value: string): FdrLambda.api.v1.read.getEndpointById.Error.UnauthorizedError => {
        return {
            content: value,
            error: "UnauthorizedError",
        };
    },

    apiDoesNotExistError: (): FdrLambda.api.v1.read.getEndpointById.Error.ApiDoesNotExistError => {
        return {
            error: "ApiDoesNotExistError",
        };
    },

    endpointDoesNotExistError: (): FdrLambda.api.v1.read.getEndpointById.Error.EndpointDoesNotExistError => {
        return {
            error: "EndpointDoesNotExistError",
        };
    },

    _unknown: (fetcherError: core.Fetcher.Error): FdrLambda.api.v1.read.getEndpointById.Error._Unknown => {
        return {
            error: undefined,
            content: fetcherError,
        };
    },

    _visit: <_Result>(
        value: FdrLambda.api.v1.read.getEndpointById.Error,
        visitor: FdrLambda.api.v1.read.getEndpointById.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.error) {
            case "UnauthorizedError":
                return visitor.unauthorizedError(value.content);
            case "ApiDoesNotExistError":
                return visitor.apiDoesNotExistError();
            case "EndpointDoesNotExistError":
                return visitor.endpointDoesNotExistError();
            default:
                return visitor._other(value as any);
        }
    },
} as const;
