/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         repository: "repository",
 *         base_branch: "base_branch"
 *     }
 */
export interface CreateEditingSessionRequest {
    repository: string;
    base_branch: string;
}
