// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import * as FdrLambda from "../../../../../../../index.js";

export declare namespace ReadClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ReadClient {
    protected readonly _options: ReadClient.Options;

    constructor(options: ReadClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {FdrLambda.docs.v2.read.GetMetadataForUrlRequest} request
     * @param {ReadClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.docs.v2.read.getDocsUrlMetadata({
     *         url: FdrLambda.Url("url")
     *     })
     */
    public getDocsUrlMetadata(
        request: FdrLambda.docs.v2.read.GetMetadataForUrlRequest,
        requestOptions?: ReadClient.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<FdrLambda.docs.v2.read.DocsUrlMetadata, FdrLambda.docs.v2.read.getDocsUrlMetadata.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__getDocsUrlMetadata(request, requestOptions));
    }

    private async __getDocsUrlMetadata(
        request: FdrLambda.docs.v2.read.GetMetadataForUrlRequest,
        requestOptions?: ReadClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<FdrLambda.docs.v2.read.DocsUrlMetadata, FdrLambda.docs.v2.read.getDocsUrlMetadata.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FdrLambdaEnvironment.Prod,
                "/v2/registry/docs/metadata-for-url",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs:
                requestOptions?.timeoutInSeconds != null
                    ? requestOptions.timeoutInSeconds * 1000
                    : this._options?.timeoutInSeconds != null
                      ? this._options?.timeoutInSeconds * 1000
                      : undefined,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as FdrLambda.docs.v2.read.DocsUrlMetadata,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as FdrLambda.docs.v2.read.getDocsUrlMetadata.Error)?.error) {
                case "DomainNotRegisteredError":
                    return {
                        data: {
                            ok: false,
                            error: _response.error.body as FdrLambda.docs.v2.read.getDocsUrlMetadata.Error,
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: FdrLambda.docs.v2.read.getDocsUrlMetadata.Error._unknown(_response.error),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * @param {FdrLambda.docs.v2.read.LoadDocsForUrlRequest} request
     * @param {ReadClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.docs.v2.read.getDocsForUrl({
     *         url: FdrLambda.Url("url")
     *     })
     */
    public getDocsForUrl(
        request: FdrLambda.docs.v2.read.LoadDocsForUrlRequest,
        requestOptions?: ReadClient.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<FdrLambda.docs.v2.read.LoadDocsForUrlResponse, FdrLambda.docs.v2.read.getDocsForUrl.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__getDocsForUrl(request, requestOptions));
    }

    private async __getDocsForUrl(
        request: FdrLambda.docs.v2.read.LoadDocsForUrlRequest,
        requestOptions?: ReadClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<FdrLambda.docs.v2.read.LoadDocsForUrlResponse, FdrLambda.docs.v2.read.getDocsForUrl.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FdrLambdaEnvironment.Prod,
                "/v2/registry/docs/load-with-url",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs:
                requestOptions?.timeoutInSeconds != null
                    ? requestOptions.timeoutInSeconds * 1000
                    : this._options?.timeoutInSeconds != null
                      ? this._options?.timeoutInSeconds * 1000
                      : undefined,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as FdrLambda.docs.v2.read.LoadDocsForUrlResponse,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as FdrLambda.docs.v2.read.getDocsForUrl.Error)?.error) {
                case "DomainNotRegisteredError":
                case "UnauthorizedError":
                    return {
                        data: {
                            ok: false,
                            error: _response.error.body as FdrLambda.docs.v2.read.getDocsForUrl.Error,
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: FdrLambda.docs.v2.read.getDocsForUrl.Error._unknown(_response.error),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Loads docs from the database and stores them in S3.
     * Returns the S3 URL where the docs definition can be accessed.
     * This endpoint always writes to S3 idempotently, regardless of whether the docs already exist in S3.
     *
     * @param {FdrLambda.docs.v2.read.EnsureDocsInS3Request} request
     * @param {ReadClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.docs.v2.read.ensureDocsInS3({
     *         url: FdrLambda.Url("url")
     *     })
     */
    public ensureDocsInS3(
        request: FdrLambda.docs.v2.read.EnsureDocsInS3Request,
        requestOptions?: ReadClient.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<FdrLambda.docs.v2.read.EnsureDocsInS3Response, FdrLambda.docs.v2.read.ensureDocsInS3.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__ensureDocsInS3(request, requestOptions));
    }

    private async __ensureDocsInS3(
        request: FdrLambda.docs.v2.read.EnsureDocsInS3Request,
        requestOptions?: ReadClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<FdrLambda.docs.v2.read.EnsureDocsInS3Response, FdrLambda.docs.v2.read.ensureDocsInS3.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FdrLambdaEnvironment.Prod,
                "/v2/registry/docs/ensure-docs-in-s3",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs:
                requestOptions?.timeoutInSeconds != null
                    ? requestOptions.timeoutInSeconds * 1000
                    : this._options?.timeoutInSeconds != null
                      ? this._options?.timeoutInSeconds * 1000
                      : undefined,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as FdrLambda.docs.v2.read.EnsureDocsInS3Response,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as FdrLambda.docs.v2.read.ensureDocsInS3.Error)?.error) {
                case "DomainNotRegisteredError":
                case "UnauthorizedError":
                    return {
                        data: {
                            ok: false,
                            error: _response.error.body as FdrLambda.docs.v2.read.ensureDocsInS3.Error,
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: FdrLambda.docs.v2.read.ensureDocsInS3.Error._unknown(_response.error),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    /**
     * Loads specific fields from the docs definition with proper conversion (e.g., S3 URLs resolved).
     * This is more efficient than loading the entire docs definition when you only need specific parts.
     *
     * @param {FdrLambda.docs.v2.read.GetDocsFieldsRequest} request
     * @param {ReadClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.docs.v2.read.getDocsFields({
     *         domain: "domain",
     *         fields: ["BASE_URL", "BASE_URL"]
     *     })
     */
    public getDocsFields(
        request: FdrLambda.docs.v2.read.GetDocsFieldsRequest,
        requestOptions?: ReadClient.RequestOptions,
    ): core.HttpResponsePromise<
        core.APIResponse<FdrLambda.docs.v2.read.GetDocsFieldsResponse, FdrLambda.docs.v2.read.getDocsFields.Error>
    > {
        return core.HttpResponsePromise.fromPromise(this.__getDocsFields(request, requestOptions));
    }

    private async __getDocsFields(
        request: FdrLambda.docs.v2.read.GetDocsFieldsRequest,
        requestOptions?: ReadClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<
            core.APIResponse<FdrLambda.docs.v2.read.GetDocsFieldsResponse, FdrLambda.docs.v2.read.getDocsFields.Error>
        >
    > {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FdrLambdaEnvironment.Prod,
                "/v2/registry/docs/load-fields",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs:
                requestOptions?.timeoutInSeconds != null
                    ? requestOptions.timeoutInSeconds * 1000
                    : this._options?.timeoutInSeconds != null
                      ? this._options?.timeoutInSeconds * 1000
                      : undefined,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: _response.body as FdrLambda.docs.v2.read.GetDocsFieldsResponse,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as FdrLambda.docs.v2.read.getDocsFields.Error)?.error) {
                case "DomainNotRegisteredError":
                case "UnauthorizedError":
                    return {
                        data: {
                            ok: false,
                            error: _response.error.body as FdrLambda.docs.v2.read.getDocsFields.Error,
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: FdrLambda.docs.v2.read.getDocsFields.Error._unknown(_response.error),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
