/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";
import * as core from "../../../../../../../../core/index.js";

export type Error =
    | FdrLambda.docs.v2.read.ensureDocsInS3.Error.DomainNotRegisteredError
    | FdrLambda.docs.v2.read.ensureDocsInS3.Error.UnauthorizedError
    | FdrLambda.docs.v2.read.ensureDocsInS3.Error._Unknown;

export namespace Error {
    export interface DomainNotRegisteredError {
        error: "DomainNotRegisteredError";
    }

    export interface UnauthorizedError {
        error: "UnauthorizedError";
        content: string;
    }

    export interface _Unknown {
        error: void;
        content: core.Fetcher.Error;
    }

    export interface _Visitor<_Result> {
        domainNotRegisteredError: () => _Result;
        unauthorizedError: (value: string) => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    domainNotRegisteredError: (): FdrLambda.docs.v2.read.ensureDocsInS3.Error.DomainNotRegisteredError => {
        return {
            error: "DomainNotRegisteredError",
        };
    },

    unauthorizedError: (value: string): FdrLambda.docs.v2.read.ensureDocsInS3.Error.UnauthorizedError => {
        return {
            content: value,
            error: "UnauthorizedError",
        };
    },

    _unknown: (fetcherError: core.Fetcher.Error): FdrLambda.docs.v2.read.ensureDocsInS3.Error._Unknown => {
        return {
            error: undefined,
            content: fetcherError,
        };
    },

    _visit: <_Result>(
        value: FdrLambda.docs.v2.read.ensureDocsInS3.Error,
        visitor: FdrLambda.docs.v2.read.ensureDocsInS3.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.error) {
            case "DomainNotRegisteredError":
                return visitor.domainNotRegisteredError();
            case "UnauthorizedError":
                return visitor.unauthorizedError(value.content);
            default:
                return visitor._other(value as any);
        }
    },
} as const;
