[mypy]
python_executable = .venv/bin/python
files = src
mypy_path = .
explicit_package_bases = True
ignore_missing_imports = True
no_site_packages = True
namespace_packages = True
exclude = ^(\.venv/)

warn_redundant_casts = True
disallow_any_generics = True
check_untyped_defs = True
no_implicit_reexport = True

# for strict mypy
disallow_untyped_defs = True
