/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Settings {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Settings {
    protected readonly _options: Settings.Options;

    constructor(_options: Settings.Options = {}) {
        this._options = _options;
    }

    /**
     * Get settings for a domain and organization.
     *
     * @param {FernAI.GetDocsSettingsRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.getDocsSettings({
     *         domain: "domain"
     *     })
     */
    public getDocsSettings(
        request: FernAI.GetDocsSettingsRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.GetSettingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getDocsSettings(request, requestOptions));
    }

    private async __getDocsSettings(
        request: FernAI.GetDocsSettingsRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.GetSettingsResponse>> {
        const { domain } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/docs",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetSettingsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling GET /settings/ask-ai/docs.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get settings for a domain and organization.
     *
     * @param {FernAI.GetSlackSettingsRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.getSlackSettings({
     *         domain: "domain"
     *     })
     */
    public getSlackSettings(
        request: FernAI.GetSlackSettingsRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.GetSettingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSlackSettings(request, requestOptions));
    }

    private async __getSlackSettings(
        request: FernAI.GetSlackSettingsRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.GetSettingsResponse>> {
        const { domain } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/slack",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetSettingsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling GET /settings/ask-ai/slack.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get settings for a domain and organization.
     *
     * @param {FernAI.GetDiscordSettingsRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.getDiscordSettings({
     *         domain: "domain"
     *     })
     */
    public getDiscordSettings(
        request: FernAI.GetDiscordSettingsRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.GetSettingsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getDiscordSettings(request, requestOptions));
    }

    private async __getDiscordSettings(
        request: FernAI.GetDiscordSettingsRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.GetSettingsResponse>> {
        const { domain } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/discord",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.GetSettingsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling GET /settings/ask-ai/discord.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Enable Ask AI for multiple domains with specified locations and trigger reindex.
     *
     * Args:
     *     request: Request containing domains, org_name, and locations to enable
     *
     * @param {FernAI.EnableAskAiRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.enableAskAi({
     *         domains: ["domains"],
     *         org_name: "org_name",
     *         locations: ["locations"]
     *     })
     */
    public enableAskAi(
        request: FernAI.EnableAskAiRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.EnableAskAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__enableAskAi(request, requestOptions));
    }

    private async __enableAskAi(
        request: FernAI.EnableAskAiRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.EnableAskAiResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/enable",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.EnableAskAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /settings/ask-ai/enable.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Toggle Ask AI setting and return job_id for tracking.
     *
     * Args:
     *     domain: Domain to toggle Ask AI for
     *     org_name: Organization name
     *     preview: Whether this is a preview deployment
     *     locations: Optional list of locations to enable. Valid values: docs, slack, discord
     *
     * @param {FernAI.ToggleAskAiRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.toggleAskAi({
     *         domain: "domain",
     *         org_name: "org_name",
     *         preview: true
     *     })
     */
    public toggleAskAi(
        request: FernAI.ToggleAskAiRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.ToggleAskAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__toggleAskAi(request, requestOptions));
    }

    private async __toggleAskAi(
        request: FernAI.ToggleAskAiRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.ToggleAskAiResponse>> {
        const { domain, org_name: orgName, preview, locations } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        _queryParams["org_name"] = orgName;
        if (preview != null) {
            _queryParams["preview"] = preview.toString();
        }

        if (locations != null) {
            if (Array.isArray(locations)) {
                _queryParams["locations"] = locations.map((item) => item);
            } else {
                _queryParams["locations"] = locations;
            }
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/toggle",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ToggleAskAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /settings/ask-ai/toggle.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Manually trigger reindex for an already enabled Ask AI setup.
     *
     * @param {FernAI.ReindexAskAiRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.reindexAskAi({
     *         domain: "domain",
     *         org_name: "org_name"
     *     })
     */
    public reindexAskAi(
        request: FernAI.ReindexAskAiRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.ToggleAskAiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__reindexAskAi(request, requestOptions));
    }

    private async __reindexAskAi(
        request: FernAI.ReindexAskAiRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.ToggleAskAiResponse>> {
        const { domain, org_name: orgName } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        if (orgName != null) {
            _queryParams["org_name"] = orgName;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/reindex",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ToggleAskAiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /settings/ask-ai/reindex.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get the status of Ask AI toggle operation.
     *
     * @param {FernAI.GetToggleStatusRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.getToggleStatus({
     *         domain: "domain"
     *     })
     */
    public getToggleStatus(
        request: FernAI.GetToggleStatusRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.ToggleStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getToggleStatus(request, requestOptions));
    }

    private async __getToggleStatus(
        request: FernAI.GetToggleStatusRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.ToggleStatusResponse>> {
        const { domain } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/toggle/status",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ToggleStatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling GET /settings/ask-ai/toggle/status.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Handle callback from Upstash QStash when preview reindex completes.
     *
     * @param {FernAI.UpstashCallbackRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.reindexPreviewCallback({
     *         status: 1,
     *         sourceMessageId: "sourceMessageId"
     *     })
     */
    public reindexPreviewCallback(
        request: FernAI.UpstashCallbackRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__reindexPreviewCallback(request, requestOptions));
    }

    private async __reindexPreviewCallback(
        request: FernAI.UpstashCallbackRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/reindex-preview-callback",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling POST /settings/reindex-preview-callback.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Set the job_id for a domain when reindex starts processing.
     *
     * @param {FernAI.SetJobIdRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.setJobId({
     *         domain: "domain",
     *         job_id: "job_id"
     *     })
     */
    public setJobId(
        request: FernAI.SetJobIdRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<FernAI.SetJobIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setJobId(request, requestOptions));
    }

    private async __setJobId(
        request: FernAI.SetJobIdRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.SetJobIdResponse>> {
        const { domain, job_id: jobId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["domain"] = domain;
        _queryParams["job_id"] = jobId;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/set-job-id",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.SetJobIdResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError("Timeout exceeded when calling POST /settings/ask-ai/set-job-id.");
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Handle callback from SQS reindexing worker when reindex completes.
     *
     * @param {FernAI.ReindexCallbackRequest} request
     * @param {Settings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.settings.reindexCallback({
     *         status: "success",
     *         sourceMessageId: "sourceMessageId"
     *     })
     */
    public reindexCallback(
        request: FernAI.ReindexCallbackRequest,
        requestOptions?: Settings.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__reindexCallback(request, requestOptions));
    }

    private async __reindexCallback(
        request: FernAI.ReindexCallbackRequest,
        requestOptions?: Settings.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                "settings/ask-ai/reindex-callback",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling POST /settings/ask-ai/reindex-callback.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
