"use client";

import { useRouter } from "@bprogress/next/app";
import {
    constructEditorSlug,
    createMdxFrontmatter,
    extractLiveSidebarFromRootNode,
    getAllPageContainersFromSidebarRootNode,
    getClientPageDefaultFilename,
    type PageContainerWithTraversalContext,
    type SerializableFoundNode,
    useNavigation
} from "@fern-docs/components/navigation";
import { useParams } from "next/navigation";
import type React from "react";
import { useCallback, useEffect, useMemo, useState } from "react";

import type { Auth0OrgName } from "@/app/services/auth0/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { pageTitleToSlug } from "@/utils/pageTitleToSlug";
import type { EncodedDocsUrl } from "@/utils/types";

interface CreateClientPageProps {
    children: React.ReactNode;
    disabled?: boolean;
    /** The base found node to create the page from */
    baseFoundNode: SerializableFoundNode;
}

export function CreateClientPage({ children, disabled = false, baseFoundNode }: CreateClientPageProps) {
    const [isPopoverOpen, setIsPopoverOpen] = useState(false);
    const [pageTitle, setPageTitle] = useState("");
    const [pageSlug, setPageSlug] = useState("");
    const [selectedContainer, setSelectedContainer] = useState<PageContainerWithTraversalContext | null>(null);
    const [isCreating, setIsCreating] = useState(false);
    const [hasAttemptedSubmission, setHasAttemptedSubmission] = useState(false);
    const router = useRouter();
    const params = useParams();

    const navigationSnapshot = useNavigation();
    const { registeredPages, createClientPage, rootNode } = navigationSnapshot;

    // Get all available containers (sections + root-level containers) from the navigation tree
    // Use rootNode from NavigationStore instead of baseFoundNode.sidebar to get live updates (e.g., renames)
    const allContainers = useMemo(() => {
        // Try to extract live sidebar from rootNode first
        const liveSidebar = extractLiveSidebarFromRootNode(rootNode, baseFoundNode.currentTab?.slug);
        if (liveSidebar) {
            const containers = getAllPageContainersFromSidebarRootNode(liveSidebar, baseFoundNode.currentTab?.slug);
            return containers;
        }

        // Fallback to baseFoundNode.sidebar (initial server state)
        const containers = baseFoundNode.sidebar
            ? getAllPageContainersFromSidebarRootNode(baseFoundNode.sidebar, baseFoundNode.currentTab?.slug)
            : [];
        return containers;
        // Note: version dependency ensures re-computation when store updates (e.g., section renames).
        // Depending only on rootNode may not trigger re-computation due to React's dependency comparison.
    }, [rootNode, baseFoundNode.sidebar, baseFoundNode.currentTab]);

    // Set default container on first load
    useEffect(() => {
        if (allContainers.length > 0 && !selectedContainer) {
            setSelectedContainer(allContainers[0] ?? null);
        }
    }, [allContainers, selectedContainer]);

    // Auto-generate slug from page title
    // For root-level containers, use only the page title slug without a section prefix
    const autoGeneratedSlug = useMemo(() => {
        if (!pageTitle) {
            return "";
        }
        const pageTitleSlug = pageTitleToSlug(pageTitle);

        // Check if this is a root-level container
        if (selectedContainer && "isRootLevel" in selectedContainer && selectedContainer.isRootLevel) {
            // For root-level pages, use the container slug (tab slug) as the prefix
            return selectedContainer.slug ? `${selectedContainer.slug}/${pageTitleSlug}` : pageTitleSlug;
        }

        // For section pages, use the section slug as prefix
        return selectedContainer?.slug ? `${selectedContainer.slug}/${pageTitleSlug}` : pageTitleSlug;
    }, [pageTitle, selectedContainer]);

    // Use custom slug if provided, otherwise use auto-generated
    const finalSlug = pageSlug || autoGeneratedSlug;

    // Field-specific errors for real-time validation
    const errors = useMemo(() => {
        const validatePageTitle = () => {
            if (!pageTitle) {
                return "Page title is required";
            }

            if (pageTitle !== pageTitle.trim()) {
                return "Page title cannot have leading or trailing spaces";
            }

            return null;
        };

        const validateContainer = () => {
            if (!selectedContainer) {
                return "Please select a section";
            }
            return null;
        };

        const validateSlug = () => {
            if (!finalSlug) {
                return "Invalid page title - cannot generate slug";
            }

            if (finalSlug !== finalSlug.trim()) {
                return "Slug cannot have leading or trailing spaces";
            }

            if (finalSlug !== pageTitleToSlug(finalSlug)) {
                return "Invalid slug format";
            }

            // Check for duplicates
            const duplicateInRegistry = Object.values(registeredPages).some(
                (page) => page.pageData.frontmatter?.slug === finalSlug
            );

            // Check for duplicates in the selected container
            const duplicateInContainer =
                selectedContainer && "children" in selectedContainer
                    ? selectedContainer.children
                          ?.filter((child) => child.type === "page")
                          .some((page) => page.slug === finalSlug)
                    : false;

            if (duplicateInRegistry || duplicateInContainer) {
                return "A page with this slug already exists";
            }

            return null;
        };

        return {
            pageTitle: validatePageTitle(),
            container: validateContainer(),
            slug: validateSlug()
        };
    }, [pageTitle, selectedContainer, finalSlug, registeredPages]);

    // Block user submission if mandatory fields are not filled
    const blockSubmission = pageTitle.length === 0 || finalSlug.length === 0 || !selectedContainer;

    const resetForm = useCallback(() => {
        setPageTitle("");
        setPageSlug("");
        setSelectedContainer(allContainers[0] || null);
        setHasAttemptedSubmission(false);
    }, [allContainers]);

    const handleCreatePage = useCallback(async () => {
        setHasAttemptedSubmission(true);

        if (blockSubmission || errors.pageTitle || errors.container || errors.slug) {
            return;
        }

        setIsCreating(true);

        try {
            const filename = getClientPageDefaultFilename(finalSlug);

            // Close popover and reset form
            setIsPopoverOpen(false);
            resetForm();

            const orgName = params.orgName as Auth0OrgName;
            const docsUrl = params.docsUrl as EncodedDocsUrl;
            const branch = params.branch as string;

            try {
                // Register the new page in the store
                createClientPage(filename, {
                    source: "client",
                    filename: filename,
                    initialMdx: createMdxFrontmatter({
                        title: pageTitle,
                        slug: finalSlug
                    }),
                    baseFoundNode: baseFoundNode,
                    targetSectionPath: selectedContainer.sectionPath
                });

                // Navigate to the new page
                const targetUrl = constructEditorSlug({
                    orgName,
                    docsUrl,
                    branchName: branch,
                    slug: finalSlug
                });
                router.push(targetUrl);
            } catch (pageCreationError) {
                console.error("Failed to create page in store:", pageCreationError);
                throw new Error(
                    `Failed to create page in navigation: ${
                        pageCreationError instanceof Error ? pageCreationError.message : "Unknown error"
                    }`
                );
            }
        } catch (err) {
            console.error("Failed to create client page:", err);
            // Error will be shown via form validation state if needed
        } finally {
            setIsCreating(false);
        }
    }, [
        router,
        params,
        baseFoundNode,
        selectedContainer,
        pageTitle,
        finalSlug,
        createClientPage,
        blockSubmission,
        resetForm,
        errors
    ]);

    const shouldShowPageTitleError = hasAttemptedSubmission && errors.pageTitle;
    const shouldShowSlugError = hasAttemptedSubmission && errors.slug;
    const shouldShowContainerError = errors.container;

    // Button is disabled if form is invalid or currently creating
    const isCreateDisabled = blockSubmission || isCreating;

    return (
        <Popover
            open={isPopoverOpen && !disabled}
            onOpenChange={(open: boolean) => {
                if (disabled) {
                    return;
                }
                setIsPopoverOpen(open);
                if (!open) {
                    resetForm();
                    setIsCreating(false);
                }
            }}
        >
            <PopoverTrigger asChild disabled={disabled}>
                {children}
            </PopoverTrigger>
            <PopoverContent className="border-border w-80 border p-3" align="start">
                <div className="space-y-3">
                    <div className="space-y-1">
                        <label className="text-gray-1100 text-xs font-medium">Page title</label>
                        <Input
                            placeholder="Enter page title..."
                            value={pageTitle}
                            onChange={(e) => {
                                setPageTitle(e.target.value);
                                setHasAttemptedSubmission(false);
                            }}
                            className={`w-full text-sm ${shouldShowPageTitleError ? "border-red-300 focus:border-red-500" : ""}`}
                            autoFocus
                        />
                        {shouldShowPageTitleError && (
                            <div className="mt-1 text-xs text-red-600">{errors.pageTitle}</div>
                        )}
                    </div>

                    <div className="space-y-1">
                        <label className="text-gray-1100 text-xs font-medium">
                            Slug <span className="font-normal text-gray-800">(auto-generated, optional)</span>
                        </label>
                        <Input
                            placeholder={autoGeneratedSlug || "auto-generated-from-title"}
                            value={pageSlug}
                            onChange={(e) => {
                                setPageSlug(e.target.value);
                                setHasAttemptedSubmission(false);
                            }}
                            className={`w-full font-mono text-xs placeholder:text-gray-800 ${shouldShowSlugError ? "border-red-300 focus:border-red-500" : ""}`}
                        />
                        {shouldShowSlugError && <div className="mt-1 text-xs text-red-600">{errors.slug}</div>}
                    </div>

                    <div className="space-y-1">
                        <label className="text-gray-1100 text-xs font-medium">In section...</label>
                        {allContainers.length === 0 ? (
                            <div className="rounded-md border border-gray-200 p-2 text-center text-xs text-gray-800">
                                No sections available
                            </div>
                        ) : (
                            <Select
                                value={selectedContainer?.id || ""}
                                onValueChange={(value) => {
                                    const container = allContainers.find((c) => c.id === value);
                                    if (!container) {
                                        return;
                                    }
                                    setSelectedContainer(container);
                                    setHasAttemptedSubmission(false);
                                }}
                            >
                                <SelectTrigger className="h-8 w-full text-sm">
                                    <SelectValue placeholder="Select section..." />
                                </SelectTrigger>
                                <SelectContent className="border-border">
                                    {allContainers.map((container) => {
                                        // Check if this is a root-level container
                                        const isRootLevel = "isRootLevel" in container && container.isRootLevel;

                                        if (isRootLevel) {
                                            // Display "No section" for root-level containers
                                            return (
                                                <SelectItem key={container.id} value={container.id}>
                                                    <div className="flex items-center">
                                                        <span className="text-muted-foreground">No section</span>
                                                    </div>
                                                </SelectItem>
                                            );
                                        }

                                        // For sections, display the hierarchical path
                                        const sectionAncestors = container.sectionPath.filter(
                                            (ancestor) => ancestor.type === "section"
                                        );
                                        return (
                                            <SelectItem key={container.id} value={container.id}>
                                                <div className="flex items-center">
                                                    {sectionAncestors.length > 0 && (
                                                        <>
                                                            {sectionAncestors.map((ancestor, idx) => {
                                                                const isLast = idx === sectionAncestors.length - 1;
                                                                return (
                                                                    <span
                                                                        key={ancestor.id}
                                                                        className={
                                                                            !isLast
                                                                                ? "text-muted-foreground mr-1"
                                                                                : "mr-1"
                                                                        }
                                                                    >
                                                                        {ancestor.title}
                                                                        {!isLast ? " / " : ""}
                                                                    </span>
                                                                );
                                                            })}
                                                        </>
                                                    )}
                                                </div>
                                            </SelectItem>
                                        );
                                    })}
                                </SelectContent>
                            </Select>
                        )}
                        {shouldShowContainerError && (
                            <div className="mt-1 text-xs text-red-600">{errors.container}</div>
                        )}
                    </div>

                    <Button
                        onClick={handleCreatePage}
                        disabled={isCreateDisabled}
                        className="h-8 w-full cursor-pointer text-sm"
                        variant="default"
                    >
                        {isCreating ? "Creating..." : "Create"}
                    </Button>
                </div>
            </PopoverContent>
        </Popover>
    );
}
