/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         base_url: "base_url"
 *     }
 */
export interface DeleteWebsiteRequest {
    /** The base URL of the website to delete (deletes all pages from this source) */
    base_url: string;
}
