/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         job_id: "job_id"
 *     }
 */
export interface GetWebsiteStatusRequest {
    /** The job ID returned from the index endpoint */
    job_id: string;
}
