/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         page: 1,
 *         limit: 1
 *     }
 */
export interface GetWebsitesRequest {
    /** The page number for pagination */
    page?: number;
    /** The number of sources per page */
    limit?: number;
}
