/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         base_url: "base_url"
 *     }
 */
export interface IndexWebsiteRequest {
    /** The base URL to start indexing from (e.g., 'https://docs.example.com') */
    base_url: string;
    /** Domain to filter crawling (e.g., 'docs.example.com'). Defaults to base_url domain. */
    domain_filter?: string;
    /** Path prefix to restrict crawling (e.g., '/docs'). Only URLs starting with this will be crawled. */
    path_filter?: string;
    /** Regex pattern to filter URLs (e.g., 'https://example\.com/(docs|api)/.*'). */
    url_pattern?: string;
    /** Size of text chunks for splitting documents */
    chunk_size?: number;
    /** Overlap between consecutive chunks */
    chunk_overlap?: number;
    /** Minimum content length to index a page */
    min_content_length?: number;
    /** Maximum number of pages to crawl. None means unlimited. */
    max_pages?: number;
    /** Delay in seconds between requests */
    delay?: number;
    /** Version to tag all indexed pages with */
    version?: string;
    /** Product to tag all indexed pages with */
    product?: string;
    /** Whether indexed pages should be auth-gated */
    authed?: boolean;
}
