/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         base_url: "base_url"
 *     }
 */
export interface ReindexWebsiteRequest {
    /** The base URL to re-crawl (will delete old pages and re-index) */
    base_url: string;
    /** Domain to filter crawling (e.g., 'docs.example.com'). If not provided, uses previous config. */
    domain_filter?: string;
    /** Path prefix to restrict crawling (e.g., '/docs'). If not provided, uses previous config. */
    path_filter?: string;
    /** Regex pattern to filter URLs (e.g., `https://example\.com/(docs|api)/.*`). If not provided, uses previous config. */
    url_pattern?: string;
    /** Size of text chunks for splitting documents. If not provided, uses previous config. */
    chunk_size?: number;
    /** Overlap between consecutive chunks. If not provided, uses previous config. */
    chunk_overlap?: number;
    /** Minimum content length to index a page. If not provided, uses previous config. */
    min_content_length?: number;
    /** Maximum number of pages to crawl. If not provided, uses previous config. */
    max_pages?: number;
    /** Delay in seconds between requests. If not provided, uses previous config. */
    delay?: number;
    /** Version to tag all indexed pages with. If not provided, uses previous config. */
    version?: string;
    /** Product to tag all indexed pages with. If not provided, uses previous config. */
    product?: string;
    /** Whether indexed pages should be auth-gated. If not provided, uses previous config. */
    authed?: boolean;
}
