/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments.js";
import * as core from "../../../../../../core/index.js";
import { Read } from "../resources/read/client/Client.js";

export declare namespace V1 {
    export interface Options {
        environment?: core.Supplier<environments.FdrLambdaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }
}

export class V1 {
    protected _read: Read | undefined;

    constructor(protected readonly _options: V1.Options) {}

    public get read(): Read {
        return (this._read ??= new Read(this._options));
    }
}
