// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface AttributeIr {
    name: string;
    path: string;
    type: string | undefined;
    value: string | undefined;
    docstring: FdrLambda.libraryDocs.DocstringIr | undefined;
}
