// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface DocstringIr {
    summary: string | undefined;
    description: string | undefined;
    params: FdrLambda.libraryDocs.DocstringParamIr[];
    returns: FdrLambda.libraryDocs.DocstringReturnsIr | undefined;
    raises: FdrLambda.libraryDocs.DocstringRaisesIr[];
    examples: FdrLambda.libraryDocs.DocstringExampleIr[];
    notes: string[];
    warnings: string[];
}
