/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         editing_id: "editing_id"
 *     }
 */
export interface ScribeEditCallbackRequest {
    editing_id: string;
    pr_url?: string;
}
