/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         pr_url: "pr_url"
 *     }
 */
export interface ScribeSlackCallbackRequest {
    pr_url: string;
}
