"use server";

import { getCurrentSession } from "@/app/services/auth0/getCurrentSession";
import { getGitLoader } from "@/app/services/github/getGitLoader";
import type { GithubCommitableFile } from "@/app/services/github/types";
import type { DocsUrl } from "@/utils/types";

import postCreatePr from "../api/post-git-create-pr/handler";
import type { Auth0OrgName } from "../services/auth0/types";
import createBranchIfNotExists from "../services/dal/git/createBranchIfNotExists";
import postGitCommit from "../services/dal/git/postGitCommit";
import { getUpgradePrBranchName } from "../services/dal/git/request-utils";
import { assertUserHasOrganizationAccess } from "../services/dal/organization";

export async function upgradeFernVersionAction(
    orgName: Auth0OrgName,
    docsUrl: DocsUrl,
    gitUrl: string,
    currentVersion: string,
    latestVersion: string,
    baseBranch: string
): Promise<{
    success: boolean;
    error?: string;
    prUrl?: string;
    prNumber?: number;
}> {
    // 1. Check user session
    const session = await getCurrentSession();
    if (session == null) {
        return { success: false, error: "No session found" };
    }

    // 2. Check org membership
    try {
        await assertUserHasOrganizationAccess(session.accessToken, orgName);
    } catch (error) {
        return {
            success: false,
            error: error instanceof Error ? error.message : "User is not a member of the organization"
        };
    }

    // 3. Extract owner/repo from gitUrl
    const urlMatch = gitUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
    if (!urlMatch) {
        return { success: false, error: "Invalid GitHub URL" };
    }
    const owner = urlMatch[1];
    const repo = urlMatch[2]?.replace(/\.git$/, "");

    if (!owner || !repo) {
        return { success: false, error: "Invalid GitHub URL" };
    }

    // 4. Get GitLoader instance
    const loader = getGitLoader(gitUrl);

    // 5. Validate repository access
    const accessResult = await loader.validateAccess?.({
        owner,
        repo,
        site: docsUrl,
        orgName
    });

    if (accessResult?.type === "error") {
        return { success: false, error: `Access validation failed: ${accessResult.error.type}` };
    }

    try {
        // Generate branch name
        const branchName = getUpgradePrBranchName(currentVersion, latestVersion);

        // Step 1: Create a new branch (only if it doesn't exist)
        const createBranchResult = await createBranchIfNotExists({
            owner,
            repo,
            branch: branchName,
            baseBranch,
            site: docsUrl,
            orgName
        });

        if (!createBranchResult.success) {
            return {
                success: false,
                error: `Failed to create branch: ${createBranchResult.error}`
            };
        }

        // Step 2: Get current fern.config.json content and update the version
        const fernConfigResult = await loader.getFernConfigJson(owner, repo, docsUrl);

        if (fernConfigResult.type !== "ok") {
            return { success: false, error: fernConfigResult.error.type };
        }

        const { pathToFernConfigJson, ...fernConfig } = fernConfigResult.result;

        // Step 3: Commit the change (only if the content needs updating)
        const currentVersionInBranch = fernConfig.version;

        if (currentVersionInBranch !== latestVersion) {
            // Update the version
            fernConfig.version = latestVersion;
            const updatedContent = JSON.stringify(fernConfig, null, 2);
            const commitMessage = `Upgrade Fern CLI from ${currentVersion} to ${latestVersion}`;

            const files: GithubCommitableFile[] = [
                {
                    path: pathToFernConfigJson,
                    content: updatedContent
                }
            ];

            const commitResult = await postGitCommit({
                owner,
                repo,
                branch: branchName,
                message: commitMessage,
                files,
                orgName,
                site: docsUrl
            });

            if (!commitResult.success) {
                return {
                    success: false,
                    error: `Failed to commit changes: ${commitResult.error}`
                };
            }
        }

        // Step 4: Create a pull request
        const prResult = await postCreatePr({
            owner,
            repo,
            head: branchName,
            base: baseBranch,
            title: `Upgrade Fern CLI to ${latestVersion}`,
            body: `This PR upgrades the Fern CLI version from ${currentVersion} to ${latestVersion}.
\n<br>
\n🌿 _This PR was generated by Fern._
[(buildwithfern.com)](https://www.buildwithfern.com)`,
            draft: false
        });

        if (!prResult.success) {
            return {
                success: false,
                error: `Failed to create pull request: ${prResult.error}`
            };
        }

        return {
            success: true,
            prUrl: prResult.prUrl,
            prNumber: prResult.prNumber
        };
    } catch (error) {
        console.error("Failed to upgrade Fern version", error);
        return {
            success: false,
            error: error instanceof Error ? error.message : "Unknown error occurred"
        };
    }
}
