/**
 * Script to generate inlined template files for production builds.
 *
 * This reads all files from src/templates/docs-starter and generates a TypeScript
 * file with the content inlined as string literals. This is necessary because
 * Vercel serverless functions can't access source files at runtime.
 *
 * Run with: npx tsx scripts/generate-templates.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TEMPLATES_DIR = path.join(__dirname, "../src/templates/docs-starter");
const OUTPUT_FILE = path.join(__dirname, "../src/templates/docs-starter/generated-templates.ts");

const BINARY_EXTENSIONS = new Set([
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".bmp",
    ".webp",
    ".tiff",
    ".tif",
    ".pdf",
    ".zip",
    ".tar",
    ".gz",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".otf"
]);

const EXCLUDE_PATTERNS = [
    ".git",
    "node_modules",
    ".DS_Store",
    ".claude",
    "index.ts",
    "index.test.ts",
    "generated-templates.ts"
];

function isBinaryFile(filePath: string): boolean {
    const ext = path.extname(filePath).toLowerCase();
    return BINARY_EXTENSIONS.has(ext);
}

interface TemplateFile {
    path: string;
    content: string;
    encoding?: "utf-8" | "base64";
}

function readFilesRecursively(dirPath: string, relativeTo: string): TemplateFile[] {
    const files: TemplateFile[] = [];
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });

    for (const entry of entries) {
        if (EXCLUDE_PATTERNS.includes(entry.name)) {
            continue;
        }

        const fullPath = path.join(dirPath, entry.name);
        const relativePath = path.relative(relativeTo, fullPath);

        if (entry.isDirectory()) {
            const nestedFiles = readFilesRecursively(fullPath, relativeTo);
            files.push(...nestedFiles);
        } else {
            if (isBinaryFile(fullPath)) {
                const buffer = fs.readFileSync(fullPath);
                files.push({
                    path: relativePath,
                    content: buffer.toString("base64"),
                    encoding: "base64"
                });
            } else {
                const content = fs.readFileSync(fullPath, "utf-8");
                files.push({
                    path: relativePath,
                    content
                });
            }
        }
    }

    return files;
}

function escapeTemplateString(str: string): string {
    return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function generateTemplatesFile(): void {
    console.log("Reading template files from:", TEMPLATES_DIR);
    const files = readFilesRecursively(TEMPLATES_DIR, TEMPLATES_DIR);
    console.log(`Found ${files.length} template files`);

    const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-templates.ts
 *
 * This file contains all docs-starter template files inlined as string literals.
 */

export interface TemplateFile {
    path: string;
    content: string;
    encoding?: "utf-8" | "base64";
}

export const TEMPLATE_FILES: TemplateFile[] = [
${files
    .map((file) => {
        const encoding = file.encoding ? `\n        encoding: "${file.encoding}"` : "";
        return `    {
        path: ${JSON.stringify(file.path)},
        content: \`${escapeTemplateString(file.content)}\`${encoding}
    }`;
    })
    .join(",\n")}
];
`;

    fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
    console.log("Generated:", OUTPUT_FILE);
}

generateTemplatesFile();
