/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../../../../index.js";

/**
 * @example
 *     {
 *         start_date: "2024-01-15T09:30:00Z",
 *         end_date: "2024-01-15T09:30:00Z",
 *         group_by: "DAY"
 *     }
 */
export interface GetAnalyticsHistogramRequest {
    /** The start date of the period to retrieve analytics for */
    start_date?: string;
    /** The end date of the period to retrieve analytics for */
    end_date?: string;
    /** The field to group the analytics by */
    group_by?: FernAI.GroupBy;
}
