/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         dlqId: "dlqId",
 *         url: "url",
 *         status: 1
 *     }
 */
export interface QStashFailureCallback {
    dlqId: string;
    url: string;
    status: number;
    sourceHeader?: Record<string, QStashFailureCallback.SourceHeader.Value>;
}

export namespace QStashFailureCallback {
    export namespace SourceHeader {
        export type Value = string | string[];
    }
}
