export type { Availability, LinkTarget } from "./shared";
export {
    ApiDefinitionId,
    ApiDefinitionIdSchema,
    AvailabilitySchema,
    EndpointId,
    EndpointIdSchema,
    FileId,
    FileIdSchema,
    LinkTargetSchema,
    PageId,
    PageIdSchema,
    RoleId,
    RoleIdSchema,
    SubpackageId,
    SubpackageIdSchema,
    Url,
    UrlSchema,
    VersionId,
    VersionIdSchema,
    WebhookId,
    WebhookIdSchema,
    WebSocketId,
    WebSocketIdSchema
} from "./shared";
