// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface ApiNavigationConfigSubpackage {
    summaryPageId: FdrLambda.PageId | undefined;
    subpackageId: FdrLambda.api.v1.SubpackageId;
    items: FdrLambda.docs.v1.read.ApiNavigationConfigItem[];
}
