// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export type ApiNavigationConfigItem =
    | FdrLambda.docs.v1.read.ApiNavigationConfigItem.Subpackage
    | FdrLambda.docs.v1.read.ApiNavigationConfigItem.EndpointId
    | FdrLambda.docs.v1.read.ApiNavigationConfigItem.WebsocketId
    | FdrLambda.docs.v1.read.ApiNavigationConfigItem.WebhookId
    | FdrLambda.docs.v1.read.ApiNavigationConfigItem.Page;

export namespace ApiNavigationConfigItem {
    export interface Subpackage extends FdrLambda.docs.v1.read.ApiNavigationConfigSubpackage {
        type: "subpackage";
    }

    export interface EndpointId {
        type: "endpointId";
        value: FdrLambda.EndpointId;
    }

    export interface WebsocketId {
        type: "websocketId";
        value: FdrLambda.WebSocketId;
    }

    export interface WebhookId {
        type: "webhookId";
        value: FdrLambda.WebhookId;
    }

    export interface Page extends FdrLambda.docs.v1.read.PageMetadata {
        type: "page";
    }
}
