/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface ApiNavigationConfigRoot {
    summaryPageId?: FdrLambda.PageId;
    items: FdrLambda.docs.v1.read.ApiNavigationConfigItem[];
}
