// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface ApiSection extends FdrLambda.docs.v1.read.NavigationNodeMetadata {
    title: string;
    api: FdrLambda.ApiDefinitionId;
    skipUrlSlug: boolean;
    artifacts: FdrLambda.docs.v1.read.ApiArtifacts | undefined;
    showErrors: boolean;
    changelog: FdrLambda.docs.v1.read.ChangelogSection | undefined;
    navigation: FdrLambda.docs.v1.read.ApiNavigationConfigRoot | undefined;
    longScrolling: boolean | undefined;
    flattened: boolean | undefined;
}
