// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface ApiSectionV2 {
    node: FdrLambda.navigation.v1.ApiReferenceNode;
}
