/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type Background = FdrLambda.docs.v1.read.Background.Solid | FdrLambda.docs.v1.read.Background.Gradient;

export namespace Background {
    export interface Solid extends FdrLambda.docs.v1.commons.RgbaColor {
        type: "solid";
    }

    export interface Gradient {
        type: "gradient";
    }
}
