/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface ChangelogItem {
    date: string;
    pageId: FdrLambda.PageId;
    tags?: string[];
}
