/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface DocsConfig {
    title?: string;
    defaultLanguage?: FdrLambda.docs.v1.commons.ProgrammingLanguage;
    announcement?: FdrLambda.docs.v1.commons.AnnouncementConfig;
    navigation?: FdrLambda.docs.v1.read.NavigationConfig;
    root?: FdrLambda.navigation.v1.RootNode;
    navbarLinks?: FdrLambda.docs.v1.commons.NavbarLink[];
    footerLinks?: FdrLambda.docs.v1.commons.FooterLink[];
    hideNavLinks?: boolean;
    logoHeight?: FdrLambda.docs.v1.read.Height;
    logoHref?: FdrLambda.Url;
    favicon?: FdrLambda.FileId;
    metadata?: FdrLambda.docs.v1.commons.MetadataConfig;
    redirects?: FdrLambda.docs.v1.commons.RedirectConfig[];
    colorsV3?: FdrLambda.docs.v1.read.ColorsConfigV3;
    layout?: FdrLambda.docs.v1.commons.DocsLayoutConfig;
    settings?: FdrLambda.docs.v1.commons.DocsSettingsConfig;
    typographyV2?: FdrLambda.docs.v1.commons.DocsTypographyConfigV2;
    analyticsConfig?: FdrLambda.docs.v1.commons.AnalyticsConfig;
    integrations?: FdrLambda.docs.v1.commons.IntegrationsConfig;
    css?: FdrLambda.docs.v1.commons.CssConfig;
    js?: FdrLambda.docs.v1.commons.JsConfig;
    aiChatConfig?: FdrLambda.docs.v1.commons.AiChatConfig;
    pageActions?: FdrLambda.docs.v1.commons.PageActionsConfig;
}
