/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface DocsConfig {
    title: string | undefined;
    defaultLanguage: FdrLambda.docs.v1.commons.ProgrammingLanguage | undefined;
    announcement: FdrLambda.docs.v1.commons.AnnouncementConfig | undefined;
    navigation: FdrLambda.docs.v1.read.NavigationConfig | undefined;
    root: FdrLambda.navigation.v1.RootNode | undefined;
    navbarLinks: FdrLambda.docs.v1.commons.NavbarLink[] | undefined;
    footerLinks: FdrLambda.docs.v1.commons.FooterLink[] | undefined;
    hideNavLinks: boolean | undefined;
    logoHeight: FdrLambda.docs.v1.read.Height | undefined;
    logoHref: FdrLambda.Url | undefined;
    favicon: FdrLambda.FileId | undefined;
    metadata: FdrLambda.docs.v1.commons.MetadataConfig | undefined;
    redirects: FdrLambda.docs.v1.commons.RedirectConfig[] | undefined;
    colorsV3: FdrLambda.docs.v1.read.ColorsConfigV3 | undefined;
    layout: FdrLambda.docs.v1.commons.DocsLayoutConfig | undefined;
    theme: FdrLambda.docs.v1.commons.DocsThemeConfig | undefined;
    settings: FdrLambda.docs.v1.commons.DocsSettingsConfig | undefined;
    typographyV2: FdrLambda.docs.v1.commons.DocsTypographyConfigV2 | undefined;
    analyticsConfig: FdrLambda.docs.v1.commons.AnalyticsConfig | undefined;
    integrations: FdrLambda.docs.v1.commons.IntegrationsConfig | undefined;
    css: FdrLambda.docs.v1.commons.CssConfig | undefined;
    js: FdrLambda.docs.v1.commons.JsConfig | undefined;
    aiChatConfig: FdrLambda.docs.v1.commons.AiChatConfig | undefined;
    pageActions: FdrLambda.docs.v1.commons.PageActionsConfig | undefined;
}
