/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type File_ = FdrLambda.docs.v1.read.File_.Url | FdrLambda.docs.v1.read.File_.Image;

export namespace File_ {
    export interface Url extends FdrLambda.docs.v1.read.UrlFile {
        type: "url";
    }

    export interface Image extends FdrLambda.docs.v1.read.ImageFile {
        type: "image";
    }
}
