// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface GitHubRepo {
    name: string;
    url: FdrLambda.Url;
}
