/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface MavenPackage {
    coordinate: string;
    githubRepo: FdrLambda.docs.v1.read.GitHubRepo;
    version: string;
}
