/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type NavigationTab =
    | FdrLambda.docs.v1.read.NavigationTab.Group
    | FdrLambda.docs.v1.read.NavigationTab.Link
    | FdrLambda.docs.v1.read.NavigationTab.Changelog
    | FdrLambda.docs.v1.read.NavigationTab.ChangelogV3;

export namespace NavigationTab {
    export interface Group extends FdrLambda.docs.v1.read.NavigationTabGroup {
        type: "group";
    }

    export interface Link extends FdrLambda.docs.v1.read.NavigationTabLink {
        type: "link";
    }

    export interface Changelog extends FdrLambda.docs.v1.read.ChangelogSection {
        type: "changelog";
    }

    export interface ChangelogV3 extends FdrLambda.docs.v1.read.ChangelogSectionV3 {
        type: "changelogV3";
    }
}
