/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface PageMetadata extends FdrLambda.docs.v1.read.NavigationNodeMetadata {
    id: FdrLambda.PageId;
    title: string;
}
