/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export type PublishedSdk =
    | FdrLambda.docs.v1.read.PublishedSdk.Npm
    | FdrLambda.docs.v1.read.PublishedSdk.Maven
    | FdrLambda.docs.v1.read.PublishedSdk.Pypi;

export namespace PublishedSdk {
    export interface Npm extends FdrLambda.docs.v1.read.NpmPackage {
        type: "npm";
    }

    export interface Maven extends FdrLambda.docs.v1.read.MavenPackage {
        type: "maven";
    }

    export interface Pypi extends FdrLambda.docs.v1.read.PypiPackage {
        type: "pypi";
    }
}
