/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface ThemeConfig {
    logo?: FdrLambda.FileId;
    backgroundImage?: FdrLambda.FileId;
    accentPrimary: FdrLambda.docs.v1.commons.RgbaColor;
    background: FdrLambda.docs.v1.read.Background;
    border?: FdrLambda.docs.v1.commons.RgbaColor;
    sidebarBackground?: FdrLambda.docs.v1.commons.RgbaColor;
    headerBackground?: FdrLambda.docs.v1.commons.RgbaColor;
    cardBackground?: FdrLambda.docs.v1.commons.RgbaColor;
}
