/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type UnversionedNavigationConfig =
    | FdrLambda.docs.v1.read.UnversionedTabbedNavigationConfig
    | FdrLambda.docs.v1.read.UnversionedUntabbedNavigationConfig;
