/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface UnversionedTabbedNavigationConfig {
    tabs: FdrLambda.docs.v1.read.NavigationTab[];
    landingPage: FdrLambda.docs.v1.read.PageMetadata | undefined;
}
