/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type PathPart = FdrLambda.api.latest.PathPart.Literal | FdrLambda.api.latest.PathPart.PathParameter;

export namespace PathPart {
    export interface Literal {
        type: "literal";
        value: string;
    }

    export interface PathParameter {
        type: "pathParameter";
        value: FdrLambda.PropertyKey;
    }
}
