/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface SubpackageMetadata {
    id: FdrLambda.api.latest.SubpackageId;
    name: string;
    displayName?: string;
}
