/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface WithNamespace {
    /** A list of subpackage names based on the order in which values are rendered in the frontend. */
    namespace?: FdrLambda.api.latest.SubpackageId[];
}
