"""initial schema

Revision ID: 1a06a4d351f9
Revises: 
Create Date: 2025-10-31 16:04:31.742312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a06a4d351f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_reports_domain'), table_name='conversation_reports')
    op.drop_table('conversation_reports')
    op.drop_table('code_snippets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snippets',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chunk', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('code_snippets_pkey'))
    )
    op.create_table('conversation_reports',
    sa.Column('conversation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('conversation_reports_pkey'))
    )
    op.create_index(op.f('ix_conversation_reports_domain'), 'conversation_reports', ['domain'], unique=False)
    # ### end Alembic commands ###
