"""create reindexing_metadata table

Revision ID: 560b22c0ccce
Revises: create_code_table
Create Date: 2025-11-25 19:00:17.127543

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "560b22c0ccce"
down_revision: Union[str, Sequence[str], None] = "create_code_table"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reindexing_metadata",
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("memory_mb", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("task_arn", sa.String(), nullable=True),
        sa.Column("sqs_message_id", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("num_inserted", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("task_arns", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("domain"),
    )
    op.create_index("idx_reindexing_metadata_task_arn", "reindexing_metadata", ["task_arn"], unique=False)
    op.create_index("idx_reindexing_metadata_status", "reindexing_metadata", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reindexing_metadata_status", table_name="reindexing_metadata")
    op.drop_index("idx_reindexing_metadata_task_arn", table_name="reindexing_metadata")
    op.drop_table("reindexing_metadata")
    # ### end Alembic commands ###
