"""create websites table

Revision ID: 8e63cf285ea3
Revises: 62afaf912daa
Create Date: 2025-11-04 12:28:06.823218

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e63cf285ea3"
down_revision: Union[str, Sequence[str], None] = "62afaf912daa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "websites",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("page_url", sa.String(), nullable=False),
        sa.Column("chunk", sa.String(), nullable=False),
        sa.Column("document", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("product", sa.String(), nullable=True),
        sa.Column("keywords", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("authed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_websites_domain", "websites", ["domain"], unique=False)
    op.create_index("idx_websites_base_url", "websites", ["base_url"], unique=False)
    op.create_index("idx_websites_domain_base_url", "websites", ["domain", "base_url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_websites_domain_base_url", table_name="websites")
    op.drop_index("idx_websites_base_url", table_name="websites")
    op.drop_index("idx_websites_domain", table_name="websites")
    op.drop_table("websites")
    # ### end Alembic commands ###
