"""create content_hashes table

Revision ID: create_content_hashes_table
Revises: 560b22c0ccce
Create Date: 2025-12-04 00:00:00.000000

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "create_content_hashes_table"
down_revision: Union[str, Sequence[str], None] = "560b22c0ccce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_hashes",
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=False, comment="FDR PageId or EndpointId"),
        sa.Column(
            "content_hash",
            sa.String(),
            nullable=False,
            comment="SHA-256 hash of page markdown or endpoint document content",
        ),
        sa.Column("indexed_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("domain", "parent_id"),
    )
    op.create_index("idx_content_hashes_domain", "content_hashes", ["domain"], unique=False)
    op.create_index("idx_content_hashes_domain_parent_id", "content_hashes", ["domain", "parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_content_hashes_domain_parent_id", table_name="content_hashes")
    op.drop_index("idx_content_hashes_domain", table_name="content_hashes")
    op.drop_table("content_hashes")
    # ### end Alembic commands ###
