/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Scribe {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Scribe {
    protected readonly _options: Scribe.Options;

    constructor(_options: Scribe.Options = {}) {
        this._options = _options;
    }

    /**
     * Callback endpoint for Scribe to post PR URLs back to Slack threads.
     *
     * @param {string} teamId
     * @param {string} channelId
     * @param {string} threadTs
     * @param {FernAI.ScribeSlackCallbackRequest} request
     * @param {Scribe.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.scribe.slackCallback("team_id", "channel_id", "thread_ts", {
     *         pr_url: "pr_url"
     *     })
     */
    public slackCallback(
        teamId: string,
        channelId: string,
        threadTs: string,
        request: FernAI.ScribeSlackCallbackRequest,
        requestOptions?: Scribe.RequestOptions,
    ): core.HttpResponsePromise<FernAI.ScribeSlackCallbackResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__slackCallback(teamId, channelId, threadTs, request, requestOptions),
        );
    }

    private async __slackCallback(
        teamId: string,
        channelId: string,
        threadTs: string,
        request: FernAI.ScribeSlackCallbackRequest,
        requestOptions?: Scribe.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.ScribeSlackCallbackResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `scribe/callback/slack/${encodeURIComponent(teamId)}/${encodeURIComponent(channelId)}/${encodeURIComponent(threadTs)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ScribeSlackCallbackResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling POST /scribe/callback/slack/{team_id}/{channel_id}/{thread_ts}.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} teamId
     * @param {string} channelId
     * @param {string} threadTs
     * @param {FernAI.ScribeEditCallbackRequest} request
     * @param {Scribe.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.scribe.editCallback("team_id", "channel_id", "thread_ts", {
     *         editing_id: "editing_id"
     *     })
     */
    public editCallback(
        teamId: string,
        channelId: string,
        threadTs: string,
        request: FernAI.ScribeEditCallbackRequest,
        requestOptions?: Scribe.RequestOptions,
    ): core.HttpResponsePromise<FernAI.ScribeEditCallbackResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__editCallback(teamId, channelId, threadTs, request, requestOptions),
        );
    }

    private async __editCallback(
        teamId: string,
        channelId: string,
        threadTs: string,
        request: FernAI.ScribeEditCallbackRequest,
        requestOptions?: Scribe.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.ScribeEditCallbackResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `scribe/callback/slack/edit/${encodeURIComponent(teamId)}/${encodeURIComponent(channelId)}/${encodeURIComponent(threadTs)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.ScribeEditCallbackResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling POST /scribe/callback/slack/edit/{team_id}/{channel_id}/{thread_ts}.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
