/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         index_name: "index_name",
 *         parent_ids: ["parent_ids"]
 *     }
 */
export interface SyncIndexIncrementalRequest {
    /** The name of the index to sync */
    index_name: string;
    /** List of parent_ids to incrementally sync */
    parent_ids: string[];
}
