import type { ExampleEndpointCall } from "@fern-api/fdr-sdk/api-definition";

/**
 * Check if a value is non-empty (not null, not undefined, not empty object/array/string)
 */
function hasNonEmptyValue(value: unknown): boolean {
    if (value == null) {
        return false;
    }
    if (typeof value === "object") {
        if (Array.isArray(value)) {
            return value.length > 0;
        }
        return Object.keys(value).length > 0;
    }
    if (typeof value === "string") {
        return value.length > 0;
    }
    return true;
}

/**
 * Check if a parameter value is meaningful (not a placeholder like `:key`)
 */
function isMeaningfulParamValue(key: string, value: unknown): boolean {
    if (value == null) {
        return false;
    }
    if (typeof value === "string") {
        if (value.length === 0) {
            return false;
        }
        if (value === `:${key}`) {
            return false;
        }
    }
    return true;
}

/**
 * Check if params object has any meaningful values
 */
function hasMeaningfulParams(params: Record<string, unknown> | undefined): boolean {
    if (params == null) {
        return false;
    }
    return Object.entries(params).some(([key, value]) => isMeaningfulParamValue(key, value));
}

/**
 * Check if an example has request-side data (requestBody, pathParameters, or queryParameters)
 */
export function hasRequestSideData(example: ExampleEndpointCall): boolean {
    if (example.requestBody != null && hasNonEmptyValue(example.requestBody.value)) {
        return true;
    }
    if (hasMeaningfulParams(example.pathParameters)) {
        return true;
    }
    if (hasMeaningfulParams(example.queryParameters)) {
        return true;
    }
    return false;
}

/**
 * Check if an example name indicates it's auto-generated (ends with "_example")
 */
function isAutoGeneratedName(name: string | null | undefined): boolean {
    return name?.endsWith("_example") ?? false;
}

/**
 * Check if an example is user-defined (has a name that's not auto-generated)
 */
function isUserDefinedExample(example: ExampleEndpointCall): boolean {
    const name = example.name;
    return name != null && !isAutoGeneratedName(name);
}

/**
 * Filter examples for the API explorer to only show examples with request-side data.
 * When user-defined examples exist, auto-generated and unnamed examples are filtered out.
 *
 * @param examples - The examples to filter
 * @returns Object containing filtered examples and a mapping from filtered index to original index
 */
export function filterExamplesForExplorer(examples: ExampleEndpointCall[] | undefined): {
    filteredExamples: ExampleEndpointCall[];
    indexMapping: number[];
} {
    if (!examples || examples.length === 0) {
        return { filteredExamples: [], indexMapping: [] };
    }

    const examplesWithRequestData = examples
        .map((example, index) => ({ example, originalIndex: index }))
        .filter(({ example }) => hasRequestSideData(example));

    if (examplesWithRequestData.length === 0) {
        return { filteredExamples: [], indexMapping: [] };
    }

    const hasUserDefinedExample = examplesWithRequestData.some(({ example }) => isUserDefinedExample(example));

    let finalExamples: { example: ExampleEndpointCall; originalIndex: number }[];

    if (hasUserDefinedExample) {
        finalExamples = examplesWithRequestData.filter(({ example }) => isUserDefinedExample(example));
    } else {
        finalExamples = examplesWithRequestData;
    }

    return {
        filteredExamples: finalExamples.map(({ example }) => example),
        indexMapping: finalExamples.map(({ originalIndex }) => originalIndex)
    };
}
