import type { ExampleEndpointCall } from "@fern-api/fdr-sdk/api-definition";
import { compareByRequestData, hasRequestSideData } from "@fern-docs/components/api-reference/examples/example-groups";

/**
 * Check if an example name indicates it's auto-generated (ends with "_example")
 */
function isAutoGeneratedName(name: string | null | undefined): boolean {
    return name?.endsWith("_example") ?? false;
}

/**
 * Check if an example is user-defined (has a name that's not auto-generated)
 */
function isUserDefinedExample(example: ExampleEndpointCall): boolean {
    const name = example.name;
    return name != null && !isAutoGeneratedName(name);
}

/**
 * Filter examples for the API explorer to show examples with request-side data OR user-defined examples.
 * User-defined examples (with explicit names) are always shown, even without request-side data,
 * to support use cases like "Default - No Filtering" examples.
 * When user-defined examples exist, auto-generated and unnamed examples are filtered out.
 *
 * @param examples - The examples to filter
 * @returns Object containing filtered examples and a mapping from filtered index to original index
 */
export function filterExamplesForExplorer(examples: ExampleEndpointCall[] | undefined): {
    filteredExamples: ExampleEndpointCall[];
    indexMapping: number[];
} {
    if (!examples || examples.length === 0) {
        return { filteredExamples: [], indexMapping: [] };
    }

    const relevantExamples = examples
        .map((example, index) => ({ example, originalIndex: index }))
        .filter(({ example }) => hasRequestSideData(example) || isUserDefinedExample(example));

    if (relevantExamples.length === 0) {
        return { filteredExamples: [], indexMapping: [] };
    }

    const hasUserDefinedExampleInRelevant = relevantExamples.some(({ example }) => isUserDefinedExample(example));

    let finalExamples: { example: ExampleEndpointCall; originalIndex: number }[];

    if (hasUserDefinedExampleInRelevant) {
        finalExamples = relevantExamples.filter(({ example }) => isUserDefinedExample(example));
    } else {
        finalExamples = relevantExamples;
    }

    // Sort examples so that those with request data come first, and those without come last
    // Exception: if the name starts with "Default" (case-insensitive, trimmed), preserve original order
    finalExamples.sort((a, b) =>
        compareByRequestData(
            hasRequestSideData(a.example),
            hasRequestSideData(b.example),
            a.example.name,
            b.example.name
        )
    );

    return {
        filteredExamples: finalExamples.map(({ example }) => example),
        indexMapping: finalExamples.map(({ originalIndex }) => originalIndex)
    };
}
