// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export type ApiPackageChild =
    | FdrLambda.navigation.v1.ApiPackageNode
    | FdrLambda.navigation.v1.EndpointNode
    | FdrLambda.navigation.v1.EndpointPairNode
    | FdrLambda.navigation.v1.WebSocketNode
    | FdrLambda.navigation.v1.WebhookNode
    | FdrLambda.navigation.v1.GrpcNode
    | FdrLambda.navigation.v1.PageNode
    | FdrLambda.navigation.v1.LinkNode;
