/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ApiPackageNode
    extends FdrLambda.navigation.v1.WithNodeMetadata,
        FdrLambda.navigation.v1.WithOverviewPage,
        FdrLambda.navigation.v1.WithApiDefinitionId,
        FdrLambda.navigation.v1.WithRedirect {
    type: "apiPackage";
    children: FdrLambda.navigation.v1.ApiPackageChild[];
    /** Settings for the api playground that is applied only to descendants of this api package. */
    playground?: FdrLambda.navigation.v1.PlaygroundSettings;
}
