// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface ApiReferenceNode
    extends FdrLambda.navigation.v1.WithNodeMetadata,
        FdrLambda.navigation.v1.WithOverviewPage,
        FdrLambda.navigation.v1.WithApiDefinitionId,
        FdrLambda.navigation.v1.WithRedirect {
    type: "apiReference";
    /** If true, long-scrolling will be disabled. */
    paginated: boolean | undefined;
    showErrors: boolean | undefined;
    hideTitle: boolean | undefined;
    children: FdrLambda.navigation.v1.ApiPackageChild[];
    changelog: FdrLambda.navigation.v1.ChangelogNode | undefined;
    /** Settings for the api playground that affects all endpoints. */
    playground: FdrLambda.navigation.v1.PlaygroundSettings | undefined;
    /** URL to a Postman collection for this API reference. */
    postmanCollectionUrl: string | undefined;
}
