/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ChangelogMonthNode extends FdrLambda.navigation.v1.WithNodeMetadata {
    type: "changelogMonth";
    month: number;
    children: FdrLambda.navigation.v1.ChangelogEntryNode[];
}
