/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ChangelogNode
    extends FdrLambda.navigation.v1.WithNodeMetadata, FdrLambda.navigation.v1.WithOverviewPage {
    type: "changelog";
    children: FdrLambda.navigation.v1.ChangelogYearNode[];
}
