/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ChangelogYearNode extends FdrLambda.navigation.v1.WithNodeMetadata {
    type: "changelogYear";
    year: number;
    children: FdrLambda.navigation.v1.ChangelogMonthNode[];
}
