// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface EndpointNode
    extends FdrLambda.navigation.v1.WithNodeMetadata,
        FdrLambda.navigation.v1.WithApiDefinitionId {
    type: "endpoint";
    method: FdrLambda.HttpMethod;
    endpointId: FdrLambda.EndpointId;
    isResponseStream: boolean | undefined;
    /** Settings for the api playground that affect this endpoint specifically. */
    playground: FdrLambda.navigation.v1.PlaygroundSettings | undefined;
}
