/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface EndpointPairNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "endpointPair";
    stream: FdrLambda.navigation.v1.EndpointNode;
    nonStream: FdrLambda.navigation.v1.EndpointNode;
}
