/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ExternalProductNode
    extends FdrLambda.navigation.v1.WithNodeId, FdrLambda.navigation.v1.WithPermissions {
    type: "productLink";
    default: boolean;
    productId: FdrLambda.navigation.v1.ProductId;
    /** The title that will be displayed in the sidebar for this external product */
    title: string;
    /** External URL that this product links to */
    href: FdrLambda.Url;
    /** Target attribute for the link (e.g., blank to open in new tab) */
    target: FdrLambda.LinkTarget | undefined;
    /** Couple words for what the product is */
    subtitle: string;
    icon: string | undefined;
    /** A URL to an image that will be displayed in the sidebar. Takes precedence over `icon` if both are provided. */
    image: FdrLambda.FileId | undefined;
    /** If true, this product will not be displayed in the product switcher */
    hidden: boolean | undefined;
    /** If true, this product is only visible to authenticated users */
    authed: boolean | undefined;
}
