// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface GraphQlNode
    extends FdrLambda.navigation.v1.WithNodeMetadata,
        FdrLambda.navigation.v1.WithApiDefinitionId {
    type: "graphql";
    operationType: FdrLambda.navigation.v1.GraphQlOperationType;
    graphqlOperationId: FdrLambda.GraphQlOperationId;
    playground: FdrLambda.navigation.v1.PlaygroundSettings | undefined;
}
