/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface LinkNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "link";
    title: string;
    icon: string | undefined;
    url: FdrLambda.Url;
    target: FdrLambda.LinkTarget | undefined;
}
