/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../index.js";

export type NavigationChild =
    | FdrLambda.navigation.v1.ApiReferenceNode
    | FdrLambda.navigation.v1.SectionNode
    | FdrLambda.navigation.v1.PageNode
    | FdrLambda.navigation.v1.LinkNode
    | FdrLambda.navigation.v1.ChangelogNode;
