/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../index.js";

export interface PageNode extends FdrLambda.navigation.v1.WithNodeMetadata, FdrLambda.navigation.v1.WithPage {
    type: "page";
    availability?: FdrLambda.navigation.v1.NavigationV1Availability;
}
