// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface PlaygroundSettings {
    /**
     * A list of environment IDs that are allowed to be used in the playground.
     * If not provided, all environments are allowed. And if the provided list is empty, the playground should be disabled.
     */
    environments: FdrLambda.EnvironmentId[] | undefined;
    button: FdrLambda.navigation.v1.PlaygroundButtonSettings | undefined;
    "limit-websocket-messages-per-connection": number | undefined;
    /** If true, the endpoint will be hidden from the playground UI. */
    hidden: boolean | undefined;
}
