/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ProductGroupNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "productgroup";
    landingPage: FdrLambda.navigation.v1.LandingPageNode | undefined;
    /** The individual products being documented */
    children: FdrLambda.navigation.v1.ProductNode[];
}
