/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface ProductNode extends FdrLambda.navigation.v1.WithNodeMetadata, FdrLambda.navigation.v1.WithRedirect {
    type: "product";
    default: boolean;
    productId: FdrLambda.navigation.v1.ProductId;
    child: FdrLambda.navigation.v1.ProductChild;
    /** Couple words for what the product is */
    subtitle: string;
    /** A URL to an image that will be displayed in the sidebar. Takes precedence over `icon` if both are provided. */
    image?: FdrLambda.FileId;
}
