// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export type ProductId = string & {
    navigation_v1_ProductId: void;
};

export function ProductId(value: string): FdrLambda.navigation.v1.ProductId {
    return value as unknown as FdrLambda.navigation.v1.ProductId;
}
