// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface RootNode extends FdrLambda.navigation.v1.WithNodeMetadata, FdrLambda.navigation.v1.WithRedirect {
    type: "root";
    version: "v1";
    child: FdrLambda.navigation.v1.RootChild;
    roles: FdrLambda.RoleId[] | undefined;
}
