// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface SectionNode
    extends FdrLambda.navigation.v1.WithNodeMetadata,
        FdrLambda.navigation.v1.WithOverviewPage,
        FdrLambda.navigation.v1.WithRedirect {
    type: "section";
    collapsed: boolean | undefined;
    children: FdrLambda.navigation.v1.NavigationChild[];
    availability: FdrLambda.navigation.v1.NavigationV1Availability | undefined;
}
