/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../index.js";

export interface SidebarGroupNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "sidebarGroup";
    children: FdrLambda.navigation.v1.NavigationChild[];
}
