// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface SidebarRootNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "sidebarRoot";
    children: FdrLambda.navigation.v1.SidebarRootChild[];
}
