/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The full url pathname of the node, excluding leading or trailing slashes.
 * e.g. `getting-started` or `api-reference/overview`, but not `/getting-started` or `/api-reference/overview` or `/getting-started/`
 */
export type Slug = string;
