// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export type TabChild =
    | FdrLambda.navigation.v1.TabNode
    | FdrLambda.navigation.v1.LinkNode
    | FdrLambda.navigation.v1.ChangelogNode;
