/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../index.js";

export interface TabNode extends FdrLambda.navigation.v1.WithNodeMetadata, FdrLambda.navigation.v1.WithRedirect {
    type: "tab";
    child: FdrLambda.navigation.v1.SidebarRootNode;
}
