// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface UnversionedNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "unversioned";
    child: FdrLambda.navigation.v1.VersionChild;
    landingPage: FdrLambda.navigation.v1.LandingPageNode | undefined;
}
