/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface VariantedNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "varianted";
    children: FdrLambda.navigation.v1.VariantNode[];
}
