/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export type VariantId = string & {
    navigation_v1_VariantId: void;
};

export function VariantId(value: string): FdrLambda.navigation.v1.VariantId {
    return value as unknown as FdrLambda.navigation.v1.VariantId;
}
