// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface VariantNode extends FdrLambda.navigation.v1.WithNodeMetadata, FdrLambda.navigation.v1.WithRedirect {
    type: "variant";
    default: boolean;
    variantId: FdrLambda.navigation.v1.VariantId;
    /** Couple words for what the variant is */
    subtitle: string | undefined;
    /** A URL to an image that will be displayed. Takes precedence over `icon` if both are provided. */
    image: FdrLambda.FileId | undefined;
    /** The navigation items that belong to this variant */
    children: FdrLambda.navigation.v1.VariantChild[];
}
