/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface VersionedNode extends FdrLambda.navigation.v1.WithNodeId {
    type: "versioned";
    children: FdrLambda.navigation.v1.VersionNode[];
}
