/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../index.js";

export type VersionChild = FdrLambda.navigation.v1.TabbedNode | FdrLambda.navigation.v1.SidebarRootNode;
