/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface WithPage {
    pageId: FdrLambda.PageId;
    noindex?: boolean;
}
