/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface WithRedirect {
    pointsTo?: FdrLambda.navigation.v1.Slug;
}
