/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface WithNodeMetadata
    extends
        FdrLambda.navigation.v1.WithNodeId,
        FdrLambda.navigation.v1.WithPermissions,
        FdrLambda.navigation.latest.WithFeatureFlags {
    title: string;
    slug: FdrLambda.navigation.v1.Slug;
    icon: string | undefined;
    hidden: boolean | undefined;
    authed: boolean | undefined;
}
