// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface WithApiDefinitionId {
    apiDefinitionId: FdrLambda.ApiDefinitionId;
    availability: FdrLambda.navigation.v1.NavigationV1Availability | undefined;
}
