/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../index.js";

export interface WithNodeId {
    /** A unique, stable identifier for this node. */
    id: FdrLambda.navigation.v1.NodeId;
}
