/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         context: ["context", "context"],
 *         document: "document"
 *     }
 */
export interface UpdateGuidanceRequest {
    /** The context of the document, as a list of strings, that will be indexed. */
    context: string[];
    /** The content of the document that will be returned in the tool response. If not provided, the document will be removed from the index. */
    document: string;
}
