// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import * as FdrLambda from "../../../../../../../index.js";

export declare namespace WriteClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WriteClient {
    protected readonly _options: WriteClient.Options;

    constructor(options: WriteClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Delete a preview docs site. Only preview sites can be deleted through this endpoint.
     *
     * @param {FdrLambda.docs.v2.write.DeleteDocsSiteRequest} request
     * @param {WriteClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.docs.v2.write.deleteDocsSite({
     *         url: FdrLambda.Url("url")
     *     })
     */
    public deleteDocsSite(
        request: FdrLambda.docs.v2.write.DeleteDocsSiteRequest,
        requestOptions?: WriteClient.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<void, FdrLambda.docs.v2.write.deleteDocsSite.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDocsSite(request, requestOptions));
    }

    private async __deleteDocsSite(
        request: FdrLambda.docs.v2.write.DeleteDocsSiteRequest,
        requestOptions?: WriteClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<void, FdrLambda.docs.v2.write.deleteDocsSite.Error>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FdrLambdaEnvironment.Prod,
                "/v2/registry/docs/delete",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs:
                requestOptions?.timeoutInSeconds != null
                    ? requestOptions.timeoutInSeconds * 1000
                    : this._options?.timeoutInSeconds != null
                      ? this._options?.timeoutInSeconds * 1000
                      : undefined,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: undefined,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as FdrLambda.docs.v2.write.deleteDocsSite.Error)?.error) {
                case "DocsNotFoundError":
                case "UnauthorizedError":
                case "CannotDeleteNonPreviewSiteError":
                    return {
                        data: {
                            ok: false,
                            error: _response.error.body as FdrLambda.docs.v2.write.deleteDocsSite.Error,
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: FdrLambda.docs.v2.write.deleteDocsSite.Error._unknown(_response.error),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
