/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../environments.js";
import * as core from "../../../../../../../../core/index.js";
import * as FdrLambda from "../../../../../../../index.js";
import urlJoin from "url-join";

export declare namespace Write {
    export interface Options {
        environment?: core.Supplier<environments.FdrLambdaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Write {
    constructor(protected readonly _options: Write.Options) {}

    /**
     * Delete a docs site and all associated data including S3 assets
     *
     * @param {FdrLambda.docs.v2.write.DeleteDocsSiteRequest} request
     * @param {Write.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.docs.v2.write.deleteDocsSite({
     *         url: FdrLambda.Url("url")
     *     })
     */
    public deleteDocsSite(
        request: FdrLambda.docs.v2.write.DeleteDocsSiteRequest,
        requestOptions?: Write.RequestOptions,
    ): core.HttpResponsePromise<core.APIResponse<void, FdrLambda.docs.v2.write.deleteDocsSite.Error>> {
        return core.HttpResponsePromise.fromPromise(this.__deleteDocsSite(request, requestOptions));
    }

    private async __deleteDocsSite(
        request: FdrLambda.docs.v2.write.DeleteDocsSiteRequest,
        requestOptions?: Write.RequestOptions,
    ): Promise<core.WithRawResponse<core.APIResponse<void, FdrLambda.docs.v2.write.deleteDocsSite.Error>>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FdrLambdaEnvironment.Prod,
                "/v2/registry/docs/delete",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : undefined,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: {
                    ok: true,
                    body: undefined,
                    headers: _response.headers,
                    rawResponse: _response.rawResponse,
                },
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch ((_response.error.body as FdrLambda.docs.v2.write.deleteDocsSite.Error)?.error) {
                case "DocsNotFoundError":
                case "UnauthorizedError":
                    return {
                        data: {
                            ok: false,
                            error: _response.error.body as FdrLambda.docs.v2.write.deleteDocsSite.Error,
                            rawResponse: _response.rawResponse,
                        },
                        rawResponse: _response.rawResponse,
                    };
            }
        }

        return {
            data: {
                ok: false,
                error: FdrLambda.docs.v2.write.deleteDocsSite.Error._unknown(_response.error),
                rawResponse: _response.rawResponse,
            },
            rawResponse: _response.rawResponse,
        };
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
