// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../../../../core/index.js";
import type * as FdrLambda from "../../../../../../../index.js";

export type Error =
    | FdrLambda.docs.v2.write.deleteDocsSite.Error.DocsNotFoundError
    | FdrLambda.docs.v2.write.deleteDocsSite.Error.UnauthorizedError
    | FdrLambda.docs.v2.write.deleteDocsSite.Error.CannotDeleteNonPreviewSiteError
    | FdrLambda.docs.v2.write.deleteDocsSite.Error._Unknown;

export namespace Error {
    export interface DocsNotFoundError {
        error: "DocsNotFoundError";
    }

    export interface UnauthorizedError {
        error: "UnauthorizedError";
        content: string;
    }

    export interface CannotDeleteNonPreviewSiteError {
        error: "CannotDeleteNonPreviewSiteError";
    }

    export interface _Unknown {
        error: void;
        content: core.Fetcher.Error;
    }

    export interface _Visitor<_Result> {
        docsNotFoundError: () => _Result;
        unauthorizedError: (value: string) => _Result;
        cannotDeleteNonPreviewSiteError: () => _Result;
        _other: (value: core.Fetcher.Error) => _Result;
    }
}

export const Error = {
    docsNotFoundError: (): FdrLambda.docs.v2.write.deleteDocsSite.Error.DocsNotFoundError => {
        return {
            error: "DocsNotFoundError",
        };
    },

    unauthorizedError: (value: string): FdrLambda.docs.v2.write.deleteDocsSite.Error.UnauthorizedError => {
        return {
            content: value,
            error: "UnauthorizedError",
        };
    },

    cannotDeleteNonPreviewSiteError:
        (): FdrLambda.docs.v2.write.deleteDocsSite.Error.CannotDeleteNonPreviewSiteError => {
            return {
                error: "CannotDeleteNonPreviewSiteError",
            };
        },

    _unknown: (fetcherError: core.Fetcher.Error): FdrLambda.docs.v2.write.deleteDocsSite.Error._Unknown => {
        return {
            error: undefined,
            content: fetcherError,
        };
    },

    _visit: <_Result>(
        value: FdrLambda.docs.v2.write.deleteDocsSite.Error,
        visitor: FdrLambda.docs.v2.write.deleteDocsSite.Error._Visitor<_Result>,
    ): _Result => {
        switch (value.error) {
            case "DocsNotFoundError":
                return visitor.docsNotFoundError();
            case "UnauthorizedError":
                return visitor.unauthorizedError(value.content);
            case "CannotDeleteNonPreviewSiteError":
                return visitor.cannotDeleteNonPreviewSiteError();
            default:
                return visitor._other(value.content);
        }
    },
} as const;
