/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToggleAskAiRequestLocationsItem = "docs" | "slack" | "discord";
export const ToggleAskAiRequestLocationsItem = {
    Docs: "docs",
    Slack: "slack",
    Discord: "discord",
} as const;
