// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

/**
 * An example of a GraphQL operation call
 */
export interface GraphQlExample extends FdrLambda.api.v1.WithDescription {
    name: string | undefined;
    query: string;
    variables: Record<string, unknown> | undefined;
    response: unknown | undefined;
}
