// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

/**
 * A GraphQL operation (query, mutation, or subscription)
 */
export interface GraphQlOperation extends FdrLambda.api.v1.WithDescription, FdrLambda.api.v1.WithAvailability {
    id: FdrLambda.GraphQlOperationId;
    operationType: FdrLambda.api.v1.read.GraphQlOperationType;
    name: string;
    displayName: string | undefined;
    arguments: FdrLambda.api.v1.read.GraphQlArgument[] | undefined;
    returnType: FdrLambda.api.v1.read.TypeReference;
    examples: FdrLambda.api.v1.read.GraphQlExample[] | undefined;
    snippets: Record<FdrLambda.api.latest.Language, FdrLambda.api.latest.CodeSnippet[]> | undefined;
}
