/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface DiscriminatedUnionType {
    discriminant: string;
    variants: FdrLambda.api.v1.read.DiscriminatedUnionVariant[];
}
