/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface EnumValue extends FdrLambda.api.v1.WithDescription, FdrLambda.api.v1.WithAvailability {
    value: string;
}
