/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export type FormDataProperty =
    | FdrLambda.api.v1.read.FormDataProperty.File_
    | FdrLambda.api.v1.read.FormDataProperty.BodyProperty;

export namespace FormDataProperty {
    export interface File_ {
        type: "file";
        value: FdrLambda.api.v1.read.FormDataFileProperty;
    }

    export interface BodyProperty extends FdrLambda.api.v1.read.FormDataBodyProperty {
        type: "bodyProperty";
    }
}
