// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export type LiteralType =
    | FdrLambda.api.v1.read.LiteralType.BooleanLiteral
    | FdrLambda.api.v1.read.LiteralType.StringLiteral;

export namespace LiteralType {
    export interface BooleanLiteral {
        type: "booleanLiteral";
        value: boolean;
    }

    export interface StringLiteral {
        type: "stringLiteral";
        value: string;
    }
}
