// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface MapType {
    keyType: FdrLambda.api.v1.read.TypeReference;
    valueType: FdrLambda.api.v1.read.TypeReference;
    minProperties: number | undefined;
    maxProperties: number | undefined;
}
