/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface MapType {
    keyType: FdrLambda.api.v1.read.TypeReference;
    valueType: FdrLambda.api.v1.read.TypeReference;
}
