/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface ObjectType {
    extends: FdrLambda.TypeId[];
    properties: FdrLambda.api.v1.read.ObjectProperty[];
    extraProperties?: FdrLambda.api.v1.read.TypeReference;
}
