// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export type PrimitiveType =
    | FdrLambda.api.v1.read.PrimitiveType.Integer
    | FdrLambda.api.v1.read.PrimitiveType.Double
    | FdrLambda.api.v1.read.PrimitiveType.String
    | FdrLambda.api.v1.read.PrimitiveType.Long
    | FdrLambda.api.v1.read.PrimitiveType.Boolean
    | FdrLambda.api.v1.read.PrimitiveType.Datetime
    | FdrLambda.api.v1.read.PrimitiveType.Uuid
    | FdrLambda.api.v1.read.PrimitiveType.Base64
    | FdrLambda.api.v1.read.PrimitiveType.Date_
    | FdrLambda.api.v1.read.PrimitiveType.BigInteger
    | FdrLambda.api.v1.read.PrimitiveType.Uint
    | FdrLambda.api.v1.read.PrimitiveType.Uint64
    | FdrLambda.api.v1.read.PrimitiveType.Scalar;

export namespace PrimitiveType {
    export interface Integer extends FdrLambda.api.v1.read.IntegerType {
        type: "integer";
    }

    export interface Double extends FdrLambda.api.v1.read.DoubleType {
        type: "double";
    }

    export interface String extends FdrLambda.api.v1.read.StringType {
        type: "string";
    }

    export interface Long extends FdrLambda.api.v1.read.LongType {
        type: "long";
    }

    export interface Boolean extends FdrLambda.api.v1.read.BooleanType {
        type: "boolean";
    }

    export interface Datetime extends FdrLambda.api.v1.read.DatetimeType {
        type: "datetime";
    }

    export interface Uuid extends FdrLambda.api.v1.read.UuidType {
        type: "uuid";
    }

    export interface Base64 extends FdrLambda.api.v1.read.Base64Type {
        type: "base64";
    }

    export interface Date_ extends FdrLambda.api.v1.read.DateType {
        type: "date";
    }

    export interface BigInteger extends FdrLambda.api.v1.read.BigIntegerType {
        type: "bigInteger";
    }

    export interface Uint extends FdrLambda.api.v1.read.UintType {
        type: "uint";
    }

    export interface Uint64 extends FdrLambda.api.v1.read.Uint64Type {
        type: "uint64";
    }

    export interface Scalar extends FdrLambda.api.v1.read.ScalarType {
        type: "scalar";
    }
}
