/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface SetType {
    itemType: FdrLambda.api.v1.read.TypeReference;
}
