// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface SetType {
    itemType: FdrLambda.api.v1.read.TypeReference;
    minItems: number | undefined;
    maxItems: number | undefined;
}
