/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export type TypeReference =
    | FdrLambda.api.v1.read.TypeReference.Id
    | FdrLambda.api.v1.read.TypeReference.Primitive
    | FdrLambda.api.v1.read.TypeReference.Optional
    | FdrLambda.api.v1.read.TypeReference.Nullable
    | FdrLambda.api.v1.read.TypeReference.List
    | FdrLambda.api.v1.read.TypeReference.Set
    | FdrLambda.api.v1.read.TypeReference.Map
    | FdrLambda.api.v1.read.TypeReference.Literal
    | FdrLambda.api.v1.read.TypeReference.Unknown;

export namespace TypeReference {
    export interface Id extends FdrLambda.api.v1.read.TypeReferenceId {
        type: "id";
    }

    export interface Primitive {
        type: "primitive";
        value: FdrLambda.api.v1.read.PrimitiveType;
    }

    export interface Optional extends FdrLambda.api.v1.read.OptionalType {
        type: "optional";
    }

    export interface Nullable extends FdrLambda.api.v1.read.NullableType {
        type: "nullable";
    }

    export interface List extends FdrLambda.api.v1.read.ListType {
        type: "list";
    }

    export interface Set extends FdrLambda.api.v1.read.SetType {
        type: "set";
    }

    export interface Map extends FdrLambda.api.v1.read.MapType {
        type: "map";
    }

    export interface Literal {
        type: "literal";
        value: FdrLambda.api.v1.read.LiteralType;
    }

    export interface Unknown {
        type: "unknown";
    }
}
