// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export type TypeReferenceIdDefault = FdrLambda.api.v1.read.TypeReferenceIdDefault.Enum;

export namespace TypeReferenceIdDefault {
    export interface Enum {
        type: "enum";
        value: string;
    }
}
