/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface TypeReferenceId {
    value: FdrLambda.TypeId;
    default?: FdrLambda.api.v1.read.TypeReferenceIdDefault;
}
