/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface TypeDefinition extends FdrLambda.api.v1.WithDescription, FdrLambda.api.v1.WithAvailability {
    name: string;
    shape: FdrLambda.api.v1.read.TypeShape;
    displayName: string | undefined;
}
