version: "3.8"
services:
  fern-self-hosted-1:
    image: fern-self-hosted:latest
    container_name: fern-self-hosted-multinode-fern-self-hosted-1
    networks:
      - fern-network
    ports:
      - "8080:8080"
      - "8181:8081"
      - "9000:9000"
      - "9001:9001"
      - "5434:5432"
      - "3000:3000"
    volumes:
      - ./fern:/fern
    tmpfs:
      - /data:rw,size=1g,mode=0777
    environment:
      - RUN_MODE=server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5

  fern-self-hosted-2:
    image: fern-self-hosted:latest
    container_name: fern-self-hosted-multinode-fern-self-hosted-2
    networks:
      - fern-network
    ports:
      - "8082:8080"
      - "8182:8081"
      - "9002:9000"
      - "9003:9001"
      - "5435:5432"
      - "3001:3000"
    volumes:
      - ./fern:/fern
    tmpfs:
      - /data:rw,size=1g,mode=0777
    environment:
      - RUN_MODE=server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5

  fern-self-hosted-3:
    image: fern-self-hosted:latest
    container_name: fern-self-hosted-multinode-fern-self-hosted-3
    networks:
      - fern-network
    ports:
      - "8083:8080"
      - "8183:8081"
      - "9004:9000"
      - "9005:9001"
      - "5436:5432"
      - "3002:3000"
    volumes:
      - ./fern:/fern
    tmpfs:
      - /data:rw,size=1g,mode=0777
    environment:
      - RUN_MODE=server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  fern-network:
    external: true
