/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface AnalyzeCommitDiffResponse {
    /** The AI-generated commit message summarizing the changes in the diff */
    message: string;
    /** The recommended semantic version bump: MAJOR for breaking changes, MINOR for new features, PATCH for bug fixes and other changes, NO_CHANGE for empty diffs */
    version_bump: FernAI.VersionBump;
}
