/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

/**
 * Response with content hash entries.
 */
export interface BatchGetContentHashesResponse {
    entries: FernAI.ContentHashEntry[];
    total_count?: number;
    has_more?: boolean;
}
