/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Entry for upserting a content hash (without timestamps).
 */
export interface ContentHashUpsertEntry {
    parent_id: string;
    content_hash: string;
    chunk_count: number;
}
