/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCodeRequest {
    /** The content of the code document that will be returned to Ask Fern during retrieval. */
    document: string;
    /** The textual content that should be vectorized when indexing the code. If not provided, the full document will be vectorized. */
    chunk?: string;
    /** The title of the code document. This will be used with the `url` when Ask Fern cites this code. */
    title?: string;
    /** The url of the code document. This will be used as the source when Ask Fern cites it. */
    url?: string;
    /** The version of the code. This will be compared against when running Ask Fern with version filters. If null, the code will be retrievable by all versions. */
    version?: string;
    /** The product of the code. This will be used to filter code when running Ask Fern with product filters. If null, the code will be retrievable by all products. */
    product?: string;
    /** The keywords of the code. Adding keywords can improve code matching. */
    keywords?: string[];
    /** Whether the code is authed. If true, the code will be retrievable by all users. */
    authed?: boolean;
}
