/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCodeRecordResponse {
    /** The unique identifier of the created code entry */
    code_id: string;
}
