/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

/**
 * Response when creating a new editing session.
 */
export interface CreateEditingSessionResponse {
    editing_session: FernAI.EditingSession;
}
