/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteDocumentRequest {
    /** The unique identifier of the document to delete */
    document_id: string;
}
