/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteWebsiteResponse {
    /** Whether the website was successfully deleted */
    success: boolean;
    /** Number of pages deleted */
    pages_deleted: number;
}
