/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response after deleting content hashes.
 */
export interface DeleteContentHashesResponse {
    deleted_count: number;
}
