/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of an editing session.
 */
export type EditingSessionStatus = "waiting" | "active" | "interrupted" | "completed";
export const EditingSessionStatus = {
    Waiting: "waiting",
    Active: "active",
    Interrupted: "interrupted",
    Completed: "completed",
} as const;
