/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface EditingSession {
    id: string;
    session_id?: string;
    repository: string;
    base_branch: string;
    working_branch: string;
    pr_url?: string;
    status: FernAI.EditingSessionStatus;
    created_at: string;
    updated_at: string;
}
