/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface GetCodeRecordsResponse {
    /** List of code entries for the domain */
    documents: FernAI.Code[];
    /** Pagination information for the code list */
    pagination: FernAI.PaginationResponse;
}
