/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

export interface GetCodeResponse {
    /** The requested code */
    document: FernAI.Code;
}
