/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetConversationResolutionResponse {
    /** Total number of conversations in the period */
    total_conversations: number;
    /** Number of resolved conversations */
    resolved_conversations: number;
    /** Number of unresolved conversations */
    unresolved_conversations: number;
    /** Percentage of conversations resolved (0-100) */
    resolution_rate: number;
}
