/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FernAI from "../index.js";

export interface GetDocumentResponse {
    /** The requested document */
    document: FernAI.Document;
}
