/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FernAI from "../index.js";

export interface GetGuidancesResponse {
    /** List of guidance documents for the domain */
    guidances: FernAI.Guidance[];
    /** Pagination information for the guidance document list */
    pagination: FernAI.PaginationResponse;
}
