/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetSettingsResponse {
    /** Whether Ask AI is enabled */
    ask_ai_enabled: boolean;
    /** Active job ID if reindexing is in progress */
    job_id?: string;
}
