/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetWebsiteStatusResponse {
    job_id: string;
    /** Job status: PENDING, PROCESSING, COMPLETED, or FAILED */
    status: string;
    base_url: string;
    /** Number of pages successfully indexed */
    pages_indexed: number;
    /** Number of pages that failed to index */
    pages_failed: number;
    /** Error message if the job failed */
    error?: string;
}
