/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IndexWebsiteResponse {
    /** ID to track the indexing job status */
    job_id: string;
    /** The base URL being indexed */
    base_url: string;
}
