/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IndexGithubResponse {
    /** Job ID for tracking indexing progress */
    job_id: string;
    /** GitHub repository URLs being indexed */
    repo_urls: string[];
}
