/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FernAI from "../index.js";

export interface InsightWithMetadata {
    insightText: string;
    numberOfQueries: number;
    examples: FernAI.InsightExample[];
}
