/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../index.js";

/**
 * Response when interrupting an editing session.
 */
export interface InterruptEditingSessionResponse {
    editing_session: FernAI.EditingSession;
}
