/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LanguageModel = "claude-4-sonnet" | "command-a-03-2025" | "claude-4.5-haiku" | "claude-4.5-sonnet";
export const LanguageModel = {
    Claude4Sonnet: "claude-4-sonnet",
    CommandA032025: "command-a-03-2025",
    Claude45Haiku: "claude-4.5-haiku",
    Claude45Sonnet: "claude-4.5-sonnet",
} as const;
