/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Reindexing job record model
 */
export interface ReindexingJobRecord {
    domain: string;
    status: string;
    memory_mb: number;
    retry_count: number;
    task_arn?: string;
    sqs_message_id?: string;
    started_at?: string;
    updated_at: string;
    completed_at?: string;
    duration_ms?: number;
    num_inserted?: number;
    error?: string;
    reason?: string;
    task_arns?: string[];
}
