/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SetJobIdResponse {
    /** Whether the job_id was set successfully */
    success: boolean;
    /** Domain for which job_id was set */
    domain?: string;
    /** The job_id that was set */
    job_id?: string;
}
