/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToggleAskAiResponse {
    /** Whether the toggle operation was successful */
    success: boolean;
    /** Job ID for tracking reindex progress (only when enabling Ask AI) */
    job_id?: string;
    /** Current state of Ask AI (true if enabled, false if disabled) */
    ask_ai_enabled: boolean;
}
