/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToggleStatusResponse {
    /** Current job status (running, completed, failed, etc.) */
    status: string;
    /** Current state of Ask AI */
    ask_ai_enabled: boolean;
    /** ISO timestamp of last reindex */
    last_reindex_time?: string;
}
