/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FernAI from "../index.js";

export interface UpdateDocumentResponse {
    /** The updated document */
    document: FernAI.Document;
}
