/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for updating reindexing job status
 */
export interface UpdateReindexingJobStatusResponse {
    success: boolean;
    domain: string;
    status: string;
}
