/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FernAI from "../index.js";

export interface UpdateGuidanceResponse {
    /** The updated guidance document */
    guidance: FernAI.Guidance;
}
