/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VersionBump = "MAJOR" | "MINOR" | "PATCH" | "NO_CHANGE";
export const VersionBump = {
    Major: "MAJOR",
    Minor: "MINOR",
    Patch: "PATCH",
    NoChange: "NO_CHANGE",
} as const;
