/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Website {
    website_id: string;
    domain: string;
    base_url: string;
    page_url: string;
    chunk: string;
    document: string;
    title?: string;
    version?: string;
    product?: string;
    keywords?: string[];
    authed?: boolean;
    created_at: string;
    updated_at: string;
}
