/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../index.js";

export type ApiDefinitionId = string & {
    ApiDefinitionId: void;
};

export function ApiDefinitionId(value: string): FdrLambda.ApiDefinitionId {
    return value as unknown as FdrLambda.ApiDefinitionId;
}
