// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../index.js";

/**
 * Identifier for an API environment (i.e. "Prod", "Staging", "Dev")
 */
export type EnvironmentId = string & {
    EnvironmentId: void;
};

export function EnvironmentId(value: string): FdrLambda.EnvironmentId {
    return value as unknown as FdrLambda.EnvironmentId;
}
