// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../index.js";

export type FileId = string & {
    FileId: void;
};

export function FileId(value: string): FdrLambda.FileId {
    return value as unknown as FdrLambda.FileId;
}
