// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../index.js";

export type JqString = string & {
    JqString: void;
};

export function JqString(value: string): FdrLambda.JqString {
    return value as unknown as FdrLambda.JqString;
}
