/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../index.js";

/**
 * Represents a set of auth schemes that must ALL be satisfied (AND relationship).
 * Used in multiAuth to express OR-of-AND security requirements.
 */
export interface MultipleAuthType {
    /** List of auth scheme IDs that must all be satisfied for this auth option. */
    schemes: FdrLambda.AuthSchemeId[];
}
