/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../index.js";

/**
 * Human readable org id (e.g. fern)
 */
export type OrgId = string & {
    OrgId: void;
};

export function OrgId(value: string): FdrLambda.OrgId {
    return value as unknown as FdrLambda.OrgId;
}
