/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../index.js";

export type Url = string & {
    Url: void;
};

export function Url(value: string): FdrLambda.Url {
    return value as unknown as FdrLambda.Url;
}
