/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../index.js";

export type VersionId = string & {
    VersionId: void;
};

export function VersionId(value: string): FdrLambda.VersionId {
    return value as unknown as FdrLambda.VersionId;
}
