// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../index.js";

export type WebhookId = string & {
    WebhookId: void;
};

export function WebhookId(value: string): FdrLambda.WebhookId {
    return value as unknown as FdrLambda.WebhookId;
}
