// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../index.js";

export type WebSocketId = string & {
    WebSocketId: void;
};

export function WebSocketId(value: string): FdrLambda.WebSocketId {
    return value as unknown as FdrLambda.WebSocketId;
}
