/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface ExampleWebSocketSession extends FdrLambda.api.latest.WithDescription {
    path: string;
    name?: string;
    pathParameters?: Record<FdrLambda.PropertyKey, unknown>;
    queryParameters?: Record<FdrLambda.PropertyKey, unknown>;
    requestHeaders?: Record<FdrLambda.PropertyKey, unknown>;
    messages?: FdrLambda.api.latest.ExampleWebSocketMessage[];
}
