// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface WebSocketMessage extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    type: FdrLambda.api.latest.WebSocketMessageId;
    displayName: string | undefined;
    origin: FdrLambda.api.latest.WebSocketMessageOrigin;
    body: FdrLambda.api.latest.TypeShape;
}
