// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export type WebSocketMessageId = FdrLambda.api.v1.WebSocketMessageId;
