/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface WebSocketChannel
    extends FdrLambda.api.latest.WithDescription,
        FdrLambda.api.latest.WithAvailability,
        FdrLambda.api.latest.WithNamespace {
    id: FdrLambda.WebSocketId;
    displayName?: string;
    operationId?: string;
    path: FdrLambda.api.latest.PathPart[];
    /** The messages that can be sent and received on this channel */
    messages: FdrLambda.api.latest.WebSocketMessage[];
    auth?: FdrLambda.AuthSchemeId[];
    defaultEnvironment?: FdrLambda.EnvironmentId;
    environments?: FdrLambda.api.latest.Environment[];
    pathParameters?: FdrLambda.api.latest.ObjectProperty[];
    queryParameters?: FdrLambda.api.latest.ObjectProperty[];
    requestHeaders?: FdrLambda.api.latest.ObjectProperty[];
    examples?: FdrLambda.api.latest.ExampleWebSocketSession[];
}
