/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export type Protocol =
    | FdrLambda.api.v1.Protocol.Rest
    | FdrLambda.api.v1.Protocol.Openrpc
    | FdrLambda.api.v1.Protocol.Grpc;

export namespace Protocol {
    export interface Rest extends FdrLambda.api.v1.RestProtocol {
        type: "rest";
    }

    export interface Openrpc extends FdrLambda.api.v1.OpenRpcProtocol {
        type: "openrpc";
    }

    export interface Grpc extends FdrLambda.api.v1.GrpcProtocol {
        type: "grpc";
    }
}
