/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export type SubpackageId = string & {
    api_v1_SubpackageId: void;
};

export function SubpackageId(value: string): FdrLambda.api.v1.SubpackageId {
    return value as unknown as FdrLambda.api.v1.SubpackageId;
}
