// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export type WebSocketMessageId = string & {
    api_v1_WebSocketMessageId: void;
};

export function WebSocketMessageId(value: string): FdrLambda.api.v1.WebSocketMessageId {
    return value as unknown as FdrLambda.api.v1.WebSocketMessageId;
}
