/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../index.js";

export interface WithFeatureFlags {
    featureFlags: FdrLambda.navigation.latest.FeatureFlagOptions[] | undefined;
}
