/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../../../errors/index.js";
import * as core from "../../../../../../../../core/index.js";

export class DocsNotFoundError extends errors.FdrLambdaError {
    constructor(rawResponse?: core.RawResponse) {
        super({
            message: "DocsNotFoundError",
            statusCode: 404,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, DocsNotFoundError.prototype);
    }
}
