/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface WebhookDefinition extends FdrLambda.api.v1.WithDescription {
    urlSlug: string;
    migratedFromUrlSlugs?: string[];
    method: FdrLambda.api.v1.WebhookHttpMethod;
    id: FdrLambda.WebhookId;
    name?: string;
    path: string[];
    headers: FdrLambda.api.v1.read.Header[];
    payload: FdrLambda.api.v1.read.WebhookPayload;
    examples: FdrLambda.api.v1.read.ExampleWebhookPayload[];
}
