/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         document: "document",
 *         chunk: undefined,
 *         title: undefined,
 *         url: undefined,
 *         version: undefined,
 *         keywords: undefined,
 *         authed: undefined
 *     }
 */
export interface IndexDocumentRequest {
    /** The content of the document that will be returned in the tool response */
    document: string;
    /** The chunk of the document that will be indexed as a vector. If not provided, the document will be indexed. */
    chunk?: string;
    /** The title of the document */
    title?: string;
    /** The url of the document */
    url?: string;
    /** The version of the document */
    version?: string;
    /** The keywords of the document */
    keywords?: string[];
    /** Whether the document is authed */
    authed?: boolean;
}
