


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;




ALTER SCHEMA "public" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";




DO $$ BEGIN
    CREATE TYPE "public"."oidc_mapping_type" AS ENUM (
        'org_role',
        'resource_role'
    );
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;


ALTER TYPE "public"."oidc_mapping_type" OWNER TO "postgres";


DO $$ BEGIN
    CREATE TYPE "public"."oidc_role" AS ENUM (
        'admin',
        'editor',
        'viewer'
    );
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;


ALTER TYPE "public"."oidc_role" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_oidc_mappings_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
  BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
  END;
  $$;


ALTER FUNCTION "public"."update_oidc_mappings_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_paymentmetadata_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
  BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
  END;
  $$;


ALTER FUNCTION "public"."update_paymentmetadata_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW."updatedAt" = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."AnalyticsRecord" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "start_date" "date",
    "end_date" "date",
    "top_paths" "jsonb",
    "top_countries" "jsonb",
    "top_channels" "jsonb",
    "top_device_types" "jsonb",
    "top_referring_domains" "jsonb",
    "top_llm_txts" "jsonb",
    "top_api_explorer" "jsonb",
    "top_llm_bot_traffic" "jsonb",
    "docs_site" "text",
    "docs_org" "text",
    "view_chart" "jsonb",
    "visitor_chart" "jsonb",
    "total_views" bigint,
    "total_visitors" bigint,
    "pages_404" "jsonb"
);


ALTER TABLE "public"."AnalyticsRecord" OWNER TO "postgres";


DO $$ BEGIN
    ALTER TABLE "public"."AnalyticsRecord" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."AnalyticsRecord_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



CREATE TABLE IF NOT EXISTS "public"."CustomDomainVerification" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "domain" "text" NOT NULL,
    "docsUrl" "text" NOT NULL,
    "orgId" "text" NOT NULL,
    "verificationValue" "text" NOT NULL,
    "status" "text" DEFAULT 'PENDING'::"text" NOT NULL,
    "vercelDomainId" "text",
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "verifiedAt" timestamp with time zone,
    "expiresAt" timestamp with time zone NOT NULL,
    "ownershipVerified" boolean DEFAULT false NOT NULL,
    "dnsConfigured" boolean DEFAULT false NOT NULL,
    "prUrl" "text",
    CONSTRAINT "CustomDomainVerification_status_check" CHECK (("status" = ANY (ARRAY['PENDING'::"text", 'VERIFIED'::"text", 'FAILED'::"text", 'EXPIRED'::"text"])))
);


ALTER TABLE "public"."CustomDomainVerification" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."DocsInstance" (
    "id" "text" NOT NULL,
    "orgId" "text" NOT NULL,
    "url" "text" NOT NULL,
    "createdAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp(3) without time zone
);


ALTER TABLE "public"."DocsInstance" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Feedback" (
    "id" integer NOT NULL,
    "votedAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "submittedAt" timestamp(3) without time zone,
    "pageUrl" "text" NOT NULL,
    "sessionId" "text",
    "eventId" "text",
    "location" "text",
    "deviceType" "text",
    "browser" "text",
    "isHelpful" boolean NOT NULL,
    "selection" "text",
    "comment" "text",
    "email" "text",
    "docsInstanceId" "text"
);


ALTER TABLE "public"."Feedback" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."Feedback_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."Feedback_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."Feedback_id_seq" OWNED BY "public"."Feedback"."id";



CREATE TABLE IF NOT EXISTS "public"."OidcGroupMappings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "text" NOT NULL,
    "connection_name" "text" NOT NULL,
    "group_id" "text" NOT NULL,
    "mapping_type" "public"."oidc_mapping_type" NOT NULL,
    "role" "public"."oidc_role" NOT NULL,
    "resource_type" "text",
    "resource_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" "text",
    CONSTRAINT "valid_resource_mapping" CHECK (((("mapping_type" = 'org_role'::"public"."oidc_mapping_type") AND ("resource_type" IS NULL) AND ("resource_id" IS NULL)) OR (("mapping_type" = 'resource_role'::"public"."oidc_mapping_type") AND ("resource_type" IS NOT NULL) AND ("resource_id" IS NOT NULL))))
);


ALTER TABLE "public"."OidcGroupMappings" OWNER TO "postgres";


COMMENT ON TABLE "public"."OidcGroupMappings" IS 'Maps OIDC IdP groups to Fern roles for automatic permission assignment';



COMMENT ON COLUMN "public"."OidcGroupMappings"."org_id" IS 'Fern organization ID';



COMMENT ON COLUMN "public"."OidcGroupMappings"."connection_name" IS 'Auth0 connection name (e.g., oidcnvidia)';



COMMENT ON COLUMN "public"."OidcGroupMappings"."group_id" IS 'IdP group identifier from oidc-groups claim';



COMMENT ON COLUMN "public"."OidcGroupMappings"."mapping_type" IS 'org_role for org-wide permissions, resource_role for resource-specific';



COMMENT ON COLUMN "public"."OidcGroupMappings"."role" IS 'Role to assign: admin, editor, or viewer';



COMMENT ON COLUMN "public"."OidcGroupMappings"."resource_type" IS 'Resource type (e.g., docs) - required for resource_role mappings';



COMMENT ON COLUMN "public"."OidcGroupMappings"."resource_id" IS 'Resource ID (e.g., site-abc) - required for resource_role mappings';



COMMENT ON COLUMN "public"."OidcGroupMappings"."created_by" IS 'User ID who created this mapping';



CREATE TABLE IF NOT EXISTS "public"."Organization" (
    "orgId" "text" NOT NULL
);


ALTER TABLE "public"."Organization" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."RolePermissions" (
    "id" bigint NOT NULL,
    "role" "text" NOT NULL,
    "permission" "text" NOT NULL
);


ALTER TABLE "public"."RolePermissions" OWNER TO "postgres";


COMMENT ON TABLE "public"."RolePermissions" IS 'Roles and their related permissions';



DO $$ BEGIN
    ALTER TABLE "public"."RolePermissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."RolePermissions_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



CREATE TABLE IF NOT EXISTS "public"."User" (
    "userId" "text" NOT NULL,
    "email" "text" NOT NULL,
    "githubUsername" "text",
    "createdAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "isAdmin" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."User" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."UserOrganization" (
    "userId" "text" NOT NULL,
    "orgId" "text" NOT NULL
);


ALTER TABLE "public"."UserOrganization" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."UserRolesPerResource" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "text" NOT NULL,
    "resource_type" "text" NOT NULL,
    "resource_id" "text" NOT NULL,
    "role" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "org_id" "text" NOT NULL
);


ALTER TABLE "public"."UserRolesPerResource" OWNER TO "postgres";


COMMENT ON TABLE "public"."UserRolesPerResource" IS 'relation between a user and resources';



CREATE TABLE IF NOT EXISTS "public"."_prisma_migrations" (
    "id" character varying(36) NOT NULL,
    "checksum" character varying(64) NOT NULL,
    "finished_at" timestamp with time zone,
    "migration_name" character varying(255) NOT NULL,
    "logs" "text",
    "rolled_back_at" timestamp with time zone,
    "started_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "applied_steps_count" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."_prisma_migrations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."billing_product" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "sku" "text" NOT NULL,
    "kind" "text" NOT NULL,
    "display_name" "text" NOT NULL,
    "tier" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "billing_product_kind_check" CHECK (("kind" = ANY (ARRAY['plan'::"text", 'addon'::"text"]))),
    CONSTRAINT "billing_product_tier_check" CHECK (("tier" = ANY (ARRAY['free'::"text", 'paid'::"text", 'enterprise'::"text"])))
);


ALTER TABLE "public"."billing_product" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."deprecated_PaymentMetadata" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "text" NOT NULL,
    "stripe_customer_id" "text" NOT NULL,
    "subscription_id" "text",
    "subscription_status" "text",
    "subscription_start_date" timestamp with time zone,
    "subscription_end_date" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product_ids" "text"[],
    "pricing_tier" "text" DEFAULT 'free'::"text" NOT NULL,
    CONSTRAINT "valid_pricing_tier" CHECK (("pricing_tier" = ANY (ARRAY['free'::"text", 'basic'::"text", 'pro'::"text", 'enterprise'::"text"])))
);


ALTER TABLE "public"."deprecated_PaymentMetadata" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."deprecated_payment_metadata" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "text" NOT NULL,
    "stripe_customer_id" "text" NOT NULL,
    "subscription_id" "text",
    "subscription_status" "text",
    "subscription_start_date" timestamp with time zone,
    "subscription_end_date" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."deprecated_payment_metadata" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."deprecated_product_ownership" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "text" NOT NULL,
    "product_registry_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "text" DEFAULT 'active'::"text" NOT NULL,
    CONSTRAINT "product_ownership_status_check" CHECK (("status" = ANY (ARRAY['active'::"text", 'inactive'::"text"])))
);


ALTER TABLE "public"."deprecated_product_ownership" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."deprecated_product_registry" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "display_name" "text" NOT NULL,
    "tier" "text",
    "type" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "product_registry_tier_check" CHECK (("tier" = ANY (ARRAY['free'::"text", 'basic'::"text", 'pro'::"text", 'enterprise'::"text"]))),
    CONSTRAINT "product_registry_type_check" CHECK (("type" = ANY (ARRAY['plan'::"text", 'add_on'::"text"])))
);


ALTER TABLE "public"."deprecated_product_registry" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."org_subscription" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "text" NOT NULL,
    "stripe_subscription_id" "text" NOT NULL,
    "status" "text" NOT NULL,
    "current_period_start" timestamp with time zone,
    "current_period_end" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."org_subscription" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."org_subscription_item" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_subscription_id" "uuid" NOT NULL,
    "org_billing_product" "uuid" NOT NULL,
    "stripe_subscription_item_id" "text" NOT NULL,
    "quantity" integer DEFAULT 1 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."org_subscription_item" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."org_active_products" AS
 SELECT "os"."org_id",
    "bp"."id" AS "billing_product_id",
    "bp"."sku",
    "bp"."kind",
    "bp"."tier",
    "osi"."quantity" AS "qty",
    "os"."id" AS "subscription_id",
    "os"."status"
   FROM (("public"."org_subscription" "os"
     JOIN "public"."org_subscription_item" "osi" ON (("osi"."org_subscription_id" = "os"."id")))
     JOIN "public"."billing_product" "bp" ON (("bp"."id" = "osi"."org_billing_product")));


ALTER TABLE "public"."org_active_products" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."org_billing_account" (
    "org_id" "text" NOT NULL,
    "stripe_customer_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."org_billing_account" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."org_entitlement_usage" (
    "org_id" "text" NOT NULL,
    "key" "text" NOT NULL,
    "usage_count" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."org_entitlement_usage" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."postman_app_installations" (
    "team_id" "text" NOT NULL,
    "shared_secret" "text" NOT NULL,
    "app_installation_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."postman_app_installations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."postman_collection_openapi_specs" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "team_id" "text" NOT NULL,
    "user_id" "text" NOT NULL,
    "collection_id" "text" NOT NULL,
    "openapi_spec" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."postman_collection_openapi_specs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stripe_event_inbox" (
    "stripe_event_id" "text" NOT NULL,
    "type" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "payload" "jsonb" NOT NULL,
    "processed_at" timestamp with time zone,
    "processing_error" "text"
);


ALTER TABLE "public"."stripe_event_inbox" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Feedback" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."Feedback_id_seq"'::"regclass");



DO $$ BEGIN
    ALTER TABLE ONLY "public"."AnalyticsRecord"
        ADD CONSTRAINT "AnalyticsRecord_docs_site_start_date_end_date_unique" UNIQUE ("docs_site", "start_date", "end_date");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."AnalyticsRecord"
        ADD CONSTRAINT "AnalyticsRecord_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."CustomDomainVerification"
        ADD CONSTRAINT "CustomDomainVerification_docsUrl_key" UNIQUE ("docsUrl");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."CustomDomainVerification"
        ADD CONSTRAINT "CustomDomainVerification_domain_key" UNIQUE ("domain");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."CustomDomainVerification"
        ADD CONSTRAINT "CustomDomainVerification_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."DocsInstance"
        ADD CONSTRAINT "DocsInstance_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."Feedback"
        ADD CONSTRAINT "Feedback_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."OidcGroupMappings"
        ADD CONSTRAINT "OidcGroupMappings_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."Organization"
        ADD CONSTRAINT "Organization_pkey" PRIMARY KEY ("orgId");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."RolePermissions"
        ADD CONSTRAINT "RolePermissions_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."UserOrganization"
        ADD CONSTRAINT "UserOrganization_pkey" PRIMARY KEY ("userId", "orgId");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."User"
        ADD CONSTRAINT "User_pkey" PRIMARY KEY ("userId");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."_prisma_migrations"
        ADD CONSTRAINT "_prisma_migrations_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."billing_product"
        ADD CONSTRAINT "billing_product_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."billing_product"
        ADD CONSTRAINT "billing_product_sku_key" UNIQUE ("sku");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_billing_account"
        ADD CONSTRAINT "org_billing_account_pkey" PRIMARY KEY ("org_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_billing_account"
        ADD CONSTRAINT "org_billing_account_stripe_customer_id_key" UNIQUE ("stripe_customer_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_entitlement_usage"
        ADD CONSTRAINT "org_entitlement_usage_pkey" PRIMARY KEY ("org_id", "key");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_subscription_item"
        ADD CONSTRAINT "org_subscription_item_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_subscription_item"
        ADD CONSTRAINT "org_subscription_item_stripe_subscription_item_id_key" UNIQUE ("stripe_subscription_item_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_subscription"
        ADD CONSTRAINT "org_subscription_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_subscription"
        ADD CONSTRAINT "org_subscription_stripe_subscription_id_key" UNIQUE ("stripe_subscription_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_PaymentMetadata"
        ADD CONSTRAINT "payment_metadata_org_id_key" UNIQUE ("org_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_payment_metadata"
        ADD CONSTRAINT "payment_metadata_org_id_unique" UNIQUE ("org_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_PaymentMetadata"
        ADD CONSTRAINT "payment_metadata_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_payment_metadata"
        ADD CONSTRAINT "payment_metadata_pkey1" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_PaymentMetadata"
        ADD CONSTRAINT "payment_metadata_stripe_customer_id_key" UNIQUE ("stripe_customer_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."postman_app_installations"
        ADD CONSTRAINT "postman_app_installations_pkey" PRIMARY KEY ("team_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."postman_collection_openapi_specs"
        ADD CONSTRAINT "postman_collection_openapi_specs_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_product_ownership"
        ADD CONSTRAINT "product_ownership_org_product_unique" UNIQUE ("org_id", "product_registry_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_product_ownership"
        ADD CONSTRAINT "product_ownership_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_product_registry"
        ADD CONSTRAINT "product_registry_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."stripe_event_inbox"
        ADD CONSTRAINT "stripe_event_inbox_pkey" PRIMARY KEY ("stripe_event_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."RolePermissions"
        ADD CONSTRAINT "unique_constraint_name" UNIQUE ("role", "permission");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."UserRolesPerResource"
        ADD CONSTRAINT "user_roles_per_resource_pkey" PRIMARY KEY ("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



CREATE UNIQUE INDEX IF NOT EXISTS "DocsInstance_id_key" ON "public"."DocsInstance" USING "btree" ("id");



CREATE UNIQUE INDEX IF NOT EXISTS "Feedback_eventId_key" ON "public"."Feedback" USING "btree" ("eventId");



CREATE UNIQUE INDEX IF NOT EXISTS "Organization_orgId_key" ON "public"."Organization" USING "btree" ("orgId");



CREATE INDEX IF NOT EXISTS "RolePermissions_role_idx" ON "public"."RolePermissions" USING "btree" ("role");



CREATE INDEX IF NOT EXISTS "UserRolesPerResource_user_id_org_id_resource_type_resource__idx" ON "public"."UserRolesPerResource" USING "btree" ("user_id", "org_id", "resource_type", "resource_id");



CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "public"."User" USING "btree" ("email");



CREATE UNIQUE INDEX IF NOT EXISTS "User_githubUsername_key" ON "public"."User" USING "btree" ("githubUsername");



CREATE UNIQUE INDEX IF NOT EXISTS "User_userId_key" ON "public"."User" USING "btree" ("userId");



CREATE INDEX IF NOT EXISTS "idx_cdv_docs_url" ON "public"."CustomDomainVerification" USING "btree" ("docsUrl");



CREATE INDEX IF NOT EXISTS "idx_cdv_domain" ON "public"."CustomDomainVerification" USING "btree" ("domain");



CREATE INDEX IF NOT EXISTS "idx_cdv_org_id" ON "public"."CustomDomainVerification" USING "btree" ("orgId");



CREATE INDEX IF NOT EXISTS "idx_cdv_status" ON "public"."CustomDomainVerification" USING "btree" ("status");



CREATE INDEX IF NOT EXISTS "idx_oidc_mappings_org_connection" ON "public"."OidcGroupMappings" USING "btree" ("org_id", "connection_name");



CREATE INDEX IF NOT EXISTS "idx_oidc_mappings_org_connection_group" ON "public"."OidcGroupMappings" USING "btree" ("org_id", "connection_name", "group_id");



CREATE INDEX IF NOT EXISTS "idx_oidc_mappings_org_created" ON "public"."OidcGroupMappings" USING "btree" ("org_id", "created_at" DESC);



CREATE UNIQUE INDEX IF NOT EXISTS "idx_oidc_mappings_unique" ON "public"."OidcGroupMappings" USING "btree" ("org_id", "connection_name", "group_id", "mapping_type", COALESCE("resource_type", ''::"text"), COALESCE("resource_id", ''::"text"));



CREATE INDEX IF NOT EXISTS "idx_org_entitlement_usage_org_id" ON "public"."org_entitlement_usage" USING "btree" ("org_id");



CREATE INDEX IF NOT EXISTS "idx_payment_metadata_org_id" ON "public"."deprecated_payment_metadata" USING "btree" ("org_id");



CREATE INDEX IF NOT EXISTS "idx_payment_metadata_stripe_customer_id" ON "public"."deprecated_payment_metadata" USING "btree" ("stripe_customer_id");



CREATE INDEX IF NOT EXISTS "idx_payment_metadata_subscription_id" ON "public"."deprecated_payment_metadata" USING "btree" ("subscription_id");



CREATE INDEX IF NOT EXISTS "idx_paymentmetadata_org_id" ON "public"."deprecated_PaymentMetadata" USING "btree" ("org_id");



CREATE INDEX IF NOT EXISTS "idx_paymentmetadata_product_ids" ON "public"."deprecated_PaymentMetadata" USING "gin" ("product_ids");



CREATE INDEX IF NOT EXISTS "idx_paymentmetadata_stripe_customer_id" ON "public"."deprecated_PaymentMetadata" USING "btree" ("stripe_customer_id");



CREATE INDEX IF NOT EXISTS "idx_paymentmetadata_subscription_id" ON "public"."deprecated_PaymentMetadata" USING "btree" ("subscription_id");



CREATE INDEX IF NOT EXISTS "idx_paymentmetadata_subscription_status" ON "public"."deprecated_PaymentMetadata" USING "btree" ("subscription_status");



CREATE INDEX IF NOT EXISTS "idx_postman_collection_openapi_specs_collection_id" ON "public"."postman_collection_openapi_specs" USING "btree" ("collection_id");



CREATE INDEX IF NOT EXISTS "idx_postman_collection_openapi_specs_team_id" ON "public"."postman_collection_openapi_specs" USING "btree" ("team_id");



CREATE INDEX IF NOT EXISTS "idx_product_ownership_org_id" ON "public"."deprecated_product_ownership" USING "btree" ("org_id");



CREATE INDEX IF NOT EXISTS "idx_product_ownership_org_status" ON "public"."deprecated_product_ownership" USING "btree" ("org_id", "status");



CREATE INDEX IF NOT EXISTS "idx_product_ownership_product_registry_id" ON "public"."deprecated_product_ownership" USING "btree" ("product_registry_id");



CREATE INDEX IF NOT EXISTS "idx_product_ownership_status" ON "public"."deprecated_product_ownership" USING "btree" ("status");



CREATE INDEX IF NOT EXISTS "idx_product_registry_tier" ON "public"."deprecated_product_registry" USING "btree" ("tier");



CREATE INDEX IF NOT EXISTS "idx_product_registry_type" ON "public"."deprecated_product_registry" USING "btree" ("type");



CREATE INDEX IF NOT EXISTS "org_subscription_item_org_subscription_id_idx" ON "public"."org_subscription_item" USING "btree" ("org_subscription_id");



CREATE INDEX IF NOT EXISTS "org_subscription_org_id_idx" ON "public"."org_subscription" USING "btree" ("org_id");



CREATE INDEX IF NOT EXISTS "org_subscription_org_id_status_idx" ON "public"."org_subscription" USING "btree" ("org_id", "status");



CREATE INDEX IF NOT EXISTS "stripe_event_inbox_processed_at_idx" ON "public"."stripe_event_inbox" USING "btree" ("processed_at") WHERE ("processed_at" IS NULL);



CREATE OR REPLACE TRIGGER "trigger_oidc_mappings_updated_at" BEFORE UPDATE ON "public"."OidcGroupMappings" FOR EACH ROW EXECUTE FUNCTION "public"."update_oidc_mappings_updated_at"();



CREATE OR REPLACE TRIGGER "trigger_paymentmetadata_updated_at" BEFORE UPDATE ON "public"."deprecated_PaymentMetadata" FOR EACH ROW EXECUTE FUNCTION "public"."update_paymentmetadata_updated_at"();



CREATE OR REPLACE TRIGGER "update_custom_domain_verification_updated_at" BEFORE UPDATE ON "public"."CustomDomainVerification" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



DO $$ BEGIN
    ALTER TABLE ONLY "public"."DocsInstance"
        ADD CONSTRAINT "DocsInstance_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."Organization"("orgId") ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."Feedback"
        ADD CONSTRAINT "Feedback_docsInstanceId_fkey" FOREIGN KEY ("docsInstanceId") REFERENCES "public"."DocsInstance"("id") ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."UserOrganization"
        ADD CONSTRAINT "UserOrganization_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."Organization"("orgId") ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."UserOrganization"
        ADD CONSTRAINT "UserOrganization_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("userId") ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_subscription_item"
        ADD CONSTRAINT "org_subscription_item_org_billing_product_fkey" FOREIGN KEY ("org_billing_product") REFERENCES "public"."billing_product"("id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_subscription_item"
        ADD CONSTRAINT "org_subscription_item_org_subscription_id_fkey" FOREIGN KEY ("org_subscription_id") REFERENCES "public"."org_subscription"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."org_subscription"
        ADD CONSTRAINT "org_subscription_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."org_billing_account"("org_id");
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



DO $$ BEGIN
    ALTER TABLE ONLY "public"."deprecated_product_ownership"
        ADD CONSTRAINT "product_ownership_product_registry_id_fkey" FOREIGN KEY ("product_registry_id") REFERENCES "public"."deprecated_product_registry"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



ALTER TABLE "public"."AnalyticsRecord" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."CustomDomainVerification" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."deprecated_payment_metadata" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."deprecated_product_ownership" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."deprecated_product_registry" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."postman_app_installations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."postman_collection_openapi_specs" ENABLE ROW LEVEL SECURITY;


DO $$ BEGIN
    CREATE POLICY "stripe inbox service all" ON "public"."stripe_event_inbox" TO "service_role" USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN null;
END $$;



ALTER TABLE "public"."stripe_event_inbox" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "service_role";




































GRANT ALL ON TABLE "public"."AnalyticsRecord" TO "service_role";



GRANT ALL ON SEQUENCE "public"."AnalyticsRecord_id_seq" TO "service_role";
GRANT SELECT,USAGE ON SEQUENCE "public"."AnalyticsRecord_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."CustomDomainVerification" TO "service_role";
GRANT ALL ON TABLE "public"."CustomDomainVerification" TO "authenticated";



GRANT ALL ON SEQUENCE "public"."Feedback_id_seq" TO "service_role";
GRANT SELECT,USAGE ON SEQUENCE "public"."Feedback_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."OidcGroupMappings" TO "service_role";



GRANT ALL ON TABLE "public"."RolePermissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."RolePermissions_id_seq" TO "service_role";
GRANT SELECT,USAGE ON SEQUENCE "public"."RolePermissions_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."UserRolesPerResource" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."billing_product" TO "service_role";



GRANT ALL ON TABLE "public"."deprecated_PaymentMetadata" TO "service_role";



GRANT ALL ON TABLE "public"."deprecated_payment_metadata" TO "service_role";
GRANT ALL ON TABLE "public"."deprecated_payment_metadata" TO "authenticated";
GRANT ALL ON TABLE "public"."deprecated_payment_metadata" TO "anon";



GRANT ALL ON TABLE "public"."deprecated_product_ownership" TO "service_role";
GRANT ALL ON TABLE "public"."deprecated_product_ownership" TO "authenticated";
GRANT ALL ON TABLE "public"."deprecated_product_ownership" TO "anon";



GRANT ALL ON TABLE "public"."deprecated_product_registry" TO "service_role";
GRANT ALL ON TABLE "public"."deprecated_product_registry" TO "authenticated";
GRANT ALL ON TABLE "public"."deprecated_product_registry" TO "anon";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."org_subscription" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."org_subscription_item" TO "service_role";



GRANT SELECT ON TABLE "public"."org_active_products" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."org_billing_account" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."org_entitlement_usage" TO "service_role";



GRANT ALL ON TABLE "public"."postman_app_installations" TO "service_role";
GRANT ALL ON TABLE "public"."postman_app_installations" TO "authenticated";
GRANT ALL ON TABLE "public"."postman_app_installations" TO "anon";



GRANT ALL ON TABLE "public"."postman_collection_openapi_specs" TO "anon";
GRANT ALL ON TABLE "public"."postman_collection_openapi_specs" TO "authenticated";
GRANT ALL ON TABLE "public"."postman_collection_openapi_specs" TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "public"."stripe_event_inbox" TO "service_role";
