// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export type ApiAuth =
    | FdrLambda.api.v1.read.ApiAuth.BearerAuth
    | FdrLambda.api.v1.read.ApiAuth.BasicAuth
    | FdrLambda.api.v1.read.ApiAuth.Header
    | FdrLambda.api.v1.read.ApiAuth.OAuth;

export namespace ApiAuth {
    export interface BearerAuth extends FdrLambda.api.v1.read.BearerAuth {
        type: "bearerAuth";
    }

    export interface BasicAuth extends FdrLambda.api.v1.read.BasicAuth {
        type: "basicAuth";
    }

    export interface Header extends FdrLambda.api.v1.read.HeaderAuth {
        type: "header";
    }

    export interface OAuth {
        type: "oAuth";
        value: FdrLambda.api.v1.read.OAuth;
    }
}
