// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface ApiDefinitionPackage {
    endpoints: FdrLambda.api.v1.read.EndpointDefinition[];
    websockets: FdrLambda.api.v1.read.WebSocketChannel[];
    webhooks: FdrLambda.api.v1.read.WebhookDefinition[];
    types: FdrLambda.TypeId[];
    subpackages: FdrLambda.api.v1.SubpackageId[];
    /**
     * if present, this package should be replaced with the provided subpackage
     * in the docs navigation.
     */
    pointsTo: FdrLambda.api.v1.SubpackageId | undefined;
}
