/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface ApiDefinitionSubpackage
    extends FdrLambda.api.v1.WithDescription, FdrLambda.api.v1.read.ApiDefinitionPackage {
    parent: FdrLambda.api.v1.SubpackageId | undefined;
    subpackageId: FdrLambda.api.v1.SubpackageId;
    name: string;
    urlSlug: string;
    displayName: string | undefined;
}
