/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface ApiNavigationConfigSubpackage {
    subpackageId: FdrLambda.api.v1.SubpackageId;
    items: FdrLambda.api.v1.read.ApiNavigationConfigItem[];
}
