// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export type ApiNavigationConfigItem =
    | FdrLambda.api.v1.read.ApiNavigationConfigItem.Subpackage
    | FdrLambda.api.v1.read.ApiNavigationConfigItem.EndpointId
    | FdrLambda.api.v1.read.ApiNavigationConfigItem.WebsocketId
    | FdrLambda.api.v1.read.ApiNavigationConfigItem.WebhookId
    | FdrLambda.api.v1.read.ApiNavigationConfigItem.GraphqlOperationId;

export namespace ApiNavigationConfigItem {
    export interface Subpackage extends FdrLambda.api.v1.read.ApiNavigationConfigSubpackage {
        type: "subpackage";
    }

    export interface EndpointId {
        type: "endpointId";
        value: FdrLambda.EndpointId;
    }

    export interface WebsocketId {
        type: "websocketId";
        value: FdrLambda.WebSocketId;
    }

    export interface WebhookId {
        type: "webhookId";
        value: FdrLambda.WebhookId;
    }

    export interface GraphqlOperationId {
        type: "graphqlOperationId";
        value: FdrLambda.GraphQlOperationId;
    }
}
