/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface BasicAuth extends FdrLambda.api.v1.WithDescription {
    usernameName?: string;
    passwordName?: string;
}
