/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface BearerAuth extends FdrLambda.api.v1.WithDescription {
    tokenName: string | undefined;
}
