// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface HeaderAuth extends FdrLambda.api.v1.WithDescription {
    nameOverride: string | undefined;
    headerWireValue: string;
    /** The prefix that comes before the header */
    prefix: string | undefined;
}
