// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface OAuthClientCredentialsReferencedEndpoint extends FdrLambda.api.v1.WithDescription {
    endpointId: FdrLambda.EndpointId;
    accessTokenLocator: FdrLambda.JqString;
    headerName: string | undefined;
    tokenPrefix: string | undefined;
}
