/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type OAuthClientCredentials = FdrLambda.api.v1.read.OAuthClientCredentials.ReferencedEndpoint;

export namespace OAuthClientCredentials {
    export interface ReferencedEndpoint extends FdrLambda.api.v1.read.OAuthClientCredentialsReferencedEndpoint {
        type: "referencedEndpoint";
    }
}
