/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         domain: "domain"
 *     }
 */
export interface CreateSlackIntegration {
    domain: string;
}
