/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         code: "code",
 *         state: "state"
 *     }
 */
export interface HandleSlackOauthCallbackRequest {
    code: string;
    state?: string;
}
