FROM python:3.13-slim-bookworm

COPY pyproject.toml ./pyproject.toml
COPY poetry.lock ./poetry.lock
COPY ./src ./src
COPY ./logging.conf ./logging.conf
COPY ./.env.discord ./.env.discord

RUN pip3 install poetry &&\
  poetry config virtualenvs.create false &&\
  poetry install

ENTRYPOINT ["poetry", "run", "discord"]
