/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         task_arn: "task_arn"
 *     }
 */
export interface GetReindexingJobStatusByTaskArnRequest {
    task_arn: string;
}
