/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         status: "status",
 *         memory_mb: 1,
 *         retry_count: 1,
 *         task_arn: "task_arn",
 *         sqs_message_id: "sqs_message_id",
 *         completed_at: "completed_at",
 *         duration_ms: 1,
 *         num_inserted: 1,
 *         error: "error",
 *         reason: "reason"
 *     }
 */
export interface UpdateReindexingJobStatusEndpointRequest {
    status: string;
    memory_mb?: number;
    retry_count?: number;
    task_arn?: string;
    sqs_message_id?: string;
    completed_at?: string;
    duration_ms?: number;
    num_inserted?: number;
    error?: string;
    reason?: string;
}
