/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface AiChatConfig {
    model: FdrLambda.docs.v1.commons.AiModel | undefined;
    systemPrompt: string | undefined;
    location: FdrLambda.docs.v1.commons.AiChatLocation[] | undefined;
    datasources: FdrLambda.docs.v1.commons.AiChatDatasource[] | undefined;
}
