/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface AnalyticsConfig {
    segment?: FdrLambda.docs.v1.commons.SegmentConfig;
    fullstory?: FdrLambda.docs.v1.commons.FullStoryAnalyticsConfig;
    intercom?: FdrLambda.docs.v1.commons.IntercomConfig;
    posthog?: FdrLambda.docs.v1.commons.PostHogConfig;
    gtm?: FdrLambda.docs.v1.commons.GtmConfig;
    ga4?: FdrLambda.docs.v1.commons.GoogleAnalytics4Config;
    amplitude?: FdrLambda.docs.v1.commons.AmplitudeConfig;
    mixpanel?: FdrLambda.docs.v1.commons.MixpanelConfig;
    hotjar?: FdrLambda.docs.v1.commons.HotJarConfig;
    koala?: FdrLambda.docs.v1.commons.KoalaConfig;
    logrocket?: FdrLambda.docs.v1.commons.LogRocketConfig;
    pirsch?: FdrLambda.docs.v1.commons.PirschConfig;
    plausible?: FdrLambda.docs.v1.commons.PlausibleConfig;
    fathom?: FdrLambda.docs.v1.commons.FathomConfig;
    clearbit?: FdrLambda.docs.v1.commons.ClearBitConfig;
    heap?: FdrLambda.docs.v1.commons.HeapConfig;
}
