// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface AnalyticsConfig {
    segment: FdrLambda.docs.v1.commons.SegmentConfig | undefined;
    fullstory: FdrLambda.docs.v1.commons.FullStoryAnalyticsConfig | undefined;
    intercom: FdrLambda.docs.v1.commons.IntercomConfig | undefined;
    posthog: FdrLambda.docs.v1.commons.PostHogConfig | undefined;
    gtm: FdrLambda.docs.v1.commons.GtmConfig | undefined;
    ga4: FdrLambda.docs.v1.commons.GoogleAnalytics4Config | undefined;
    amplitude: FdrLambda.docs.v1.commons.AmplitudeConfig | undefined;
    mixpanel: FdrLambda.docs.v1.commons.MixpanelConfig | undefined;
    hotjar: FdrLambda.docs.v1.commons.HotJarConfig | undefined;
    koala: FdrLambda.docs.v1.commons.KoalaConfig | undefined;
    logrocket: FdrLambda.docs.v1.commons.LogRocketConfig | undefined;
    pirsch: FdrLambda.docs.v1.commons.PirschConfig | undefined;
    plausible: FdrLambda.docs.v1.commons.PlausibleConfig | undefined;
    fathom: FdrLambda.docs.v1.commons.FathomConfig | undefined;
    clearbit: FdrLambda.docs.v1.commons.ClearBitConfig | undefined;
    heap: FdrLambda.docs.v1.commons.HeapConfig | undefined;
}
