// This file was auto-generated by Fern from our API Definition.

/**
 * A custom page action that can be configured by the user.
 */
export interface CustomPageAction {
    /** The title of the custom action. */
    title: string;
    /** The subtitle/helper text of the custom action. */
    subtitle: string | undefined;
    /** The URL to navigate to. Supports placeholders - {slug} for page slug, {domain} for domain, and {url} for the full URL (https://domain/slug). */
    url: string;
    /** Icon to display for the custom action. Can be a file ID (e.g., "file:my-icon"), an image URL (starting with http://, https://, or /), or a Font Awesome icon name (e.g., "fas fa-star" or "star"). */
    icon: string | undefined;
    /** Whether this custom action should be the default action. */
    default: boolean | undefined;
}
