// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface CustomFontConfigVariant {
    fontFile: FdrLambda.FileId;
    weight: string[] | undefined;
    style: FdrLambda.docs.v1.commons.FontStyle[] | undefined;
}
