// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface DocsThemeConfig {
    sidebar: FdrLambda.docs.v1.commons.DocsSidebarConfig | undefined;
    body: FdrLambda.docs.v1.commons.DocsBodyConfig | undefined;
    tabs: FdrLambda.docs.v1.commons.DocsTabsConfig | undefined;
    footerNav: FdrLambda.docs.v1.commons.FooterNavConfig | undefined;
    "page-actions": FdrLambda.docs.v1.commons.DocsPageActionsConfig | undefined;
    "language-switcher": FdrLambda.docs.v1.commons.LanguageSwitcherConfig | undefined;
    "product-switcher": FdrLambda.docs.v1.commons.ProductSwitcherConfig | undefined;
}
