/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface DocsSettingsConfig {
    searchText: string | undefined;
    disableSearch: boolean | undefined;
    darkModeCode: boolean | undefined;
    defaultSearchFilters: boolean | undefined;
    httpSnippets: FdrLambda.docs.v1.commons.HttpSnippetsConfig | undefined;
    hide404Page: boolean | undefined;
    useJavascriptAsTypescript: boolean | undefined;
}
