// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export const DocsTabsStyle = {
    Default: "default",
    Bubble: "bubble",
} as const;
export type DocsTabsStyle = (typeof DocsTabsStyle)[keyof typeof DocsTabsStyle];

export interface DocsTabsObjectConfig {
    style?: FdrLambda.docs.v1.commons.DocsTabsStyle;
    alignment?: FdrLambda.docs.v1.commons.TabsAlignment;
    placement?: FdrLambda.docs.v1.commons.TabsPlacement;
}

export type DocsTabsConfig = DocsTabsStyle | DocsTabsObjectConfig;
