/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface DocsTypographyConfigV2 {
    headingsFont?: FdrLambda.docs.v1.commons.FontConfigV2;
    bodyFont?: FdrLambda.docs.v1.commons.FontConfigV2;
    codeFont?: FdrLambda.docs.v1.commons.FontConfigV2;
}
