/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface DocsLayoutConfig {
    pageWidth?: FdrLambda.docs.v1.commons.PageWidthSizeConfig;
    contentWidth?: FdrLambda.docs.v1.commons.SizeConfig;
    sidebarWidth?: FdrLambda.docs.v1.commons.SizeConfig;
    headerHeight?: FdrLambda.docs.v1.commons.SizeConfig;
    searchbarPlacement?: FdrLambda.docs.v1.commons.SearchbarPlacement;
    tabsPlacement?: FdrLambda.docs.v1.commons.TabsPlacement;
    contentAlignment?: FdrLambda.docs.v1.commons.ContentAlignment;
    headerPosition?: FdrLambda.docs.v1.commons.HeaderPosition;
    disableHeader?: boolean;
    hideNavLinks?: boolean;
    hideFeedback?: boolean;
}
