/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface DocsSettingsConfig {
    searchText?: string;
    disableSearch?: boolean;
    darkModeCode?: boolean;
    defaultSearchFilters?: boolean;
    httpSnippets?: FdrLambda.docs.v1.commons.HttpSnippetsConfig;
    hide404Page?: boolean;
    useJavascriptAsTypescript?: boolean;
}
