// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export type FileIdOrUrl = FdrLambda.docs.v1.commons.FileIdOrUrl.FileId | FdrLambda.docs.v1.commons.FileIdOrUrl.Url;

export namespace FileIdOrUrl {
    export interface FileId {
        type: "fileId";
        value: FdrLambda.FileId;
    }

    export interface Url {
        type: "url";
        value: FdrLambda.Url;
    }
}
