/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export type FontConfigV2 = FdrLambda.docs.v1.commons.FontConfigV2.Custom;

export namespace FontConfigV2 {
    export interface Custom extends FdrLambda.docs.v1.commons.CustomFontConfig {
        type: "custom";
    }
}
