/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FooterNavConfig = "default" | "minimal";
export const FooterNavConfig = {
    Default: "default",
    Minimal: "minimal",
} as const;
