/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export type FooterLink =
    | FdrLambda.docs.v1.commons.FooterLink.Github
    | FdrLambda.docs.v1.commons.FooterLink.Twitter
    | FdrLambda.docs.v1.commons.FooterLink.X
    | FdrLambda.docs.v1.commons.FooterLink.Linkedin
    | FdrLambda.docs.v1.commons.FooterLink.Youtube
    | FdrLambda.docs.v1.commons.FooterLink.Instagram
    | FdrLambda.docs.v1.commons.FooterLink.Facebook
    | FdrLambda.docs.v1.commons.FooterLink.Discord
    | FdrLambda.docs.v1.commons.FooterLink.Slack
    | FdrLambda.docs.v1.commons.FooterLink.Hackernews
    | FdrLambda.docs.v1.commons.FooterLink.Medium
    | FdrLambda.docs.v1.commons.FooterLink.Website;

export namespace FooterLink {
    export interface Github {
        type: "github";
        value: FdrLambda.Url;
    }

    export interface Twitter {
        type: "twitter";
        value: FdrLambda.Url;
    }

    export interface X {
        type: "x";
        value: FdrLambda.Url;
    }

    export interface Linkedin {
        type: "linkedin";
        value: FdrLambda.Url;
    }

    export interface Youtube {
        type: "youtube";
        value: FdrLambda.Url;
    }

    export interface Instagram {
        type: "instagram";
        value: FdrLambda.Url;
    }

    export interface Facebook {
        type: "facebook";
        value: FdrLambda.Url;
    }

    export interface Discord {
        type: "discord";
        value: FdrLambda.Url;
    }

    export interface Slack {
        type: "slack";
        value: FdrLambda.Url;
    }

    export interface Hackernews {
        type: "hackernews";
        value: FdrLambda.Url;
    }

    export interface Medium {
        type: "medium";
        value: FdrLambda.Url;
    }

    export interface Website {
        type: "website";
        value: FdrLambda.Url;
    }
}
