/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type HttpSnippetLanguage =
    | "curl"
    | "csharp"
    | "go"
    | "java"
    | "javascript"
    | "php"
    | "python"
    | "ruby"
    | "swift"
    | "rust"
    | "typescript";
export const HttpSnippetLanguage = {
    Curl: "curl",
    Csharp: "csharp",
    Go: "go",
    Java: "java",
    Javascript: "javascript",
    Php: "php",
    Python: "python",
    Ruby: "ruby",
    Swift: "swift",
    Rust: "rust",
    Typescript: "typescript"
} as const;
