/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface JsConfig {
    remote?: FdrLambda.docs.v1.commons.JsRemoteConfig[];
    files: FdrLambda.docs.v1.commons.JsFileConfig[];
    inline?: string[];
}
