/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface JsFileConfig {
    fileId: FdrLambda.FileId;
    strategy: FdrLambda.docs.v1.commons.JsScriptStrategy | undefined;
}
