/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface MetadataConfig {
    "og:site_name"?: string;
    "og:title"?: string;
    "og:description"?: string;
    "og:url"?: string;
    "og:image"?: FdrLambda.docs.v1.commons.FileIdOrUrl;
    "og:image:width"?: number;
    "og:image:height"?: number;
    "og:locale"?: string;
    "og:logo"?: FdrLambda.docs.v1.commons.FileIdOrUrl;
    "twitter:title"?: string;
    "twitter:description"?: string;
    "twitter:handle"?: string;
    "twitter:image"?: FdrLambda.docs.v1.commons.FileIdOrUrl;
    "twitter:site"?: string;
    "twitter:url"?: string;
    "twitter:card"?: FdrLambda.docs.v1.commons.TwitterCardSetting;
    noindex?: boolean;
    nofollow?: boolean;
    canonicalHost?: string;
}
