/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface NavbarGithubMetadata extends FdrLambda.docs.v1.commons.WithPermissions {
    url: FdrLambda.Url;
    target: FdrLambda.LinkTarget | undefined;
}
