// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface NavbarLinkMetadata extends FdrLambda.docs.v1.commons.WithPermissions {
    url: FdrLambda.Url;
    target: FdrLambda.LinkTarget | undefined;
    text: string | undefined;
    icon: string | undefined;
    rightIcon: string | undefined;
    rounded: boolean | undefined;
}
