/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface NavbarLinkDropdownMetadata extends FdrLambda.docs.v1.commons.WithPermissions {
    links: FdrLambda.docs.v1.commons.NavbarLinkMetadata[];
    text: string | undefined;
    icon: string | undefined;
    rightIcon: string | undefined;
    rounded: boolean | undefined;
}
