/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface NavbarLinkMetadata {
    url: FdrLambda.Url;
    text: string | undefined;
    icon: string | undefined;
    rightIcon: string | undefined;
    rounded: boolean | undefined;
}
