// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface PageActionOptions {
    copyPage: boolean | undefined;
    viewAsMarkdown: boolean | undefined;
    askAi: boolean | undefined;
    openAi: boolean | undefined;
    claude: boolean | undefined;
    cursor: boolean | undefined;
    vscode: boolean | undefined;
    custom: FdrLambda.docs.v1.commons.CustomPageAction[] | undefined;
}
