// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface PageActionsConfig {
    default: FdrLambda.docs.v1.commons.PageActionOption | undefined;
    options: FdrLambda.docs.v1.commons.PageActionOptions | undefined;
}
