/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PageActionOption = "copyPage" | "viewAsMarkdown" | "askAi" | "openAi" | "claude" | "cursor" | "vscode";
export const PageActionOption = {
    CopyPage: "copyPage",
    ViewAsMarkdown: "viewAsMarkdown",
    AskAi: "askAi",
    OpenAi: "openAi",
    Claude: "claude",
    Cursor: "cursor",
    Vscode: "vscode"
} as const;
