/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FernRegistry from "../../../../../../../../../index.js";

export interface PageActionOptions {
    copyPage: boolean | undefined;
    viewAsMarkdown: boolean | undefined;
    askAi: boolean | undefined;
    openAi: boolean | undefined;
    claude: boolean | undefined;
    cursor: boolean | undefined;
    vscode: boolean | undefined;
    custom: FernRegistry.docs.v1.commons.CustomPageAction[] | undefined;
}
