// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export type SizeConfig = FdrLambda.docs.v1.commons.SizeConfig.Px | FdrLambda.docs.v1.commons.SizeConfig.Rem;

export namespace SizeConfig {
    export interface Px {
        type: "px";
        value: number;
    }

    export interface Rem {
        type: "rem";
        value: number;
    }
}
