/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { Api } from "./api/resources/api/client/Client.js";
import { Docs } from "./api/resources/docs/client/Client.js";

export declare namespace FdrLambdaClient {
    export interface Options {
        environment?: core.Supplier<environments.FdrLambdaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class FdrLambdaClient {
    protected _api: Api | undefined;
    protected _docs: Docs | undefined;

    constructor(protected readonly _options: FdrLambdaClient.Options) {}

    public get api(): Api {
        return (this._api ??= new Api(this._options));
    }

    public get docs(): Docs {
        return (this._docs ??= new Docs(this._options));
    }
}
