// This file was auto-generated by Fern from our API Definition.

import { ApiClient } from "./api/resources/api/client/Client.js";
import { DocsClient } from "./api/resources/docs/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace FdrLambdaClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FdrLambdaClient {
    protected readonly _options: FdrLambdaClient.Options;
    protected _api: ApiClient | undefined;
    protected _docs: DocsClient | undefined;

    constructor(options: FdrLambdaClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get api(): ApiClient {
        return (this._api ??= new ApiClient(this._options));
    }

    public get docs(): DocsClient {
        return (this._docs ??= new DocsClient(this._options));
    }
}
