// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

/**
 * A GraphQL operation (query, mutation, or subscription)
 */
export interface GraphQlOperation
    extends FdrLambda.api.latest.WithDescription,
        FdrLambda.api.latest.WithAvailability,
        FdrLambda.api.latest.WithNamespace {
    id: FdrLambda.GraphQlOperationId;
    operationType: FdrLambda.api.latest.GraphQlOperationType;
    name: string;
    displayName: string | undefined;
    arguments: FdrLambda.api.latest.GraphQlArgument[] | undefined;
    returnType: FdrLambda.api.latest.TypeShape;
    examples: FdrLambda.api.latest.GraphQlExample[] | undefined;
    snippets: Record<FdrLambda.api.latest.Language, FdrLambda.api.latest.CodeSnippet[]> | undefined;
}
