// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

/**
 * An argument to a GraphQL operation
 */
export interface GraphQlArgument extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    name: string;
    type: FdrLambda.api.latest.TypeShape;
    defaultValue: unknown | undefined;
}
