/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         diff: "diff"
 *     }
 */
export interface AnalyzeCommitDiffRequest {
    /** The git diff to analyze for generating a commit message */
    diff: string;
}
