/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         domain: "domain",
 *         org_name: "org_name",
 *         incremental: true
 *     }
 */
export interface ReindexAskAiRequest {
    domain: string;
    org_name?: string;
    incremental?: boolean;
}
