/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         status: "success",
 *         sourceMessageId: "sourceMessageId"
 *     }
 */
export interface ReindexCallbackRequest {
    status: ReindexCallbackRequest.Status;
    sourceMessageId: string;
    domain?: string;
    url?: string;
}

export namespace ReindexCallbackRequest {
    export type Status = "success" | "failure";
    export const Status = {
        Success: "success",
        Failure: "failure",
    } as const;
}
