/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface SnippetsConfig {
    typescriptSdk: FdrLambda.api.v1.register.TypescriptPackage | undefined;
    pythonSdk: FdrLambda.api.v1.register.PythonPackage | undefined;
    goSdk: FdrLambda.api.v1.register.GoModule | undefined;
    javaSdk: FdrLambda.api.v1.register.JavaCoordinate | undefined;
    rubySdk: FdrLambda.api.v1.register.RubyGem | undefined;
    csharpSdk: FdrLambda.api.v1.register.NugetPackage | undefined;
    phpSdk: FdrLambda.api.v1.register.ComposerPackage | undefined;
    swiftSdk: FdrLambda.api.v1.register.SwiftPackage | undefined;
    rustSdk: FdrLambda.api.v1.register.CratesPackage | undefined;
}
