// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface DiscriminatedUnionType {
    discriminant: FdrLambda.PropertyKey;
    variants: FdrLambda.api.latest.DiscriminatedUnionVariant[];
}
