/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface DiscriminatedUnionVariant
    extends FdrLambda.api.latest.WithDescription,
        FdrLambda.api.latest.WithAvailability,
        FdrLambda.api.latest.ObjectType {
    discriminantValue: string;
    displayName: string | undefined;
}
