/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface EnumValue extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    value: string;
}
