/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface FormDataFiles extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    key: FdrLambda.PropertyKey;
    isOptional: boolean;
    contentType?: FdrLambda.api.latest.ContentType;
}
