// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface FormDataProperty extends FdrLambda.api.latest.ObjectProperty {
    contentType: FdrLambda.api.latest.ContentType | undefined;
    exploded: boolean | undefined;
}
