/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export type FormDataField =
    | FdrLambda.api.latest.FormDataField.File_
    | FdrLambda.api.latest.FormDataField.Files
    | FdrLambda.api.latest.FormDataField.Property;

export namespace FormDataField {
    export interface File_ extends FdrLambda.api.latest.FormDataFile {
        type: "file";
    }

    export interface Files extends FdrLambda.api.latest.FormDataFiles {
        type: "files";
    }

    export interface Property extends FdrLambda.api.latest.FormDataProperty {
        type: "property";
    }
}
