/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface FormDataRequest extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    fields: FdrLambda.api.latest.FormDataField[];
}
