/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface ObjectType {
    extends: FdrLambda.TypeId[];
    properties: FdrLambda.api.latest.ObjectProperty[];
    extraProperties?: FdrLambda.api.latest.TypeReference;
}
