/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface ObjectProperty extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    key: FdrLambda.PropertyKey;
    valueShape: FdrLambda.api.latest.TypeShape;
    propertyAccess?: FdrLambda.api.latest.ObjectPropertyAccess;
}
