/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface OptionalType {
    shape: FdrLambda.api.latest.TypeShape;
    default: unknown | undefined;
}
