/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export type PrimitiveType = FdrLambda.api.v1.read.PrimitiveType;
