/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type TypeShape =
    | FdrLambda.api.latest.TypeShape.Alias
    | FdrLambda.api.latest.TypeShape.Enum
    | FdrLambda.api.latest.TypeShape.UndiscriminatedUnion
    | FdrLambda.api.latest.TypeShape.DiscriminatedUnion
    | FdrLambda.api.latest.TypeShape.Object_;

export namespace TypeShape {
    export interface Alias {
        type: "alias";
        value: FdrLambda.api.latest.TypeReference;
    }

    export interface Enum extends FdrLambda.api.latest.EnumType {
        type: "enum";
    }

    export interface UndiscriminatedUnion extends FdrLambda.api.latest.UndiscriminatedUnionType {
        type: "undiscriminatedUnion";
    }

    export interface DiscriminatedUnion extends FdrLambda.api.latest.DiscriminatedUnionType {
        type: "discriminatedUnion";
    }

    export interface Object_ extends FdrLambda.api.latest.ObjectType {
        type: "object";
    }
}
