/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type TypeReference =
    | FdrLambda.api.latest.TypeReference.Id
    | FdrLambda.api.latest.TypeReference.Primitive
    | FdrLambda.api.latest.TypeReference.Optional
    | FdrLambda.api.latest.TypeReference.Nullable
    | FdrLambda.api.latest.TypeReference.List
    | FdrLambda.api.latest.TypeReference.Set
    | FdrLambda.api.latest.TypeReference.Map
    | FdrLambda.api.latest.TypeReference.Literal
    | FdrLambda.api.latest.TypeReference.Unknown;

export namespace TypeReference {
    export interface Id extends FdrLambda.api.latest.TypeReferenceId {
        type: "id";
    }

    export interface Primitive {
        type: "primitive";
        value: FdrLambda.api.latest.PrimitiveType;
    }

    export interface Optional extends FdrLambda.api.latest.OptionalType {
        type: "optional";
    }

    export interface Nullable extends FdrLambda.api.latest.NullableType {
        type: "nullable";
    }

    export interface List extends FdrLambda.api.latest.ListType {
        type: "list";
    }

    export interface Set extends FdrLambda.api.latest.SetType {
        type: "set";
    }

    export interface Map extends FdrLambda.api.latest.MapType {
        type: "map";
    }

    export interface Literal {
        type: "literal";
        value: FdrLambda.api.latest.LiteralType;
    }

    export interface Unknown extends FdrLambda.api.latest.UnknownType {
        type: "unknown";
    }
}
