/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface TypeDefinition extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    name: string;
    shape: FdrLambda.api.latest.TypeShape;
    displayName?: string;
}
