/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface TypeReferenceId {
    id: FdrLambda.TypeId;
    default?: FdrLambda.api.latest.TypeReferenceIdDefault;
}
