/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface UndiscriminatedUnionVariant
    extends FdrLambda.api.latest.WithDescription,
        FdrLambda.api.latest.WithAvailability {
    displayName?: string;
    shape: FdrLambda.api.latest.TypeShape;
}
