/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface UndiscriminatedUnionType {
    variants: FdrLambda.api.latest.UndiscriminatedUnionVariant[];
}
