import { cn } from "@fern-docs/components/cn";
import { FernAnchor } from "@fern-docs/components/FernAnchor";
import { Prose } from "@fern-docs/components/mdx/prose";
import { t } from "@fern-docs/i18n";
import type React from "react";

export const ParamField: React.FC<
    React.PropsWithChildren<{
        type: string;
        default?: string;
        required?: boolean;
        deprecated?: boolean;
        className?: string;
        toc?: boolean;
        /** id generated by rehype-slug plugin */
        id?: string;
        /** title generated by rehype-param-field plugin */
        title?: string;
        /**
         * whether this is the last parameter in the list.
         * used to remove the bottom border.
         */
        last?: boolean;
        /** @deprecated unused Mintlify prop */
        initialValue?: any;
        /** @deprecated unused Mintlify prop */
        placeholder?: string;
        lang: string;
    }> &
        ({ query: string } | { path: string } | { body: string } | { header: string })
> = ({
    type,
    default: defaultProp,
    required,
    deprecated,
    toc,
    className,
    children,
    id,
    title,
    last,
    lang = "en",
    ...props
}) => {
    // use title prop if available, otherwise fall back to extracting from props
    const name =
        title ||
        ("query" in props ? props.query : "path" in props ? props.path : "body" in props ? props.body : props.header);

    return (
        <div className={cn("fern-api-property border-border-default border-b", last && "border-b-0", className)}>
            <div className="fern-api-property-header">
                {toc ? (
                    <FernAnchor href={`#${id}`} asChild>
                        <h6 className="fern-api-property-key" id={id}>
                            {name}
                        </h6>
                    </FernAnchor>
                ) : (
                    <div className="fern-api-property-key">{name}</div>
                )}
                <div className="fern-api-property-meta">
                    <span>{type}</span>
                    {defaultProp && (
                        <span>
                            {t(lang).playground.defaultsTo} {defaultProp}
                        </span>
                    )}
                    {deprecated && <span className="text-(color:--amber-a11)">{t(lang).apiReference.deprecated}</span>}
                    {required && <span className="text-(color:--red-a11)">{t(lang).apiReference.required}</span>}
                </div>
            </div>
            {children && <Prose size="sm">{children}</Prose>}
        </div>
    );
};
