from pydantic import BaseModel, Field


class OpenApiGeneratorConfig(BaseModel):
    """Configuration for OpenAPI generator."""

    source_path: str


class GeneratorConfig(BaseModel):
    """Configuration for all generators."""

    openapi: OpenApiGeneratorConfig | None = None


class SuiteConfig(BaseModel):
    """Configuration for an evaluation suite."""

    domain: str
    generators: list[str] = Field(default_factory=list)
    evaluators: list[str] = Field(default_factory=list)
    num_questions_generation: int | None = None
    generator_config: GeneratorConfig | None = None


class Question(BaseModel):
    """A question with ground truth for evaluation."""

    question: str
    ground_truth: str
    metadata: dict[str, str] = Field(default_factory=dict)


class Answer(BaseModel):
    """An answer generated by a model for a question."""

    question: str
    answer: str
    model: str
    metadata: dict[str, str] = Field(default_factory=dict)


class Evaluation(BaseModel):
    """Result of evaluating an answer against ground truth."""

    question: str
    answer: str
    ground_truth: str
    is_correct: bool
    reason: str
    metadata: dict[str, str] = Field(default_factory=dict)


class EvaluationRun(BaseModel):
    """Complete results from an evaluation run."""

    run_id: str
    timestamp: str
    suite: str
    results: list[Evaluation]
    metrics: "EvaluationMetrics"


class EvaluationMetrics(BaseModel):
    """Aggregated metrics for an evaluation run."""

    total_questions: int
    total_correct: int
    accuracy: float
