from typing import Literal

from pydantic import (
    BaseModel,
    Field,
)


class CollectionConfig(BaseModel):
    """Configuration for a question collection."""

    domain: str


class SuiteConfig(BaseModel):
    """Configuration for an evaluation suite."""

    integration: Literal["fai-local", "fai-http", "vercel-http"]
    collections: list[str] = Field(default_factory=list)
    evaluators: list[str] = Field(default_factory=list)
    rewrite_query: bool = False


class Question(BaseModel):
    """A question with ground truth for evaluation."""

    question: str
    ground_truth: str
    metadata: dict[str, str] = Field(default_factory=dict)
    criteria: dict[str, list[str]] | None = None


class Answer(BaseModel):
    """An answer generated by a model for a question."""

    question: str
    answer: str
    model: str
    metadata: dict[str, str] = Field(default_factory=dict)


class EvaluatorResult(BaseModel):
    """Result from a single evaluator stored in Evaluation."""

    is_passing: bool
    reason: str
    result_type: Literal["binary", "scaled", "numeric"]


class BinaryEvaluatorResult(EvaluatorResult):
    """Binary pass/fail result from an evaluator."""

    result_type: Literal["binary"] = "binary"


class ScaledEvaluatorResult(EvaluatorResult):
    """Scaled result (e.g., 1-3 or 1-5) from an evaluator."""

    result_type: Literal["scaled"] = "scaled"
    score: int
    min_score: int
    max_score: int
    passing_threshold: int


class NumericEvaluatorResult(EvaluatorResult):
    """Numeric result for statistical metrics from an evaluator."""

    result_type: Literal["numeric"] = "numeric"
    value: float


class Evaluation(BaseModel):
    """Result of evaluating an answer against ground truth."""

    question: str
    answer: str
    ground_truth: str
    is_correct: bool
    metadata: dict[str, str] = Field(default_factory=dict)
    evaluator_results: dict[str, BinaryEvaluatorResult | ScaledEvaluatorResult | NumericEvaluatorResult] = Field(
        default_factory=dict
    )


class EvaluationRun(BaseModel):
    """Complete results from an evaluation run."""

    run_id: str
    timestamp: str
    suite: str
    results: list[Evaluation]
    metrics: "EvaluationMetrics"


class EvaluationMetrics(BaseModel):
    """Aggregated metrics for an evaluation run."""

    total_questions: int
    total_correct: int
    accuracy: float
    evaluator_pass_rates: dict[str, float] = Field(default_factory=dict)
    evaluator_avg_scores: dict[str, float] = Field(default_factory=dict)
    evaluator_avg_values: dict[str, float] = Field(default_factory=dict)
    evaluator_std_values: dict[str, float] = Field(default_factory=dict)
