/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernFai from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "claude-4-sonnet-20250514",
 *         system_prompt: undefined,
 *         messages: [{
 *                 role: "role",
 *                 content: "content"
 *             }, {
 *                 role: "role",
 *                 content: "content"
 *             }]
 *     }
 */
export interface ChatCompletionRequest {
    /** The model to use for the chat completion. */
    model: FernFai.LanguageModel;
    /** The system prompt to use for the chat completion. */
    system_prompt?: string;
    /** The messages to use for the chat completion. */
    messages: FernFai.ChatTurn[];
}
