/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         code_id: "code_id"
 *     }
 */
export interface DeleteCodeRequest {
    /** The unique identifier of the code to delete */
    code_id: string;
}
