// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface PythonLibraryDocsIr {
    metadata: FdrLambda.libraryDocs.IrMetadata;
    rootModule: FdrLambda.libraryDocs.PythonModuleIr;
}
