// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../index.js";

export interface PythonModuleIr {
    name: string;
    path: string;
    docstring: FdrLambda.libraryDocs.DocstringIr | undefined;
    classes: FdrLambda.libraryDocs.PythonClassIr[];
    functions: FdrLambda.libraryDocs.PythonFunctionIr[];
    attributes: FdrLambda.libraryDocs.AttributeIr[];
    submodules: FdrLambda.libraryDocs.PythonModuleIr[];
}
