// This file was auto-generated by Fern from our API Definition.

export interface TypedDictFieldIr {
    name: string;
    type: string | undefined;
    description: string | undefined;
    required: boolean;
}
