/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../index.js";

export interface DictTemplate {
    imports: string[] | undefined;
    /**
     * We might not need this, but the idea here is to be able to omit if it's optional and undefined,
     * or default if omitted and required.
     */
    isOptional: boolean;
    /** Commonly the braces of a container like `{ $FERN_INPUT }`, but may even be something like `new Dict( $FERN_INPUT )` */
    containerTemplateString: string;
    delimiter: string;
    keyTemplate: FdrLambda.Template;
    valueTemplate: FdrLambda.Template;
    keyValueSeparator: string;
    templateInput: FdrLambda.PayloadInput | undefined;
}
