/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../index.js";

export type TemplateInput = FdrLambda.TemplateInput.Template | FdrLambda.TemplateInput.Payload;

export namespace TemplateInput {
    export interface Template {
        type: "template";
        value: FdrLambda.Template;
    }

    export interface Payload extends FdrLambda.PayloadInput {
        type: "payload";
    }
}
