/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../index.js";

export type Template =
    | FdrLambda.Template.Generic
    | FdrLambda.Template.Enum
    | FdrLambda.Template.DiscriminatedUnion
    | FdrLambda.Template.Union
    | FdrLambda.Template.UnionV2
    | FdrLambda.Template.Dict
    | FdrLambda.Template.Iterable;

export namespace Template {
    export interface Generic extends FdrLambda.GenericTemplate {
        type: "generic";
    }

    export interface Enum extends FdrLambda.EnumTemplate {
        type: "enum";
    }

    export interface DiscriminatedUnion extends FdrLambda.DiscriminatedUnionTemplate {
        type: "discriminatedUnion";
    }

    export interface Union extends FdrLambda.UnionTemplate {
        type: "union";
    }

    export interface UnionV2 extends FdrLambda.UnionTemplateV2 {
        type: "union_v2";
    }

    export interface Dict extends FdrLambda.DictTemplate {
        type: "dict";
    }

    export interface Iterable extends FdrLambda.IterableTemplate {
        type: "iterable";
    }
}
