/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../index.js";

export type VersionedSnippetTemplate = FdrLambda.VersionedSnippetTemplate.V1;

export namespace VersionedSnippetTemplate {
    export interface V1 extends FdrLambda.SnippetTemplate {
        type: "v1";
    }
}
