/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         github_repo: "github_repo"
 *     }
 */
export interface GetFernWriterInstallLinkRequest {
    /** The GitHub repository to install the Fern Writer for. Must have the `fern-api` bot installed. Must be in the format `owner/repo`. Example: `fern-api/docs` */
    github_repo: string;
}
