"use client";

import { assertNever } from "@fern-api/ui-core-utils";
import { FileIcon, Loader2Icon, RotateCcwIcon } from "lucide-react";
import { usePostHog } from "posthog-js/react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Auth0OrgName } from "@/app/services/auth0/types";
import { DashboardApiClient } from "@/app/services/dashboard-api/client";
import { captureEvent, PosthogEventName } from "@/components/posthog/events";
import { Button } from "@/components/ui/button";
import Card from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import type { DocsUrl } from "@/utils/types";
import { CoverTextOverride } from "./CoverTextOverride";
import { EmptyOverridesHint } from "./EmptyOverridesHint";
import { ExportRow } from "./ExportRow";
import type { DocsStructure } from "./infer-docs-structure";
import { OverrideRow } from "./OverrideRow";
import { usePdfExportTasks } from "./PdfExportTasksContext";
import { type FocusedTemplateField, PdfPreviewPanel, type PreviewTab } from "./PdfPreviewPanel";
import { SectionHeader } from "./SectionHeader";
import { TemplateOverride } from "./TemplateOverride";
import type { ExportOptionKey, ExportOptionKind, ExportOptionSectionId, ExportOptions } from "./types";

const OPTION_META: Record<
    ExportOptionKey,
    {
        label: string;
        description: string;
        section: ExportOptionSectionId;
        kind: ExportOptionKind;
    }
> = {
    coverTitle: {
        label: "Cover title",
        section: "cover",
        kind: "coverText",
        description: 'Shown as the main heading on the cover page. Set to "hide" to render nothing.'
    },
    coverSubtitle: {
        label: "Cover subtitle",
        section: "cover",
        kind: "coverText",
        description: 'Shown under the title on the cover page. Set to "hide" to render nothing.'
    },
    hideCoverFooter: {
        label: "Hide cover footer",
        section: "cover",
        kind: "boolean",
        description: 'Hides the "Generated by Fern" footer on the cover page.'
    },
    headerLeftTemplate: {
        label: "Header (left) template",
        section: "headersFooters",
        kind: "template",
        description: "Appears in the top-left of each content page."
    },
    headerRightTemplate: {
        label: "Header (right) template",
        section: "headersFooters",
        kind: "template",
        description: "Appears in the top-right of each content page."
    },
    footerLeftTemplate: {
        label: "Footer (left) template",
        section: "headersFooters",
        kind: "template",
        description: "Appears in the bottom-left of each content page."
    },
    footerRightTemplate: {
        label: "Footer (right) template",
        section: "headersFooters",
        kind: "template",
        description: "Appears in the bottom-right of each content page."
    }
};

function renderTemplate(
    template: string | undefined,
    sample: { pageIndex: number; totalPages: number }
): string | undefined {
    if (template == null) {
        return undefined;
    }
    return template
        .replaceAll("{pageIndex}", String(sample.pageIndex))
        .replaceAll("{totalPages}", String(sample.totalPages));
}

interface PdfExporterPageProps {
    docsUrl: DocsUrl;
    orgName: Auth0OrgName;
    defaultCoverTitle: string;
    docsStructure: DocsStructure;
    highlightExports?: boolean;
}

type OverrideState = Partial<Record<ExportOptionKey, true>>;

export default function PdfExporterPage({
    docsUrl,
    orgName,
    defaultCoverTitle,
    docsStructure,
    highlightExports
}: PdfExporterPageProps) {
    const posthog = usePostHog();

    const defaultOptions: ExportOptions = useMemo(
        () => ({
            coverTitle: defaultCoverTitle,
            coverSubtitle: "Complete documentation for developers, technical teams, and partners.",
            hideCoverFooter: undefined,
            headerLeftTemplate: undefined,
            headerRightTemplate: undefined,
            footerLeftTemplate: undefined,
            footerRightTemplate: undefined
        }),
        [defaultCoverTitle]
    );

    const [options, setOptions] = useState(defaultOptions);
    const [overrides, setOverrides] = useState<OverrideState>({});
    const [previewTab, setPreviewTab] = useState<PreviewTab>("cover");
    const [focusedTemplateField, setFocusedTemplateField] = useState<FocusedTemplateField | null>(null);
    const [isExporting, setIsExporting] = useState(false);

    const focusBlurTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
    const handleTemplateFocus = useCallback((field: FocusedTemplateField) => {
        clearTimeout(focusBlurTimerRef.current);
        setFocusedTemplateField(field);
    }, []);
    const handleTemplateBlur = useCallback(() => {
        focusBlurTimerRef.current = setTimeout(() => setFocusedTemplateField(null), 50);
    }, []);
    const [openingTaskId, setOpeningTaskId] = useState<string | null>(null);
    const [nowMs, setNowMs] = useState(() => Date.now());
    const [isExportsHighlighted, setIsExportsHighlighted] = useState(false);

    const products = docsStructure.type === "multiProduct" ? docsStructure.products : [];

    const defaultProductId = useMemo(() => (products.find((p) => p.isDefault) ?? products[0])?.productId, [products]);

    const [selectedProductId, setSelectedProductId] = useState<string | undefined>(defaultProductId);
    const [selectedVersionId, setSelectedVersionId] = useState<string | undefined>(undefined);

    const availableVersions = useMemo(() => {
        switch (docsStructure.type) {
            case "unversioned":
                return [];
            case "versioned":
                return docsStructure.versions;
            case "multiProduct":
                return (
                    (selectedProductId != null ? docsStructure.versionsByProduct[selectedProductId] : undefined) ?? []
                );
            default:
                assertNever(docsStructure);
        }
    }, [docsStructure, selectedProductId]);

    // Initialize / reset selected version when available versions change
    useEffect(() => {
        const defaultVersion = availableVersions.find((v) => v.isDefault) ?? availableVersions[0];
        setSelectedVersionId(defaultVersion?.versionId);
    }, [availableVersions]);

    const handleChangeProductId = useCallback((productId: string) => {
        setSelectedProductId(productId);
    }, []);

    const exportsCardRef = useRef<HTMLDivElement>(null);
    const tasksState = usePdfExportTasks();
    const tasksStatus = tasksState.status;
    const tasks = tasksState.tasks;
    const refreshTasks = tasksState.refresh;
    const upsertTask = tasksState.upsertTask;
    const tasksErrorMessage = tasksState.status === "error" ? tasksState.errorMessage : null;

    // Scroll to exports section and animate highlight
    useEffect(() => {
        if (!highlightExports) {
            setIsExportsHighlighted(false);
            return;
        }

        const scrollTimeout = setTimeout(() => {
            exportsCardRef.current?.scrollIntoView({ behavior: "smooth", block: "center" });
        }, 500);

        const showTimeout = setTimeout(() => {
            setIsExportsHighlighted(true);
        }, 1000);

        const hideTimeout = setTimeout(() => {
            setIsExportsHighlighted(false);
        }, 3000);

        return () => {
            clearTimeout(scrollTimeout);
            clearTimeout(showTimeout);
            clearTimeout(hideTimeout);
        };
    }, [highlightExports]);

    const sample = useMemo(() => ({ pageIndex: 3, totalPages: 12 }), []);

    const renderedHeadersFooters = useMemo(
        () => ({
            headerLeft: renderTemplate(options.headerLeftTemplate, sample),
            headerRight: renderTemplate(options.headerRightTemplate, sample),
            footerLeft: renderTemplate(options.footerLeftTemplate, sample),
            footerRight: renderTemplate(options.footerRightTemplate, sample)
        }),
        [
            options.headerLeftTemplate,
            options.headerRightTemplate,
            options.footerLeftTemplate,
            options.footerRightTemplate,
            sample
        ]
    );

    useEffect(() => {
        const hasRunning = tasks.some((t) => t.status === "RUNNING");
        if (!hasRunning) {
            return;
        }
        const id = window.setInterval(() => setNowMs(Date.now()), 1000);
        return () => window.clearInterval(id);
    }, [tasks]);

    const setOption = useCallback(<K extends ExportOptionKey>(key: K, value: ExportOptions[K]) => {
        setOptions((prev) => ({ ...prev, [key]: value }));
    }, []);

    const removeOverride = useCallback(
        (key: ExportOptionKey) => {
            setOverrides((prev) => {
                const next = { ...prev };
                delete next[key];
                return next;
            });
            switch (key) {
                case "coverTitle":
                case "coverSubtitle":
                    setOption(key, defaultOptions[key]);
                    return;
                case "hideCoverFooter":
                case "headerLeftTemplate":
                case "headerRightTemplate":
                case "footerLeftTemplate":
                case "footerRightTemplate":
                    setOption(key, undefined);
                    return;
                default:
                    assertNever(key);
            }
        },
        [setOption, defaultOptions]
    );

    const addOverride = useCallback(
        (key: ExportOptionKey) => {
            setOverrides((prev) => ({ ...prev, [key]: true }));
            setPreviewTab(OPTION_META[key].section === "headersFooters" ? "contentPage" : "cover");
            const kind = OPTION_META[key].kind;
            if (kind === "boolean") {
                setOption(key, false);
            } else if (kind === "template") {
                setOption(key, "");
            } else if (kind === "coverText") {
                // Initialize with the site's current default so the user
                // sees the real value and can edit or hide it from there.
                setOption(key, defaultOptions[key] ?? "");
            } else {
                assertNever(kind);
            }
        },
        [setOption, defaultOptions]
    );

    const hasAnyOverrides = useMemo(() => Object.keys(overrides).length > 0, [overrides]);

    const availableOverridesBySection = useMemo(() => {
        const present = new Set<ExportOptionKey>();
        for (const key of Object.keys(OPTION_META) as ExportOptionKey[]) {
            if (overrides[key]) {
                present.add(key);
            }
        }

        const entries = (Object.keys(OPTION_META) as ExportOptionKey[]).map((key) => ({
            key,
            ...OPTION_META[key],
            isPresent: present.has(key)
        }));

        const bySection: Record<ExportOptionSectionId, { key: ExportOptionKey; label: string }[]> = {
            cover: [],
            headersFooters: []
        };
        for (const e of entries) {
            if (!e.isPresent) {
                bySection[e.section].push({ key: e.key, label: e.label });
            }
        }
        return bySection;
    }, [overrides]);

    const handleExport = useCallback(async () => {
        captureEvent(posthog, PosthogEventName.PDF_EXPORT_CLICKED, { orgName, docsUrl });
        setIsExporting(true);
        try {
            const { task } = await DashboardApiClient.createPdfExportTask({
                orgName,
                docsUrl,
                productId: selectedProductId,
                versionId: selectedVersionId,
                options
            });
            upsertTask(task);
        } finally {
            setIsExporting(false);
        }
    }, [posthog, docsUrl, orgName, options, selectedProductId, selectedVersionId, upsertTask]);

    const handleOpen = useCallback(
        async (taskId: string) => {
            setOpeningTaskId(taskId);
            try {
                const { downloadUrl } = await DashboardApiClient.getPdfExportDownloadUrl({
                    orgName,
                    docsUrl,
                    taskId
                });
                window.open(downloadUrl, "_blank", "noopener,noreferrer");
            } finally {
                setOpeningTaskId((current) => (current === taskId ? null : current));
            }
        },
        [orgName, docsUrl]
    );

    return (
        <div className="flex w-full flex-col gap-6">
            <div>
                <h2 className="text-lg font-semibold">PDF Exporter</h2>
                <p className="mt-1 text-sm text-muted-foreground">
                    Configure a PDF export for this documentation site. Only the settings you override will be applied.
                </p>
            </div>

            {/* Two-column layout: Left (Settings + Exports) | Right (Cover Preview) */}
            <div className="flex flex-col gap-6 lg:flex-row lg:items-start">
                <div className="flex min-w-0 flex-1 flex-col gap-6">
                    <Card className="flex-col gap-4">
                        <div className="flex items-start justify-between gap-4">
                            <div>
                                <div className="text-base font-semibold text-gray-1100">Export settings</div>
                            </div>
                            {hasAnyOverrides && (
                                <Button
                                    variant="outline"
                                    size="sm"
                                    className="gap-2"
                                    onClick={() => {
                                        setOverrides({});
                                        setOptions(defaultOptions);
                                    }}
                                >
                                    <RotateCcwIcon className="size-4" />
                                    Reset to defaults
                                </Button>
                            )}
                        </div>

                        <div className="flex flex-col gap-5">
                            {products.length > 1 ? (
                                <div className="flex flex-col gap-3">
                                    <div>
                                        <div className="text-sm font-semibold text-gray-1100">Product</div>
                                        <div className="mt-1 text-sm text-muted-foreground">
                                            Choose which product’s documentation this PDF should include.
                                        </div>
                                    </div>

                                    <Select value={selectedProductId} onValueChange={handleChangeProductId}>
                                        <SelectTrigger className="w-full">
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {products.map((p) => (
                                                <SelectItem key={p.productId} value={p.productId}>
                                                    {p.title}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>
                            ) : null}

                            {availableVersions.length > 1 ? (
                                <div className="flex flex-col gap-3">
                                    <div>
                                        <div className="text-sm font-semibold text-gray-1100">Version</div>
                                        <div className="mt-1 text-sm text-muted-foreground">
                                            Choose which version this PDF should include.
                                        </div>
                                    </div>

                                    <Select value={selectedVersionId} onValueChange={(v) => setSelectedVersionId(v)}>
                                        <SelectTrigger className="w-full">
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {availableVersions.map((v) => (
                                                <SelectItem key={v.versionId} value={v.versionId}>
                                                    {v.title}
                                                </SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>
                            ) : null}

                            <div className="flex flex-col gap-3">
                                <SectionHeader
                                    title="Cover"
                                    description="Customize the PDF cover. If you don't override an option, we'll use the site's default."
                                    addOverrideItems={availableOverridesBySection.cover}
                                    onAddOverride={addOverride}
                                />

                                <div className="flex flex-col gap-3" onFocus={() => setPreviewTab("cover")}>
                                    {overrides.coverTitle && (
                                        <OverrideRow
                                            label={OPTION_META.coverTitle.label}
                                            description={OPTION_META.coverTitle.description}
                                            onRemove={() => removeOverride("coverTitle")}
                                        >
                                            <CoverTextOverride
                                                value={options.coverTitle ?? ""}
                                                onChange={(next) => setOption("coverTitle", next)}
                                            />
                                        </OverrideRow>
                                    )}

                                    {overrides.coverSubtitle && (
                                        <OverrideRow
                                            label={OPTION_META.coverSubtitle.label}
                                            description={OPTION_META.coverSubtitle.description}
                                            onRemove={() => removeOverride("coverSubtitle")}
                                        >
                                            <CoverTextOverride
                                                value={options.coverSubtitle ?? ""}
                                                onChange={(next) => setOption("coverSubtitle", next)}
                                            />
                                        </OverrideRow>
                                    )}

                                    {overrides.hideCoverFooter && (
                                        <OverrideRow
                                            label={OPTION_META.hideCoverFooter.label}
                                            description={OPTION_META.hideCoverFooter.description}
                                            onRemove={() => removeOverride("hideCoverFooter")}
                                        >
                                            <div className="flex items-center justify-between gap-4">
                                                <div className="text-sm text-gray-1100">Hide "Generated by Fern"</div>
                                                <Switch
                                                    checked={Boolean(options.hideCoverFooter)}
                                                    onCheckedChange={(checked) => setOption("hideCoverFooter", checked)}
                                                />
                                            </div>
                                        </OverrideRow>
                                    )}

                                    {overrides.coverTitle !== true &&
                                        overrides.coverSubtitle !== true &&
                                        overrides.hideCoverFooter !== true && <EmptyOverridesHint />}
                                </div>
                            </div>

                            <div className="flex flex-col gap-3">
                                <SectionHeader
                                    title="Headers & footers"
                                    description={
                                        <>
                                            Stamp a template onto each content page. Supports{" "}
                                            <code className="rounded bg-muted px-1 py-0.5 text-xs">
                                                {"{pageIndex}"}
                                            </code>{" "}
                                            and{" "}
                                            <code className="rounded bg-muted px-1 py-0.5 text-xs">
                                                {"{totalPages}"}
                                            </code>{" "}
                                            placeholders.
                                        </>
                                    }
                                    addOverrideItems={availableOverridesBySection.headersFooters}
                                    onAddOverride={addOverride}
                                />

                                <div className="flex flex-col gap-3" onFocus={() => setPreviewTab("contentPage")}>
                                    {overrides.headerLeftTemplate && (
                                        <OverrideRow
                                            label={OPTION_META.headerLeftTemplate.label}
                                            description={OPTION_META.headerLeftTemplate.description}
                                            onRemove={() => removeOverride("headerLeftTemplate")}
                                        >
                                            <TemplateOverride
                                                value={options.headerLeftTemplate}
                                                onChange={(next) => setOption("headerLeftTemplate", next)}
                                                onFocus={() => handleTemplateFocus("headerLeft")}
                                                onBlur={handleTemplateBlur}
                                            />
                                        </OverrideRow>
                                    )}

                                    {overrides.headerRightTemplate && (
                                        <OverrideRow
                                            label={OPTION_META.headerRightTemplate.label}
                                            description={OPTION_META.headerRightTemplate.description}
                                            onRemove={() => removeOverride("headerRightTemplate")}
                                        >
                                            <TemplateOverride
                                                value={options.headerRightTemplate}
                                                onChange={(next) => setOption("headerRightTemplate", next)}
                                                onFocus={() => handleTemplateFocus("headerRight")}
                                                onBlur={handleTemplateBlur}
                                            />
                                        </OverrideRow>
                                    )}

                                    {overrides.footerLeftTemplate && (
                                        <OverrideRow
                                            label={OPTION_META.footerLeftTemplate.label}
                                            description={OPTION_META.footerLeftTemplate.description}
                                            onRemove={() => removeOverride("footerLeftTemplate")}
                                        >
                                            <TemplateOverride
                                                value={options.footerLeftTemplate}
                                                onChange={(next) => setOption("footerLeftTemplate", next)}
                                                onFocus={() => handleTemplateFocus("footerLeft")}
                                                onBlur={handleTemplateBlur}
                                            />
                                        </OverrideRow>
                                    )}

                                    {overrides.footerRightTemplate && (
                                        <OverrideRow
                                            label={OPTION_META.footerRightTemplate.label}
                                            description={OPTION_META.footerRightTemplate.description}
                                            onRemove={() => removeOverride("footerRightTemplate")}
                                        >
                                            <TemplateOverride
                                                value={options.footerRightTemplate}
                                                onChange={(next) => setOption("footerRightTemplate", next)}
                                                onFocus={() => handleTemplateFocus("footerRight")}
                                                onBlur={handleTemplateBlur}
                                            />
                                        </OverrideRow>
                                    )}

                                    {overrides.headerLeftTemplate !== true &&
                                        overrides.headerRightTemplate !== true &&
                                        overrides.footerLeftTemplate !== true &&
                                        overrides.footerRightTemplate !== true && <EmptyOverridesHint />}
                                </div>
                            </div>
                        </div>
                    </Card>

                    {/* Exports section in left column */}
                    <div ref={exportsCardRef}>
                        <Card
                            className="flex-col gap-4"
                            style={{
                                borderColor: isExportsHighlighted ? "var(--green-800)" : undefined,
                                transition: "border-color 500ms ease-in-out"
                            }}
                        >
                            <div className="flex items-start justify-between gap-4">
                                <div>
                                    <div className="text-base font-semibold text-gray-1100">Exports</div>
                                    <div className="mt-1 text-sm text-muted-foreground">
                                        Exports run asynchronously and may take a few minutes for large documentation
                                        sites.
                                    </div>
                                </div>
                                <Button
                                    onClick={() => void handleExport()}
                                    disabled={
                                        isExporting ||
                                        (products.length > 0 && selectedProductId == null) ||
                                        (availableVersions.length > 0 && selectedVersionId == null)
                                    }
                                    className="gap-2"
                                >
                                    {isExporting ? (
                                        <Loader2Icon className="size-4 animate-spin" />
                                    ) : (
                                        <FileIcon className="size-4" />
                                    )}
                                    Export as PDF
                                </Button>
                            </div>

                            {tasksStatus === "error" ? (
                                <div className="rounded-xl border border-border bg-muted/30 p-4">
                                    <div className="text-sm font-medium text-gray-1100">Failed to load exports</div>
                                    <div className="mt-1 text-xs text-muted-foreground">
                                        {tasksErrorMessage ?? "Please try again."}
                                    </div>
                                    <div className="mt-3">
                                        <Button size="sm" variant="outline" onClick={() => void refreshTasks()}>
                                            Retry
                                        </Button>
                                    </div>
                                </div>
                            ) : tasksStatus === "loading" && tasks.length === 0 ? (
                                <div className="rounded-xl border border-border bg-muted/30 p-4">
                                    <div className="flex flex-col gap-3">
                                        <Skeleton className="h-5 w-40" />
                                        <Skeleton className="h-10 w-full" />
                                        <Skeleton className="h-10 w-full" />
                                    </div>
                                </div>
                            ) : tasksStatus === "success" && tasks.length === 0 ? (
                                <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border bg-muted/30 py-10 text-center">
                                    <FileIcon className="mb-3 size-10 text-muted-foreground/50" />
                                    <div className="text-sm font-medium text-gray-1100">No exports yet</div>
                                    <div className="mt-1 text-xs text-muted-foreground">
                                        Click "Export as PDF" to generate your first export.
                                    </div>
                                </div>
                            ) : (
                                <div className="max-h-72 divide-y divide-border overflow-y-auto rounded-xl border border-border">
                                    {tasks.map((task) => (
                                        <ExportRow
                                            key={task.id}
                                            task={task}
                                            nowMs={nowMs}
                                            onOpen={handleOpen}
                                            isOpening={openingTaskId === String(task.id)}
                                            requesterEmail={task.notifyEmails?.[0]}
                                        />
                                    ))}
                                </div>
                            )}
                        </Card>
                    </div>
                </div>

                <div className="shrink-0">
                    <PdfPreviewPanel
                        docsUrl={docsUrl}
                        orgName={orgName}
                        options={options}
                        activeTab={previewTab}
                        onTabChange={setPreviewTab}
                        headerLeft={renderedHeadersFooters.headerLeft}
                        headerRight={renderedHeadersFooters.headerRight}
                        footerLeft={renderedHeadersFooters.footerLeft}
                        footerRight={renderedHeadersFooters.footerRight}
                        focusedTemplateField={focusedTemplateField}
                    />
                </div>
            </div>
        </div>
    );
}
