// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export type BytesValue = FdrLambda.api.v1.read.BytesValue.Base64;

export namespace BytesValue {
    export interface Base64 {
        type: "base64";
        value: string;
    }
}
