/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface CodeExamples {
    nodeAxios?: string;
    pythonSdk?: FdrLambda.api.v1.read.PythonSnippet;
    typescriptSdk?: FdrLambda.api.v1.read.TypescriptSnippet;
    goSdk?: FdrLambda.api.v1.read.GoSnippet;
    rubySdk?: FdrLambda.api.v1.read.RubySnippet;
    csharpSdk?: FdrLambda.api.v1.read.CsharpSnippet;
}
