/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface CodeExamples {
    nodeAxios: string | undefined;
    pythonSdk: FdrLambda.api.v1.read.PythonSnippet | undefined;
    typescriptSdk: FdrLambda.api.v1.read.TypescriptSnippet | undefined;
    goSdk: FdrLambda.api.v1.read.GoSnippet | undefined;
    rubySdk: FdrLambda.api.v1.read.RubySnippet | undefined;
    csharpSdk: FdrLambda.api.v1.read.CsharpSnippet | undefined;
}
