/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

/**
 * Hand-written code samples
 */
export interface CustomCodeSample extends FdrLambda.api.v1.WithDescription {
    language: FdrLambda.api.v1.read.Language;
    code: string;
    name: string | undefined;
    install: string | undefined;
}
