/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export type EndpointPathPart =
    | FdrLambda.api.v1.read.EndpointPathPart.Literal
    | FdrLambda.api.v1.read.EndpointPathPart.PathParameter;

export namespace EndpointPathPart {
    export interface Literal {
        type: "literal";
        value: string;
    }

    export interface PathParameter {
        type: "pathParameter";
        value: FdrLambda.PropertyKey;
    }
}
