// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface EndpointSnippetTemplates {
    typescript: FdrLambda.VersionedSnippetTemplate | undefined;
    python: FdrLambda.VersionedSnippetTemplate | undefined;
}
