/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface EndpointPath {
    parts: FdrLambda.api.v1.read.EndpointPathPart[];
    pathParameters: FdrLambda.api.v1.read.PathParameter[];
}
