/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface ErrorExample extends FdrLambda.api.v1.WithDescription {
    name?: string;
    responseBody: FdrLambda.api.v1.read.ExampleErrorResponse;
}
