/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export type ExampleErrorResponse = FdrLambda.api.v1.read.ExampleErrorResponse.Json;

export namespace ExampleErrorResponse {
    export interface Json {
        type: "json";
        value?: unknown;
    }
}
