// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export type ExampleEndpointResponse =
    | FdrLambda.api.v1.read.ExampleEndpointResponse.Json
    | FdrLambda.api.v1.read.ExampleEndpointResponse.Filename
    | FdrLambda.api.v1.read.ExampleEndpointResponse.Stream
    | FdrLambda.api.v1.read.ExampleEndpointResponse.Sse;

export namespace ExampleEndpointResponse {
    export interface Json {
        type: "json";
        value: unknown;
    }

    export interface Filename {
        type: "filename";
        value: string;
    }

    export interface Stream {
        type: "stream";
        value: unknown[];
    }

    export interface Sse {
        type: "sse";
        value: FdrLambda.api.v1.read.ExampleServerSentEvent[];
    }
}
