/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export type ExampleEndpointRequest =
    | FdrLambda.api.v1.read.ExampleEndpointRequest.Json
    | FdrLambda.api.v1.read.ExampleEndpointRequest.Form
    | FdrLambda.api.v1.read.ExampleEndpointRequest.Bytes;

export namespace ExampleEndpointRequest {
    export interface Json {
        type: "json";
        value?: unknown;
    }

    export interface Form {
        type: "form";
        value: Record<string, FdrLambda.api.v1.read.FormValue>;
    }

    export interface Bytes {
        type: "bytes";
        value: FdrLambda.api.v1.read.BytesValue;
    }
}
