/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export type FormValue =
    | FdrLambda.api.v1.read.FormValue.Json
    | FdrLambda.api.v1.read.FormValue.Filename
    | FdrLambda.api.v1.read.FormValue.Filenames
    | FdrLambda.api.v1.read.FormValue.FilenameWithData
    | FdrLambda.api.v1.read.FormValue.FilenamesWithData
    | FdrLambda.api.v1.read.FormValue.Exploded;

export namespace FormValue {
    export interface Json {
        type: "json";
        value: unknown;
    }

    export interface Filename {
        type: "filename";
        value: string;
    }

    export interface Filenames {
        type: "filenames";
        value: string[];
    }

    export interface FilenameWithData extends FdrLambda.api.v1.read.FilenameWithData {
        type: "filenameWithData";
    }

    export interface FilenamesWithData {
        type: "filenamesWithData";
        value: FdrLambda.api.v1.read.FilenameWithData[];
    }

    export interface Exploded {
        type: "exploded";
        value: unknown[];
    }
}
