/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export type HttpRequestBodyShape =
    | FdrLambda.api.v1.read.HttpRequestBodyShape.Object_
    | FdrLambda.api.v1.read.HttpRequestBodyShape.Reference
    | FdrLambda.api.v1.read.HttpRequestBodyShape.Bytes
    | FdrLambda.api.v1.read.HttpRequestBodyShape.FormData
    /**
     * `fileUpload` is optional only to be backwards compatible. It should be required. */
    | FdrLambda.api.v1.read.HttpRequestBodyShape.FileUpload;

export namespace HttpRequestBodyShape {
    export interface Object_ extends FdrLambda.api.v1.read.ObjectType {
        type: "object";
    }

    export interface Reference {
        type: "reference";
        value: FdrLambda.api.v1.read.TypeReference;
    }

    export interface Bytes extends FdrLambda.api.v1.read.BytesRequest {
        type: "bytes";
    }

    export interface FormData extends FdrLambda.api.v1.read.FormDataRequest {
        type: "formData";
    }

    export interface FileUpload {
        type: "fileUpload";
        value?: FdrLambda.api.v1.read.FormDataRequest;
    }
}
