// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface HttpResponsesV2 {
    responses: FdrLambda.api.v1.read.HttpResponse[] | undefined;
}
