/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface HttpResponse extends FdrLambda.api.v1.WithDescription {
    type: FdrLambda.api.v1.read.HttpResponseBodyShape;
    /** Defaults to 200 */
    statusCode?: number;
}
