/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface HttpRequest extends FdrLambda.api.v1.WithDescription {
    contentType: string;
    type: FdrLambda.api.v1.read.HttpRequestBodyShape;
}
