/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface HttpRequestsV2 {
    requests?: FdrLambda.api.v1.read.HttpRequest[];
}
