/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export type JsonBodyShape = FdrLambda.api.v1.read.JsonBodyShape.Object_ | FdrLambda.api.v1.read.JsonBodyShape.Reference;

export namespace JsonBodyShape {
    export interface Object_ extends FdrLambda.api.v1.read.ObjectType {
        type: "object";
    }

    export interface Reference {
        type: "reference";
        value: FdrLambda.api.v1.read.TypeReference;
    }
}
