/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface PathParameter extends FdrLambda.api.v1.WithDescription, FdrLambda.api.v1.WithAvailability {
    key: FdrLambda.PropertyKey;
    type: FdrLambda.api.v1.read.TypeReference;
}
