/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface StreamConditionResponse {
    response: FdrLambda.api.v1.read.NonStreamResponse;
    streamResponse: FdrLambda.api.v1.read.StreamResponse;
    streamCondition: FdrLambda.api.v1.read.StreamCondition;
}
