/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernAI from "../../../../index.js";

/**
 * @example
 *     {
 *         entries: [{
 *                 parent_id: "parent_id",
 *                 content_hash: "content_hash",
 *                 chunk_count: 1
 *             }]
 *     }
 */
export interface BatchUpsertContentHashesRequest {
    entries: FernAI.ContentHashUpsertEntry[];
}
