/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface BatchGetContentHashesRequest {
    parent_ids?: string[];
    /** The number of content hashes to return */
    limit?: number;
    /** The offset to start from */
    offset?: number;
}
