/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         parent_ids: ["parent_ids"]
 *     }
 */
export interface DeleteContentHashesRequest {
    parent_ids: string[];
}
