/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface WebhookDefinition
    extends FdrLambda.api.latest.WithDescription,
        FdrLambda.api.latest.WithAvailability,
        FdrLambda.api.latest.WithNamespace {
    id: FdrLambda.WebhookId;
    displayName?: string;
    operationId?: string;
    method: FdrLambda.api.latest.WebhookHttpMethod;
    path: string[];
    headers?: FdrLambda.api.latest.ObjectProperty[];
    payloads?: FdrLambda.api.latest.WebhookPayload[];
    examples?: FdrLambda.api.v1.read.ExampleWebhookPayload[];
}
