// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface WebhookDefinition
    extends FdrLambda.api.latest.WithDescription,
        FdrLambda.api.latest.WithAvailability,
        FdrLambda.api.latest.WithNamespace {
    id: FdrLambda.WebhookId;
    displayName: string | undefined;
    operationId: string | undefined;
    method: FdrLambda.api.latest.WebhookHttpMethod;
    path: string[];
    headers: FdrLambda.api.latest.ObjectProperty[] | undefined;
    payloads: FdrLambda.api.latest.WebhookPayload[] | undefined;
    responses: FdrLambda.api.latest.HttpResponse[] | undefined;
    examples: FdrLambda.api.v1.read.ExampleWebhookPayload[] | undefined;
}
