/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface WebhookPayload extends FdrLambda.api.latest.WithDescription {
    shape: FdrLambda.api.latest.TypeShape;
}
