[loggers]
keys=root

[handlers]
keys=console

[formatters]
keys=simple

[logger_root]
level=WARNING
handlers=console

[handler_console]
class=StreamHandler
level=WARNING
formatter=simple
args=(sys.stdout,)

[formatter_simple]
format=%(levelname)s: %(message)s
