/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../../../index.js";

export interface ExampleWebSocketSession extends FdrLambda.api.v1.WithDescription {
    name?: string;
    path: string;
    pathParameters: Record<FdrLambda.PropertyKey, unknown>;
    queryParameters: Record<string, unknown>;
    headers: Record<string, unknown>;
    messages: FdrLambda.api.v1.read.ExampleWebSocketMessage[];
}
