/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface WebSocketChannel extends FdrLambda.api.v1.WithDescription, FdrLambda.api.v1.WithAvailability {
    urlSlug: string;
    id: FdrLambda.WebSocketId;
    auth: boolean;
    name: string | undefined;
    defaultEnvironment: FdrLambda.EnvironmentId | undefined;
    environments: FdrLambda.api.v1.Environment[];
    path: FdrLambda.api.v1.read.EndpointPath;
    headers: FdrLambda.api.v1.read.Header[];
    queryParameters: FdrLambda.api.v1.read.QueryParameter[];
    /** The messages that can be sent and received on this channel */
    messages: FdrLambda.api.v1.read.WebSocketMessage[];
    examples: FdrLambda.api.v1.read.ExampleWebSocketSession[];
}
