/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export type WebSocketMessageBodyShape =
    | FdrLambda.api.v1.read.WebSocketMessageBodyShape.Object_
    | FdrLambda.api.v1.read.WebSocketMessageBodyShape.Reference;

export namespace WebSocketMessageBodyShape {
    export interface Object_ extends FdrLambda.api.v1.read.ObjectType {
        type: "object";
    }

    export interface Reference {
        type: "reference";
        value: FdrLambda.api.v1.read.TypeReference;
    }
}
