/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../../../index.js";

export interface WebSocketMessage extends FdrLambda.api.v1.WithDescription, FdrLambda.api.v1.WithAvailability {
    type: FdrLambda.api.v1.WebSocketMessageId;
    displayName: string | undefined;
    origin: FdrLambda.api.v1.WebSocketMessageOrigin;
    body: FdrLambda.api.v1.read.WebSocketMessageBodyShape;
}
