/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as FernAI from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace ContentHash {
    export interface Options {
        environment?: core.Supplier<environments.FernAIEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class ContentHash {
    protected readonly _options: ContentHash.Options;

    constructor(_options: ContentHash.Options = {}) {
        this._options = _options;
    }

    /**
     * Get content hashes for multiple parent_ids.
     * If parent_ids is empty, returns all content hashes for the domain.
     *
     * @param {string} domain
     * @param {FernAI.BatchGetContentHashesRequest} request
     * @param {ContentHash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.contentHash.batchGetContentHashes("domain")
     */
    public batchGetContentHashes(
        domain: string,
        request: FernAI.BatchGetContentHashesRequest = {},
        requestOptions?: ContentHash.RequestOptions,
    ): core.HttpResponsePromise<FernAI.BatchGetContentHashesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__batchGetContentHashes(domain, request, requestOptions));
    }

    private async __batchGetContentHashes(
        domain: string,
        request: FernAI.BatchGetContentHashesRequest = {},
        requestOptions?: ContentHash.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.BatchGetContentHashesResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `content-hash/${encodeURIComponent(domain)}/batch-get`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.BatchGetContentHashesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling POST /content-hash/{domain}/batch-get.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Upsert content hashes for multiple parent_ids.
     * Creates new records or updates existing ones.
     *
     * @param {string} domain
     * @param {FernAI.BatchUpsertContentHashesRequest} request
     * @param {ContentHash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.contentHash.batchUpsertContentHashes("domain", {
     *         entries: [{
     *                 parent_id: "parent_id",
     *                 content_hash: "content_hash",
     *                 chunk_count: 1
     *             }]
     *     })
     */
    public batchUpsertContentHashes(
        domain: string,
        request: FernAI.BatchUpsertContentHashesRequest,
        requestOptions?: ContentHash.RequestOptions,
    ): core.HttpResponsePromise<FernAI.BatchUpsertContentHashesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__batchUpsertContentHashes(domain, request, requestOptions));
    }

    private async __batchUpsertContentHashes(
        domain: string,
        request: FernAI.BatchUpsertContentHashesRequest,
        requestOptions?: ContentHash.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.BatchUpsertContentHashesResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `content-hash/${encodeURIComponent(domain)}/batch-upsert`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as FernAI.BatchUpsertContentHashesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling POST /content-hash/{domain}/batch-upsert.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete content hashes for multiple parent_ids.
     *
     * @param {string} domain
     * @param {FernAI.DeleteContentHashesRequest} request
     * @param {ContentHash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.contentHash.deleteContentHashes("domain", {
     *         parent_ids: ["parent_ids"]
     *     })
     */
    public deleteContentHashes(
        domain: string,
        request: FernAI.DeleteContentHashesRequest,
        requestOptions?: ContentHash.RequestOptions,
    ): core.HttpResponsePromise<FernAI.DeleteContentHashesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteContentHashes(domain, request, requestOptions));
    }

    private async __deleteContentHashes(
        domain: string,
        request: FernAI.DeleteContentHashesRequest,
        requestOptions?: ContentHash.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.DeleteContentHashesResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `content-hash/${encodeURIComponent(domain)}/delete`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.DeleteContentHashesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling DELETE /content-hash/{domain}/delete.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete all content hashes for a domain.
     * Used when forcing a full reindex.
     *
     * @param {string} domain
     * @param {ContentHash.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernAI.UnprocessableEntityError}
     *
     * @example
     *     await client.contentHash.deleteAllContentHashes("domain")
     */
    public deleteAllContentHashes(
        domain: string,
        requestOptions?: ContentHash.RequestOptions,
    ): core.HttpResponsePromise<FernAI.DeleteContentHashesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAllContentHashes(domain, requestOptions));
    }

    private async __deleteAllContentHashes(
        domain: string,
        requestOptions?: ContentHash.RequestOptions,
    ): Promise<core.WithRawResponse<FernAI.DeleteContentHashesResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernAIEnvironment.Production,
                `content-hash/${encodeURIComponent(domain)}/delete-all`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as FernAI.DeleteContentHashesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new FernAI.UnprocessableEntityError(
                        _response.error.body as FernAI.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernAIError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernAIError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernAITimeoutError(
                    "Timeout exceeded when calling DELETE /content-hash/{domain}/delete-all.",
                );
            case "unknown":
                throw new errors.FernAIError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
