// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface CodeSnippet extends FdrLambda.api.latest.WithDescription {
    name: string | undefined;
    language: FdrLambda.api.latest.Language;
    install: string | undefined;
    code: string;
    generated: boolean;
}
