/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface EndpointDefinition
    extends FdrLambda.api.latest.WithDescription,
        FdrLambda.api.latest.WithAvailability,
        FdrLambda.api.latest.WithNamespace {
    id: FdrLambda.EndpointId;
    method: FdrLambda.HttpMethod;
    path: FdrLambda.api.latest.PathPart[];
    displayName: string | undefined;
    operationId: string | undefined;
    auth: FdrLambda.AuthSchemeId[] | undefined;
    defaultEnvironment: FdrLambda.EnvironmentId | undefined;
    environments: FdrLambda.api.latest.Environment[] | undefined;
    pathParameters: FdrLambda.api.latest.ObjectProperty[] | undefined;
    queryParameters: FdrLambda.api.latest.ObjectProperty[] | undefined;
    requestHeaders: FdrLambda.api.latest.ObjectProperty[] | undefined;
    responseHeaders: FdrLambda.api.latest.ObjectProperty[] | undefined;
    requests: FdrLambda.api.latest.HttpRequest[] | undefined;
    responses: FdrLambda.api.latest.HttpResponse[] | undefined;
    errors: FdrLambda.api.latest.ErrorResponse[] | undefined;
    examples: FdrLambda.api.latest.ExampleEndpointCall[] | undefined;
    snippetTemplates: FdrLambda.api.latest.EndpointSnippetTemplates | undefined;
    protocol: FdrLambda.api.latest.Protocol | undefined;
}
