/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface ErrorResponse extends FdrLambda.api.latest.WithDescription, FdrLambda.api.latest.WithAvailability {
    shape: FdrLambda.api.latest.TypeShape | undefined;
    statusCode: number;
    name: string;
    examples: FdrLambda.api.latest.ErrorExample[] | undefined;
}
