// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface ErrorExample extends FdrLambda.api.latest.WithDescription {
    name: string | undefined;
    responseBody: FdrLambda.api.latest.ExampleErrorResponse;
}
