/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface ErrorExample extends FdrLambda.api.latest.WithDescription {
    name?: string;
    responseBody: FdrLambda.api.latest.ExampleErrorResponse;
}
