/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface ExampleEndpointCall extends FdrLambda.api.latest.WithDescription {
    path: string;
    responseStatusCode: number;
    name?: string;
    pathParameters?: Record<FdrLambda.PropertyKey, unknown>;
    queryParameters?: Record<FdrLambda.PropertyKey, unknown>;
    headers?: Record<FdrLambda.PropertyKey, unknown>;
    requestBody?: FdrLambda.api.latest.ExampleEndpointRequest;
    responseBody?: FdrLambda.api.latest.ExampleEndpointResponse;
    snippets?: Record<FdrLambda.api.latest.Language, FdrLambda.api.latest.CodeSnippet[]>;
}
