// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface ExampleEndpointCall extends FdrLambda.api.latest.WithDescription {
    path: string;
    responseStatusCode: number;
    name: string | undefined;
    pathParameters: Record<FdrLambda.PropertyKey, unknown> | undefined;
    queryParameters: Record<FdrLambda.PropertyKey, unknown> | undefined;
    headers: Record<FdrLambda.PropertyKey, unknown> | undefined;
    requestBody: FdrLambda.api.latest.ExampleEndpointRequest | undefined;
    responseBody: FdrLambda.api.latest.ExampleEndpointResponse | undefined;
    snippets: Record<FdrLambda.api.latest.Language, FdrLambda.api.latest.CodeSnippet[]> | undefined;
}
