/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface GrpcProtocol {
    methodName: string;
    methodType?: FdrLambda.GrpcMethod;
}
