// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface HttpRequest extends FdrLambda.api.latest.WithDescription {
    contentType: string | undefined;
    body: FdrLambda.api.latest.HttpRequestBodyShape;
}
