/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export type HttpResponseBodyShape =
    | FdrLambda.api.latest.HttpResponseBodyShape.Empty
    | FdrLambda.api.latest.HttpResponseBodyShape.Object_
    | FdrLambda.api.latest.HttpResponseBodyShape.Alias
    | FdrLambda.api.latest.HttpResponseBodyShape.FileDownload
    | FdrLambda.api.latest.HttpResponseBodyShape.StreamingText
    | FdrLambda.api.latest.HttpResponseBodyShape.Stream;

export namespace HttpResponseBodyShape {
    export interface Empty {
        type: "empty";
    }

    export interface Object_ extends FdrLambda.api.latest.ObjectType {
        type: "object";
    }

    export interface Alias {
        type: "alias";
        value: FdrLambda.api.latest.TypeReference;
    }

    export interface FileDownload extends FdrLambda.api.latest.FileDownloadResponseBodyShape {
        type: "fileDownload";
    }

    export interface StreamingText {
        type: "streamingText";
    }

    export interface Stream extends FdrLambda.api.latest.StreamResponse {
        type: "stream";
    }
}
