/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export type HttpRequestBodyShape =
    | FdrLambda.api.latest.HttpRequestBodyShape.Object_
    | FdrLambda.api.latest.HttpRequestBodyShape.Alias
    | FdrLambda.api.latest.HttpRequestBodyShape.Bytes
    | FdrLambda.api.latest.HttpRequestBodyShape.FormData;

export namespace HttpRequestBodyShape {
    export interface Object_ extends FdrLambda.api.latest.ObjectType {
        type: "object";
    }

    export interface Alias {
        type: "alias";
        value: FdrLambda.api.latest.TypeReference;
    }

    export interface Bytes extends FdrLambda.api.v1.read.BytesRequest {
        type: "bytes";
    }

    export interface FormData extends FdrLambda.api.latest.FormDataRequest {
        type: "formData";
    }
}
