/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface StreamResponse {
    /**
     * The terminator for each message. For example, for OpenAPI
     * the terminator is [DATA].
     */
    terminator: string | undefined;
    shape: FdrLambda.api.latest.TypeShape;
}
