import type { ConsoleLogFormat, LogLevel } from "../util/logger";

export interface DocsPdfExporterConfig {
    /**
     * Maximum number of content pages to render concurrently during generation.
     * This bounds browser page creation and prevents thrashing on large sites.
     *
     * @defaultValue 5
     */
    maxRenderConcurrency: number;

    /**
     * Maximum number of retries for rendering an individual page to PDF (cover/TOC/content).
     *
     * Retries are useful for transient failures (timeouts, navigation flakiness,
     * Chromium hiccups). Total attempts = 1 + maxRenderRetries.
     *
     * @defaultValue 2
     */
    maxRenderRetries: number;

    /**
     * Maximum time to wait for any printed page (cover/TOC/content) to load and become idle.
     *
     * @defaultValue 60
     */
    renderTimeoutSeconds: number;

    /**
     * Whether to continue generating the PDF when a content page fails to render after all retries.
     *
     * - When `false` (default), any content page render failure aborts the entire run and throws.
     * - When `true`, failed pages are skipped and their errors collected in the result.
     *   The PDF is still produced with the remaining pages.
     *
     * This only affects content page rendering. Failures in cover, TOC, merge, etc. always throw.
     *
     * @defaultValue false
     */
    continueOnPageError: boolean;

    /**
     * Logging verbosity.
     *
     * - `silent`: no logs
     * - `error`: only failures
     * - `warn`: warnings + errors
     * - `info`: high-level progress
     * - `debug`: verbose per-step and per-page timing
     *
     * @defaultValue "info"
     */
    logLevel: LogLevel;

    /**
     * Output format used when logging to console (only applies to the default logger).
     *
     * @defaultValue "pretty"
     */
    logFormat: ConsoleLogFormat;

    /**
     * Authentication token sent as `FERN_TOKEN` header to protected print routes.
     * Required when accessing authenticated documentation sites.
     *
     * This should be the Fern admin token.
     */
    authToken?: string;
}

export interface DocsPdfGenerateOptions {
    /**
     * Cover title (center heading).
     *
     * - omit / `undefined`: use the site's configured default
     * - `null`: render nothing (hide)
     * - string: render the provided string (after trimming)
     */
    coverTitle?: string | null;

    /**
     * Cover subtitle (center subheading).
     *
     * - omit / `undefined`: use the default subtitle
     * - `null`: render nothing (hide)
     * - string: render the provided string (after trimming)
     */
    coverSubtitle?: string | null;

    /**
     * Hide the "Generated by Fern" footer on the cover page.
     *
     * @defaultValue false
     */
    hideCoverFooter?: boolean;

    /**
     * Header (top-left) template for content pages.
     * Supports placeholders: `{pageIndex}`, `{totalPages}`.
     */
    headerLeftTemplate?: string;

    /**
     * Header (top-right) template for content pages.
     * Supports placeholders: `{pageIndex}`, `{totalPages}`.
     */
    headerRightTemplate?: string;

    /**
     * Footer (bottom-left) template for content pages.
     * Supports placeholders: `{pageIndex}`, `{totalPages}`.
     */
    footerLeftTemplate?: string;

    /**
     * Footer (bottom-right) template for content pages.
     * Supports placeholders: `{pageIndex}`, `{totalPages}`.
     */
    footerRightTemplate?: string;
}

/**
 * Result of generating a cover PDF.
 */
export interface CoverPdfGenerateResult {
    /**
     * The generated PDF bytes.
     */
    pdfBytes: Uint8Array;
}

/**
 * Information about a content page that failed to render.
 */
export interface PageRenderError {
    /**
     * The slug of the page that failed to render.
     */
    slug: string;

    /**
     * The 0-based index in the original page list.
     */
    orderIndex: number;

    /**
     * The error message.
     */
    message: string;
}

/**
 * Result of generating a docs PDF.
 */
export interface DocsPdfGenerateResult {
    /**
     * The generated PDF bytes.
     */
    pdfBytes: Uint8Array;

    /**
     * Content pages that failed to render and were skipped.
     * Only populated when `continueOnPageError` is enabled.
     */
    pageErrors: PageRenderError[];
}
