name: FAI CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/app' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}

jobs:
  check-fai-changes:
    runs-on: ubuntu-latest
    outputs:
      fai_changed: ${{ steps.filter.outputs.fai }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            fai:
              - 'servers/fai/**'
              - 'servers/fai-discord/**'
              - 'servers/fai-lambda/**'
              - 'servers/fai-lambda-deploy/**'
              - 'fern/apis/fai/**'
              - '.github/workflows/ci-fai.yml'

  lint-fai:
    needs: check-fai-changes
    if: needs.check-fai-changes.outputs.fai_changed == 'true'
    runs-on: CLI
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install
        uses: ./.github/actions/install

      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y --version 1.5.1
          cd servers/fai
          poetry install

      - name: Lint & Format
        run: |
          cd servers/fai
          make code-cleanup

      - name: Type check
        run: |
          cd servers/fai
          poetry run mypy .

  lint-fai-discord:
    needs: check-fai-changes
    if: needs.check-fai-changes.outputs.fai_changed == 'true'
    runs-on: CLI
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install
        uses: ./.github/actions/install

      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y --version 1.5.1
          cd servers/fai-discord
          poetry install

      - name: Lint & Format
        run: |
          cd servers/fai-discord
          make code-cleanup

      - name: Type check
        run: |
          cd servers/fai-discord
          poetry run mypy .

  lint-fai-lambda:
    needs: check-fai-changes
    if: needs.check-fai-changes.outputs.fai_changed == 'true'
    runs-on: CLI
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install
        uses: ./.github/actions/install

      - name: Setup poetry for fai-scribe
        run: |
          curl -sSL https://install.python-poetry.org | python - -y --version 1.5.1
          cd servers/fai-lambda/fai-scribe
          poetry install

      - name: Lint & Format fai-scribe
        run: |
          cd servers/fai-lambda/fai-scribe
          make code-cleanup

      - name: Type check fai-scribe
        run: |
          cd servers/fai-lambda/fai-scribe
          poetry run mypy .

      - name: Setup poetry for fai-code-indexing
        run: |
          cd servers/fai-lambda/fai-code-indexing
          poetry install

      - name: Lint & Format fai-code-indexing
        run: |
          cd servers/fai-lambda/fai-code-indexing
          make code-cleanup

      - name: Type check fai-code-indexing
        run: |
          cd servers/fai-lambda/fai-code-indexing
          poetry run mypy .

  test-fai:
    needs: check-fai-changes
    if: needs.check-fai-changes.outputs.fai_changed == 'true'
    runs-on: ubuntu-latest
    environment: Fern Dev
    env:
      FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
      TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      POSTGRES_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/mydatabase
      ASK_FERN_SLACK_BOT_TOKEN: ${{ secrets.ASK_FERN_SLACK_BOT_TOKEN }}
      KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
      KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
      KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
      FAI_LAMBDA_FUNCTION_NAME: ${{ secrets.FAI_LAMBDA_FUNCTION_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y --version 1.5.1
          cd servers/fai
          poetry install
      - name: Create .env file
        run: |
          cd servers/fai
          echo "TURBOPUFFER_API_KEY=${{ env.TURBOPUFFER_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ env.ANTHROPIC_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" >> .env
          echo "COHERE_API_KEY=${{ env.COHERE_API_KEY }}" >> .env
          echo "POSTGRES_DATABASE_URL=${{ env.POSTGRES_DATABASE_URL }}" >> .env
          echo "FERN_TOKEN=${{ env.FERN_TOKEN }}" >> .env
          echo "ASK_FERN_SLACK_BOT_TOKEN=${{ env.ASK_FERN_SLACK_BOT_TOKEN }}" >> .env
          echo "FAI_LAMBDA_FUNCTION_NAME=${{ env.FAI_LAMBDA_FUNCTION_NAME }}" >> .env
          echo "DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }}" >> .env
          echo "DISCORD_OAUTH_URL=${{ env.DISCORD_OAUTH_URL }}" >> .env
          echo "SLACK_CLIENT_ID=${{ env.SLACK_CLIENT_ID }}" >> .env
          echo "SLACK_CLIENT_SECRET=${{ env.SLACK_CLIENT_SECRET }}" >> .env
          echo "SLACK_SIGNING_SECRET=${{ env.SLACK_SIGNING_SECRET }}" >> .env
      - name: test
        run: |
          cd servers/fai
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          poetry run pytest -sv