name: CI

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/app' }}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
  WORKOS_API_KEY: ${{ secrets.WORKOS_API_KEY }}
  WORKOS_CLIENT_ID: ${{ secrets.WORKOS_CLIENT_ID }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # This helps turbo resolve changes faster

      - name: Install
        uses: ./.github/actions/install

      - name: Compile and build
        run: pnpm turbo compile codegen build
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          WORKOS_API_KEY: ${{ secrets.WORKOS_API_KEY }}
          WORKOS_CLIENT_ID: ${{ secrets.WORKOS_CLIENT_ID }}
      - name: Compile Template Resolver
        run: pnpm --filter=@fern-api/template-resolver compile:cjs

      - name: Check dependencies
        run: pnpm depcheck

      - name: Check dependency deduplication
        run: pnpm dedupe --check

      - name: Format YAML
        run: pnpm format:yaml:check

  lint:
    runs-on: CLI
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # This helps turbo resolve changes faster

      - name: Install
        uses: ./.github/actions/install

      - name: Lint style
        run: pnpm lint:style

      - name: biome
        run: pnpm check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # This helps turbo resolve changes faster

      - name: Install
        uses: ./.github/actions/install

      - name: 🧪 Build generator-cli
        run: pnpm turbo --filter=@fern-api/generator-cli compile

      - name: Run tests
        run: pnpm test
        env:
          CI: true

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run tests against local FDR
        run: pnpm --filter=@fern-platform/fdr test:local
        env:
          CI: true
