name: Deploy FDR Python Library Docs Parser Dev

on:
  push:
    branches:
      - app
    paths:
      - "servers/fdr-python-library-docs-parser/**"
      - "servers/fdr-python-library-docs-parser-deploy/**"
      - ".github/workflows/deploy-fdr-python-library-docs-parser-dev.yml"
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: Fern Dev
    env:
      APPLICATION_ENVIRONMENT: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: 🐳 Verify Docker build
        run: |
          cd servers/fdr-python-library-docs-parser
          docker build -t fdr-python-library-docs-parser:test .

      - name: 💻 Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::985111089818:role/github-ci"
          aws-region: us-east-1

      - name: 🚀 Deploy to Dev
        run: |
          git_version="$(git rev-parse --short HEAD)"
          npm install -g aws-cdk
          cd servers/fdr-python-library-docs-parser-deploy
          VERSION="${git_version}" pnpm deploy:dev
