name: Deploy FAI

on:
  workflow_dispatch:
  push:
    tags:
      - "fai@*" 

jobs:
  deploy-prod:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: Fern Prod
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      TURBOPUFFER_API_KEY: ${{ secrets.TURBOPUFFER_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
      POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
      ASK_FERN_SLACK_CLIENT_ID: ${{ secrets.ASK_FERN_SLACK_CLIENT_ID }}
      ASK_FERN_SLACK_CLIENT_SECRET: ${{ secrets.ASK_FERN_SLACK_CLIENT_SECRET }}
      ASK_FERN_SLACK_SIGNING_SECRET: ${{ secrets.ASK_FERN_SLACK_SIGNING_SECRET }}
      SCRIBE_SLACK_CLIENT_ID: ${{ secrets.SCRIBE_SLACK_CLIENT_ID }}
      SCRIBE_SLACK_CLIENT_SECRET: ${{ secrets.SCRIBE_SLACK_CLIENT_SECRET }}
      SCRIBE_SLACK_SIGNING_SECRET: ${{ secrets.SCRIBE_SLACK_SIGNING_SECRET }}
      SCRIBE_DEVIN_API_KEY: ${{ secrets.SCRIBE_DEVIN_API_KEY }}
      SCRIBE_SLACK_BOT_TOKEN: ${{ secrets.SCRIBE_SLACK_BOT_TOKEN }}
      FERN_GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
      FERN_BOT_APP_ID: ${{ secrets.FERN_BOT_APP_ID }}
      FERN_BOT_PRIVATE_KEY: ${{ secrets.FERN_BOT_PRIVATE_KEY }}
      ASK_FERN_SLACK_BOT_TOKEN: ${{ secrets.ASK_FERN_SLACK_BOT_TOKEN }}
      FERNIE_SLACK_BOT_TOKEN: ${{ secrets.FERNIE_SLACK_APP_TOKEN }}
      FAI_LAMBDA_FUNCTION_NAME: ${{ secrets.FAI_LAMBDA_FUNCTION_NAME }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      DISCORD_OAUTH_URL: ${{ secrets.DISCORD_OAUTH_URL }}
      KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
      KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
      KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
      VENUS_URL: ${{ secrets.VENUS_URL }}
      FAI_REINDEXING_SQS_URL: ${{ secrets.FAI_REINDEXING_SQS_URL }}
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
      FAI_SENTRY_DSN: ${{ secrets.FAI_SENTRY_DSN }}
      ORG_AI_CREDIT_CHECK_ORG_IDS: alecharmonspot
      DASHBOARD_API_URL: https://dashboard.buildwithfern.com
      JWT_SECRET_KEY: ${{ secrets.PROD_JWT_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.27.0
          run_install: false
      - name: Create .env file
        run: |
          cd servers/fai
          echo "TURBOPUFFER_API_KEY=${{ env.TURBOPUFFER_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ env.ANTHROPIC_API_KEY }}" >> .env
          echo "COHERE_API_KEY=${{ env.COHERE_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" >> .env
          echo "POSTGRES_DATABASE_URL=${{ env.POSTGRES_DATABASE_URL }}" >> .env
          echo "FERN_TOKEN=${{ env.FERN_TOKEN }}" >> .env
          echo "ASK_FERN_SLACK_CLIENT_ID=${{ env.ASK_FERN_SLACK_CLIENT_ID }}" >> .env
          echo "ASK_FERN_SLACK_CLIENT_SECRET=${{ env.ASK_FERN_SLACK_CLIENT_SECRET }}" >> .env
          echo "ASK_FERN_SLACK_SIGNING_SECRET=${{ env.ASK_FERN_SLACK_SIGNING_SECRET }}" >> .env
          echo "SCRIBE_SLACK_CLIENT_ID=${{ env.SCRIBE_SLACK_CLIENT_ID }}" >> .env
          echo "SCRIBE_SLACK_CLIENT_SECRET=${{ env.SCRIBE_SLACK_CLIENT_SECRET }}" >> .env
          echo "SCRIBE_SLACK_SIGNING_SECRET=${{ env.SCRIBE_SLACK_SIGNING_SECRET }}" >> .env
          echo "SCRIBE_DEVIN_API_KEY=${{ env.SCRIBE_DEVIN_API_KEY }}" >> .env
          echo "SCRIBE_SLACK_BOT_TOKEN=${{ env.SCRIBE_SLACK_BOT_TOKEN }}" >> .env
          echo "FERN_BOT_GITHUB_TOKEN=${{ env.FERN_BOT_GITHUB_TOKEN }}" >> .env
          echo "FERN_BOT_APP_ID=${{ env.FERN_BOT_APP_ID }}" >> .env
          echo "FERN_BOT_PRIVATE_KEY=${{ env.FERN_BOT_PRIVATE_KEY }}" >> .env
          echo "ASK_FERN_SLACK_BOT_TOKEN=${{ env.ASK_FERN_SLACK_BOT_TOKEN }}" >> .env
          echo "FERNIE_SLACK_BOT_TOKEN=${{ env.FERNIE_SLACK_BOT_TOKEN }}" >> .env
          echo "DISCORD_BOT_TOKEN=${{ env.DISCORD_BOT_TOKEN }}" >> .env
          echo "DISCORD_OAUTH_URL=${{ env.DISCORD_OAUTH_URL }}" >> .env
          echo "KV_REST_API_TOKEN=${{ env.KV_REST_API_TOKEN }}" >> .env
          echo "KV_REST_API_READ_ONLY_TOKEN=${{ env.KV_REST_API_READ_ONLY_TOKEN }}" >> .env
          echo "KV_REST_API_URL=${{ env.KV_REST_API_URL }}" >> .env
          echo "VENUS_URL=${{ env.VENUS_URL }}" >> .env
          echo "FAI_LAMBDA_FUNCTION_NAME=${{ env.FAI_LAMBDA_FUNCTION_NAME }}" >> .env
          echo "FAI_REINDEXING_SQS_URL=${{ env.FAI_REINDEXING_SQS_URL }}" >> .env
          echo "POSTHOG_API_KEY=${{ env.POSTHOG_API_KEY }}" >> .env
          echo "EDGE_CONFIG=${{ env.EDGE_CONFIG }}" >> .env
          echo "FAI_SENTRY_DSN=${{ env.FAI_SENTRY_DSN }}" >> .env
          echo "ORG_AI_CREDIT_CHECK_ORG_IDS=${{ env.ORG_AI_CREDIT_CHECK_ORG_IDS }}" >> .env
          echo "DASHBOARD_API_URL=${{ env.DASHBOARD_API_URL }}" >> .env
          echo "JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }}" >> .env
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::985111089818:role/github-ci"
          aws-region: us-east-1
      - name: Deploy to prod
        run: |
          git_version="$(scripts/fai-version.sh)"
          cd servers/fai
          ./scripts/create_docker.sh "${git_version}"
          cd deploy
          pnpm install
          VERSION="${git_version}" npm run cdk deploy fai-prod --require-approval never --progress events
