name: Publish FDR Lambda SDK

on:
  workflow_dispatch:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"

permissions:
  id-token: write
  contents: read

jobs:
  publish_typescript_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Build and test
        run: pnpm turbo compile test --filter=@fern-api/fdr-lambda-sdk

      - name: Publish FDR Lambda TypeScript SDK
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
        run: |
          git_version="$(scripts/fdr-version.sh)"

          cd packages/fdr-lambda-sdk
          npm version "$git_version" --no-git-tag-version
          pnpm publish --access public --tag latest --no-git-checks

  publish_python_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📥 Install
        uses: ./.github/actions/install

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish FDR Lambda Python SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          git_version="$(scripts/fdr-version.sh)"
          fern generate --api fdr --group fdr-lambda-python-sdk --version ${git_version}
