name: Publish FDR SDKs

on:
  workflow_dispatch:
  push:
    tags:
      - "fdr@*"
    branches:
      - "app"
    paths:
      - "fern/apis/fdr/**"
      - "fern/fern.config.json"
      - "servers/fdr-deploy/**"
      - "servers/fdr/**"
      - ".github/workflows/deploy-fdr-dev.yml"
      - ".github/workflows/publish-fdr-sdk.yml"
      - "packages/fdr-sdk/**"
      # Remove this once fdr is no longer needed in the generation
      - "packages/fern-docs/search-server/**"
      - "pnpm-lock.yaml"

env:
  PACKAGE_NAME: "@fern-platform/fdr"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "buildwithfern"
  FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: 📥 Install
        uses: ./.github/actions/install
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: 🧪 Build and test
        run: pnpm turbo codegen build test --filter=${{ env.PACKAGE_NAME }}

      - name: Install Fern
        run: npm install -g fern-api

      - name: Publish FDR SDK
        run: |
          git_version="$(scripts/fdr-version.sh)"
          working_dir=$(pwd)

          cd packages/commons/core-utils
          npm version "$git_version" --no-git-tag-version
          pnpm publish --access public --tag latest --no-git-checks

          cd $working_dir/packages/fdr-sdk
          npm version "$git_version" --no-git-tag-version
          pnpm publish --access public --tag latest --no-git-checks

  notify:
    needs: publish_sdk
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v3
        with:
          method: chat.postMessage
          token: ${{ secrets.FERNIE_SLACK_APP_TOKEN }}
          payload: |
            {
              "channel": "#docs-notifs",
              "text": "FDR SDK Publish ${{ needs.publish_sdk.result }}: ${{ github.ref_name }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
            }
