name: Check Sites

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  up:
    name: Check if sites are up (US)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Log location info
        run: curl ipinfo.io
      - uses: actions/checkout@v4
      - name: Copy domain list
        run: cp scripts/monitor/sites.csv sites.csv
      - name: Install dependencies
        run: pip install git+https://github.com/fern-api/incident-python.git requests
      - name: Check Sites
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
        run: python scripts/monitor/check_sites.py US

  up-eu:
    needs: up
    if: false
    name: Check if sites are up (via EU runner)
    runs-on:
      group: International
      labels: eu
    timeout-minutes: 10
    steps:
      - name: Log location info
        run: curl ipinfo.io
      - uses: actions/checkout@v4
      - name: Copy domain list
        run: cp scripts/monitor/sites.csv sites.csv
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install git+https://github.com/fern-api/incident-python.git requests
      - name: Check Sites
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
        run: python scripts/monitor/check_sites.py EU
