/**
 * This file was auto-generated by Fern from our API Definition.
 */

import type * as FdrLambda from "../../../../../../../index.js";

export interface DocsUrlMetadata {
    url: FdrLambda.Url;
    org: FdrLambda.OrgId;
    isPreviewUrl: boolean;
    gitUrl?: FdrLambda.Url;
}
