/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FdrLambda from "../../../../../../../index.js";

export interface EnsureDocsInS3Response {
    s3Url: FdrLambda.Url;
    orgId: FdrLambda.OrgId;
}
