// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

/**
 * Partial docs definition response containing only the requested fields
 */
export interface GetDocsFieldsResponse {
    domain: string;
    baseUrl: FdrLambda.docs.v2.read.BaseUrl | undefined;
    filesV2: Record<FdrLambda.FileId, FdrLambda.docs.v1.read.File_> | undefined;
    apisV2: Record<FdrLambda.ApiDefinitionId, FdrLambda.api.latest.ApiDefinition> | undefined;
    apis: Record<FdrLambda.ApiDefinitionId, FdrLambda.api.v1.read.ApiDefinition> | undefined;
    pages: Record<FdrLambda.PageId, FdrLambda.docs.v1.read.PageContent> | undefined;
    jsFiles: Record<string, string> | undefined;
    config: FdrLambda.docs.v1.read.DocsConfig | undefined;
    root: FdrLambda.navigation.v1.RootNode | undefined;
}
