// This file was auto-generated by Fern from our API Definition.

import type * as FdrLambda from "../../../../../../../index.js";

export interface LoadDocsForUrlResponse {
    orgId: FdrLambda.OrgId;
    baseUrl: FdrLambda.docs.v2.read.BaseUrl;
    definition: FdrLambda.docs.v1.read.DocsDefinition;
    lightModeEnabled: boolean;
}
