/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         repo_urls: ["repo_urls"]
 *     }
 */
export interface IndexGithubRequest {
    /** GitHub repository URLs to index */
    repo_urls: string[];
}
