// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { V2Client } from "../resources/v2/client/Client.js";

export declare namespace DocsClient {
    export interface Options extends BaseClientOptions {}
}

export class DocsClient {
    protected readonly _options: DocsClient.Options;
    protected _v2: V2Client | undefined;

    constructor(options: DocsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get v2(): V2Client {
        return (this._v2 ??= new V2Client(this._options));
    }
}
